### ISSUE TITLE
If you use a Group or Light in more than one flow -> Connection Error

### ISSUE THREAD

**Issue by RobertHerter** [Foddy/node-red-contrib-huemagic#1]
Hello,

great Nodes. One Problem i have switching to huemagic:
If i a Node of one Lamp or Group in more than one flow, i got a connection error.

I would be nice if the Node would output the Lamp/Group config (as name, Lighttype ...)
not only the id.

**Comment by Foddy** [comment]
Hi,

thanks for your feedback! Unfortunately I could not reproduce a connection error when using the same light / group additionally on other flows. 

- Do you get some more details other than that on your debug tab?
- Do you get a connection error on Node-RED or (under) the group / light? 
- Are you using the most recent version of Node-RED (which is currently 0.17.5)? If not, please upgrade and try again.

Regarding your other feature request of a node with more details on devices – I am already working on that and will release the update soon ;)
