### ISSUE TITLE
Bulb ID in Topic

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#10]
Rather than force the choice of a bulb ID in the node could you make this an input such as Topic. This can be chosen if the ID is left as zero in the node. This allows the node to be driven from a SQL database where Hue is but one of the types of light that the database might simultaneously select. It also allows the light to be selected from an MQTT message.

**Comment by Foddy** [comment]
This is a really good idea! I will implement this „feature“ in the next coming version soon!

Thanks ;)!

**Comment by lespatots** [comment]
Hi,

I look forward to the upgrade and as I modify my node-red I can let you have my complete work. Let me elaborate on what I am doing as this might influence some of your thoughts.

I wanted to create a general solution for lighting that allowed mix/match of lighting systems and mix/match of control options. The plan is to have a database of lights wherein the control system is listed and which can be used to select a control pathway in node-red. At present I have only Hue and MQTT driven products but I can select a mix of lights (objects) and set them to a ’scene’ state as defined in the database. The next step was to ‘poll’ the Hue lights to get their current state and keep this in the database. That would allow for local control of a lamp (via a philips dimmer) and for the overall system to aware of changes. One of the outcomes would be the ability to reset the hue lights to their last state following a ‘power outage’ (or any other state for that matter!)

I’d also like to catch the switch operations rather than the consequence if possible so that a Hue switch could initiate a ’scene’ which included none Hue items. This is probably all going to end up in Apple Homekit but Apple is not taking the driving seat here. Having alternate interfaces allows for the use of the Node-Red dashboard but also allows integration using MQTT and other dashboards built on MQTT as a control and logging platform.

My flow at present goes like this. A button creates an SQL query that selects objects from the database. A parallel interator then creates multiple threads, one for each object. The object passes by a switch node that directs the object to a control pathway depending on the objects needs. Hue bulbs go to the Hue Set function, whilst Sonoff objects go to an MQTT function. Depending on the function, there could then be a node to read and check the state to confirm the set command. It is perfectly possible to have slight variations for the different Hue bulb types (not implemented) and for simple versus complex commands (not implemented).

Some other functionality such as Timer (using Peter Scargill’s Big Timer) can be added to the front end as a trigger and I was toying with using the result of a status read to possibly also act as a trigger. This is a clumsy way of detecting a switch’s effect rather than the switch itself!

Some things don’t work well in Node-Red like polling light states as it uses too much processing but doing this at a lower level or catching changes would be ok.

I ignored your warnings and tried to install your node suite in parallel with my existing Hue Plus implementation. I had thought I could switch the appropriate pages off. Still trying to revert the mess-up I made of the Bridge selection! I guess I should do what I planned and create a separate sandbox!

Regards

Richard

**Comment by Foddy** [comment]
This sounds really interesting!

If you are ready please let me know about it, I would love to try it out and use it for my home automation!

**Comment by lespatots** [comment]
Hi,

Please send me a PM and I’ll send you the flow and some more files for the database. It would be quite a bit of work to create the working environment as you need to run the database or at least put one some where. Otherwise the flow is relatively straightforward. It is a bit of a mess at present as it is in a bit of an in-between state. What I mean is that MQTT could be an interface between IOT switches and lights (read controlled devices) and the database could be another place where the current state might be kept to handle say a power reset. MQTT is also one way to interface the current light states to the dashboard. So there are nodes/flows to update MQTT and the database. There are some concepts like light groups and scenes that go well with a database and with a GUI select/sort/action would be a doddle. At present it is necessary to manually create a SELECT in SQL to pick the appropriate objects (lights) and have access to the control flows.

Richard

**Comment by Foddy** [comment]
I will! Do you also plan to publish this flow on NodeRed? 
v1.1.8 of HueMagic with manual light and group Ids in msg.topic just released

**Comment by Foddy** [comment]
Hi lespatots,

since I am not able to write you a PM via GitHub, could you write me an email instead at github@foddys.com?

**Comment by lespatots** [comment]
That’s a big step for me as a total newbie to most of this. But, I do think with a bit of tweaking and integration with HueMagic it might be a very useful solution to cross platform systems, So for example adding Tradfri from IKEA would be quite simple as would adding any other system with appropriate nodes to set and query lights!

The other bit I am missing is input from someone else. Perhaps the solution I have is too clumsy or difficult to be used. I don’t think it is because I’m hoping the flow will do everything but select the lights or scene you want.

Rather than me integrating with Huemagic, perhaps this is something you could do much more easily than I could?

Richard
