### ISSUE TITLE
Friends of Hue support

### ISSUE THREAD

**Issue by winchor** [Foddy/node-red-contrib-huemagic#102]
**Is your feature request related to a problem? Please describe.**
I bought Niko [friends of hue dimmer switches](https://www.niko.eu/en/campaign/partners/philips-hue) which are not correctly recognized by huemagic.
Although being called a "dimmer" switch (type ZLLSwitch in the Hue bridge), it is recognized as a "tap" (ZGPSwitch) by the Hue Bridge. 
The button events use the following numbers:
16 (initial) or 20 (short-release) -> On
17 or 21 -> Off
18 or 22 -> Dim down
19 or 23 -> Dim Up
Using the hue-tap.js node, which only checks button events 34, 16, 17, 18, I often get, as expected, the  'buttonNum' value 0.  

**Describe the solution you'd like**
It would be great to have a 'niko-dimmer-switch' node. I believe it should be a mix between hue-tap, because of the type recognized, i.e. ZGPSwitch and hue-switch, because of the double numbering, i.e. initial and short-release.  

**Describe alternatives you've considered**
Good opportunity to prove, if need be that node-red really applies the good ol' TIMTOWTDI principle!
The following workaround works:
I use the hue-tap node to capture and send the device id to a subflow. 

![niko1](https://user-images.githubusercontent.com/56488343/66722133-466ad180-ee0a-11e9-94dc-6a01bde34867.JPG)

With that id, a function builds an url used by the http-request node to get the buttonevent state (i.e. the button pressed) from the hue bridge API. I then assign actions depending on the button number.

**Comment by Foddy** [comment]
Thanks for the hint! As of version 2.0.3, you now get the button event of the bridge directly via the property "buttonAlt"
