### ISSUE TITLE
Hue Smart Plug shows NaN for brightness

### ISSUE THREAD

**Issue by georgemathieson** [Foddy/node-red-contrib-huemagic#103]
**Describe the bug**
Philips has recently released a [new smart plug](https://www2.meethue.com/en-gb/p/hue-smart-plug/8718699689308) that shows as a light under HueMagic.

The smart plug obviously has no way of determining or controlling the brightness of a bulb, and as such the brightness shows as NaN.

**Flow to Reproduce**
Use a Hue Lights node and select a Philips Smart Plug from the Lights dropdown. NaN will display under the node for brightness once deployed.

**Expected behavior**
It shouldn't display a brightness when a smart plug is selected.

**Additional context**
The smart plug is intended to be used to control a light which explains why it shows in the list of lights rather than as its own device. The smart plug's model id is `LOM003`.

**Comment by Foddy** [comment]
Should be fixed in 2.0.3. Please reopen if this is not the case
