### ISSUE TITLE
Motion Sensor and Switch on second bridge are not working

### ISSUE THREAD

**Issue by ThomasPoett** [Foddy/node-red-contrib-huemagic#104]
It got a little worth.
Since approx 5 days the switches and sensors aren't working anymore.
With the Hue App, I can see the motion e.g. is triggered, but i do not get an feedback in huemagic.
I have deleted the node and was re-doing the config but doesn't helped.
(Note: Lights can be still controlled on the 2nd bridge)
The behavior was the same, since i only did the update to the actual version today.

Any advice?

**Comment by ThomasPoett** [comment]
is fixed with 2.0.4 today.
Thnx mate amazing work !!!!

**Comment by gekkie** [comment]
Hi,

Sorry but it looks like it's back! 2.0.4 is installed and the motion sensor is registering with Hue app and iConnectHue. Just to make sure I just spun up a fresh install of node-red on the pi4.

**Comment by gekkie** [comment]
ok. Just rebooted both my v2 bridges and everything seems to be working again.
