### ISSUE TITLE
Hue hang up error

### ISSUE THREAD

**Issue by ThomasPoett** [Foddy/node-red-contrib-huemagic#105]
Still with version 2.0.4 on several bulbs i have this issue.
Cant be solved by 2nd API user, only grp node, but in my case this is only a temp work around.

![image](https://user-images.githubusercontent.com/43953071/67140713-9cea6c80-f25d-11e9-956f-132897fcefb7.png)

**Comment by ThomasPoett** [comment]
maybe here the screenshot after changing it to a grp
![image](https://user-images.githubusercontent.com/43953071/67140748-f6529b80-f25d-11e9-8d91-651a2713f13a.png)

**Comment by Foddy** [comment]
This is really strange as HueMagic does a batch request anyway to get all lights and their current states in background.

So you should face these errors anyway if I don’t overthink something. Unfortunately the Hue Bridge only offers a REST API at the moment and not a websocket based one, which leads to this kind of performance issues – especially with many lights connected. This might change in near future (as far as I know) with a firmware upgrade for the bridge.

You could try to increase the poll interval to a higher number until then. Maybe this will help to avoid this errors... 😶?

**Comment by ThomasPoett** [comment]
tnx for your fast answer. well i will try increasing the poll interval and let you know.
What else is wired, the mobile app and win app make change super fast. but i experience issue with Alexa since 2-3 week to: with the statements:
- hub not responsive, - even telling me having double names on devices/ rooms.
I believe HUE is not ready for semi-pro zigbee bridge ;)

**Comment by Foddy** [comment]
Huejay is no longer used in the latest update.
It should be fixed now
