### ISSUE TITLE
Only update light status when inject

### ISSUE THREAD

**Issue by svaneepoel** [Foddy/node-red-contrib-huemagic#107]
**Is your feature request related to a problem? Please describe.**
For example, I would like to have the Hue light node to only update when it's get an inject (timestamp for example). At this time, it keeps updating when the light changes.

**Describe the solution you'd like**
An option that a light node only updates the status when it get an inject.

**Additional context**
I've the following simple NodeRed flow, which looks at one of my Hue groups and saves the state of it in a variable.

[https://preview.redd.it/qzj1vqrvguv31.png?width=795&format=png&auto=webp&s=117b80ee70b18457d9e1fe8cd5d400e4918c40fb](url)
This is working fine, but the problems is that the variable also get's an update when I change the light in my Hue app.

I want to save the variable only when I inject it.

**Comment by Foddy** [comment]
Should be possible with the skip events option on node configuration
