### ISSUE TITLE
Sorry. Your selected Hue Bridge is invalid!

### ISSUE THREAD

**Issue by nodecentral** [Foddy/node-red-contrib-huemagic#109]
Hi

No matter what I do I keep getting the error "Sorry. Your selected Hue Bridge is invalid!"

I’ve confirmed that the IP is correct, and now tried multiple times to connect but I can’t get it to register ? 

If I try to search for the hue hub using the magnifying glass,  it’ll report that it is ‘searching’ but not find anything in the end it’ll return the word  ‘null’ along with a message "Something went wrong. Please retry."

**Comment by stahchde** [comment]
downgrading to 2.0.4 solves this issue

**Comment by Swiftnesses** [comment]
I also have the issues (V1 Hub).

**Comment by Foddy** [comment]
If you guys have the square shaped Philips Hue Bridge and the latest version of HueMagic, then this issue should be fixed
