### ISSUE TITLE
Alert not reset state

### ISSUE THREAD

**Issue by ycharron-cstj** [Foddy/node-red-contrib-huemagic#11]
Hello,
The alert message doesn't reset the state of the light.
This is message I send to the Light 
**msg.payload = {
    "alert": 1,
    "rgb": [0,255,0]
};
**
The light stay green forever after

**Comment by Foddy** [comment]
Hi,

thank you for this report. I've just fixed that in version 1.1.9.

Note that HueMagic is currently not able to reset all the lights to their previous states if you pass an alert command on a group node. If you send the alert command on a light node it should work as expected.
