### ISSUE TITLE
Toggle with settings

### ISSUE THREAD

**Issue by ArnieX** [Foddy/node-red-contrib-huemagic#110]
Hi,

I would like to propose, hopefully simple addition. I’m currently connecting my full featuref smarthome together and for lighting I chose Philips Hue, wall switches are basic ones with CAT5e cables run to them to just send signals to my main unit, which then using NodeRed says what shall be done when it’s clicked.

Now I use toggle because I’m unaware of the state the light is currently in (even that I could likely implement such identification it would bring considerable complication to rather simple configuration as of now). Issue is that toggle doesn’t let me specify what is the state I would like to set the light to in case that toggle will turn it on. I would like to set these parameters different based on time of day.

So if it would be possible to add more settings to toggle feature that would be very welcome.

Thank you.

**Comment by Foddy** [comment]
With 2.8.0+ you can now change the device state (colors, brightness etc.) even if it's turned off. So the next time you run `toggle`, it should turn the light(s) on with the previously applied commands in "off" mode.

**Comment by ArnieX** [comment]
Hi Foddy, thank you for that. I have just tested your changes but a little unfortunate thing is that the change happen almost 5-10seconds after the light turn on. Which is little too long to be useful. Can you somehow optimise that please?

**Comment by Foddy** [comment]
Hmm... I think this happens because of the use of different nodes for the same device.

– You trigger a command for device A on Node A
– Then you trigger a command for device A on Node B

Is that correct?

**Comment by ArnieX** [comment]
Not really.

I have wall switch that triggers function in nodered which send toggle command to NODE - LIVINGROOM (that is Hue Magic Node), then I have simple inject node which changes color only. Let's say to red - {"color":"red"} - and it is pointed to the same NODE - LIVINGROOM. Then after I click inject node, color is injected, then couple seconds later (~20s) I click the wall switch which immediately turn on the light. But the color is white (for example) and after 5-10s it changes to red. So it seems like Hue is waiting with the change for the time when the light is on, but it takes some time for it to remember that there was color change requested.

**Comment by Foddy** [comment]
Can you please try it with this example? Do you also have this issue with the "toggle" command or just with the turn on / off command?

In my tests it currently occurs only with the turn on / turn off commands, so I could replicate that – but the delay is like max 1 second or so. I think I can change some things here if it only happens with the "on / off" commands...

`
[{"id":"dfe4b558.db7be","type":"tab","label":"Issue #110","disabled":false,"info":"I have wall switch that triggers function in nodered which send toggle command to NODE - LIVINGROOM (that is Hue Magic Node), then I have simple inject node which changes color only. Let's say to red - {\"color\":\"red\"} - and it is pointed to the same NODE - LIVINGROOM. Then after I click inject node, color is injected, then couple seconds later (~20s) I click the wall switch which immediately turn on the light. But the color is white (for example) and after 5-10s it changes to red. So it seems like Hue is waiting with the change for the time when the light is on, but it takes some time for it to remember that there was color change requested."},{"id":"7418698e.1b80e8","type":"inject","z":"dfe4b558.db7be","name":"Toggle","topic":"","payload":"{\"toggle\":true}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":120,"wires":[["72f09f2a.81ee18"]]},{"id":"42e10255.cf8ecc","type":"inject","z":"dfe4b558.db7be","name":"Red Color","topic":"","payload":"{\"hex\":\"#ff0000\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":240,"y":180,"wires":[["72f09f2a.81ee18"]]},{"id":"8c84b465.5a4bf8","type":"inject","z":"dfe4b558.db7be","name":"Blue Color","topic":"","payload":"{\"hex\":\"#0000ff\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":240,"y":220,"wires":[["72f09f2a.81ee18"]]},{"id":"652a4373.4e64d4","type":"inject","z":"dfe4b558.db7be","name":"Turn On","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":300,"wires":[["72f09f2a.81ee18"]]},{"id":"cee324f0.c5d728","type":"inject","z":"dfe4b558.db7be","name":"Turn Off","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":250,"y":340,"wires":[["72f09f2a.81ee18"]]},{"id":"72f09f2a.81ee18","type":"hue-light","z":"dfe4b558.db7be","name":"","lightid":"","colornamer":true,"skipevents":false,"x":500,"y":220,"wires":[[]]}]
`

**Comment by ArnieX** [comment]
I will try this when I get home tomorrow and let you know.

**Comment by ArnieX** [comment]
Hi Foddy, it took a bit longer :D, now I have tested it with double output function, first output sends payload with color change and the second one does toggle. It indeed is instant now, when toggle happen the color is already changed. At least from this quick test I would say it works now. Thanks.
