### ISSUE TITLE
Error: Philips Hue: 8, parameter, linkbutton, is not modifiable

### ISSUE THREAD

**Issue by Webunity** [Foddy/node-red-contrib-huemagic#111]
I have this flow:
![image](https://user-images.githubusercontent.com/186093/69740171-42381080-1139-11ea-9d83-75a52337fcf0.png)

With this inject node:
![image](https://user-images.githubusercontent.com/186093/69740158-3b110280-1139-11ea-8497-387b37bf4d36.png)

Resulting in this msg object;
![image](https://user-images.githubusercontent.com/186093/69740132-2f254080-1139-11ea-8081-2f880e8302e8.png)

And this error while pressing it:
![image](https://user-images.githubusercontent.com/186093/69740194-4ebc6900-1139-11ea-9ae3-89579ea5fdb2.png)

am i doing something wrong?

**Comment by Foddy** [comment]
Thanks for the hint! According to the Hue API docs:
> Starting  1.31, Writing is only allowed for Portal access via cloud application_key.

So this is no longer possible in this form. Sorry :S
