### ISSUE TITLE
No output from Switch or Light Nodes

### ISSUE THREAD

**Issue by sammachin** [Foddy/node-red-contrib-huemagic#116]
**Describe the bug**
I now have an issue where there is no msg output from the hue nodes, either a Hue Light or a Hue Switch node . I see the status update under the node but comes from the output, if I put a debug node onto it. 
Its fine in 1.9.0 but broken in 2.0.4 (not sure about intermediate releases)

**Flow to Reproduce**
```
[{"id":"dc7f2e20.652a4","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d9893764.60b638","type":"hue-light","z":"dc7f2e20.652a4","name":"Office Ceiling","bridge":"f75d93c4.8ddc8","lightid":"7","colornamer":true,"x":590,"y":480,"wires":[["f3d7ca7c.2e226"]]},{"id":"7dc4002e.fffdb","type":"hue-switch","z":"dc7f2e20.652a4","name":"Conservatory switch","bridge":"f75d93c4.8ddc8","sensorid":"5","x":570,"y":600,"wires":[["f3d7ca7c.2e226"]]},{"id":"92654d6c.c3e1d8","type":"inject","z":"dc7f2e20.652a4","name":"On","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":460,"wires":[["d9893764.60b638"]]},{"id":"f3d7ca7c.2e226","type":"debug","z":"dc7f2e20.652a4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":940,"y":520,"wires":[]},{"id":"f75d93c4.8ddc8","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.1.144","key":"Dc15u1kwLj7IzWqPbHEkb4IT1oJIKkpVXAyeIKP7","interval":"3000"}]
```

**Expected behavior**
The node should output a msg object similar to this:
```
{"payload":{"on":true,"brightness":100,"updated":"2019-12-25T18:26:03+00:00"},"info":{"id":7,"uniqueId":"00:17:88:01:10:59:a1:c5-0b","name":"Office Ceiling","type":"Dimmable light","softwareVersion":"5.127.1.26420","model":{"id":"LWB006","manufacturer":"Philips","name":"Hue A19 Lux","type":"Dimmable Light","colorGamut":null,"friendsOfHue":true}},"_msgid":"139d2062.98bc2"}
```

**Please complete the following information:**
 - NodeRED version: 1.0.3
 - NodeJS version: v12.14.0
 - Device running NodeRED: Pi4

**Comment by Foddy** [comment]
Can you try updating to v2.1? Please tell me if this is still the case with the newest version

**Comment by sammachin** [comment]
Sorry my mistake I was tryign with 2.1.0 and that had the problem so I downgraded to 1.9.0 which I knew was good. I've now checked 2.0.4 and that is good  so the issue seems to have been introduced at 2.1.0

**Comment by Foddy** [comment]
Did you unchecked the "disable node events" option in your bridge config?

![Bildschirmfoto 2019-12-26 um 10 39 50](https://user-images.githubusercontent.com/5302050/71470369-3a1cd080-27cc-11ea-9520-f3d66062d162.png)

**Comment by sammachin** [comment]
Just tested that it was unchecked by default after the update, tried with it on, then off again no difference

**Comment by pirminbucher** [comment]
I have the same problem, also updated from 2.0.4 to 2.1. All was fine with 2.0.4, but not with 2.1. Found this here (sendSceneInfo vs. message), not shure if related?
![image](https://user-images.githubusercontent.com/29455929/71534928-6175b980-2902-11ea-80e8-295c2d92c265.png)

**Comment by vBiggles** [comment]
After update to 2.1 - I had the same problem, I went into each node and changed it from one hue end point to another random one then deployed then went back in and changed it back to the correct lamp, motion, switch etc and deployed and it worked fine after I did that to all the hue magic nodes.

M

**Comment by Foddy** [comment]
Okay, I found the bug. Excuse the circumstances!
A new update and fix will be released later in the day.

**Comment by stahchde** [comment]
Hi, with 2.1.1 I also have this issue. When I try to configure a new bridge I get the Info "Sorry, your selected bridge is invalid. And when I start to search for a bridge ip, it shows the error " something went wrong, Please retry

**Comment by FreeTimeCoder82** [comment]
Hi, I found the problem.
All existing nodes, displays an unchecked options "Skip events from node", but it seems to be true inside the node. When you check and then uncheck it and then deploy again, it will work fine.
I think it will is because this option is new an on existing node this options has never been set, so it is on by default, but not displayed.

**Comment by Foddy** [comment]
It is annoying. To be honest, I don't understand the reason behind it, because the default value for Node-RED was set to "false".

That's how it is queried:
`if (typeof config.skipevents == 'undefined' || config.skipevents == false) {scope.send (message); }`

Does anyone know why this happens? :S

**Comment by FreeTimeCoder82** [comment]
`if (!config.skipevents) {scope.send(message);}`
What about this?
This should handle undefined, null and also false if it exists.

**Comment by Foddy** [comment]
Good note... I will apply this in the next minutes 🤭
