### ISSUE TITLE
use transitiontime on the scene node

### ISSUE THREAD

**Issue by tuxtof** [Foddy/node-red-contrib-huemagic#117]
ability to call a scene with a transition time

actually when we use scene object the scene is activated immediatly

it will be great to be able to pass a msg.payload.transitionTime like in light and group object

**Comment by Foddy** [comment]
I also wish I could implement this feature but unfortunately the Hue Bridge API does not offer any transition possibilities for scenes at this time. You could implement some kind of delay but I guess this is not what you want.

I'll keep an eye on the official docs and let you know if this feature is officially supported by Philips Hue.

**Comment by tuxtof** [comment]
oh , i believe you can use transitiontime and scene argument in same time on the PUT groups/<id>/action, but you are right it seems not working :-(

my goal was to reimplement the sunset logic with a fading scene, as the builtin routing

**Comment by Foddy** [comment]
Maybe the new "Hue Magic" node in v2.2 will solve your problem ;)

**Comment by tuxtof** [comment]
thanks for the tips, but not totally or easily
hope they will solve the group call scene problem soon

in the meantime i will test transition time included in the scene

**Comment by mikewoodld** [comment]
Just wanted to check on this to see if there was any movement on the Phillips side? Would be a great feature to have.

**Comment by mikewoodld** [comment]
Hey @Foddy - Just wanted to check in to see if Phillips/Hue has implemented this at all yet?
