### ISSUE TITLE
TypeError when using the random color feature

### ISSUE THREAD

**Issue by shopro** [Foddy/node-red-contrib-huemagic#118]
I have set my IKEA TRÅDFRI colored bulbs to get a new color every 5min for 7 bulbs using Hue Group.

But I keep getting _"TypeError: Expected a valid hex string"_ errors about every 3rd run, so about every 15 minutes, or sometimes it can come for example 3 times in a row and work 10 times in a row after.

Occasionally it happens with another error _"Error: Huejay: read ECONNRESET"_, but I'm assuming that is related with the Hue Bridge not being able to keep up with the requests.

**Comment by bergjet** [comment]
Have the same problem with Hue lamps.

**Comment by WoodyLetsCode** [comment]
I have the same problem.

![grafik](https://user-images.githubusercontent.com/27882680/83925210-ece35880-a786-11ea-93cb-f7185ce33458.png)

**Comment by Foddy** [comment]
Should be fixed in the latest release
