### ISSUE TITLE
V2.2.2 'something went wrong' / 'Sorry. Your selected Hue Bridge is invalid!'

### ISSUE THREAD

**Issue by Swiftnesses** [Foddy/node-red-contrib-huemagic#119]
I can no longer search scenes with this version, "Something went wrong. Please retry."

Further, trying to add a new hub (v1) displays, "Sorry. Your selected Hue Bridge is invalid!".

**Comment by fabsewup** [comment]
I cann`t connect my hue bridge. I always get the error as well. 

"Sorry. Your selected Hue Bridge is invalid!"

**Comment by zaphood1967** [comment]
Same here

**Comment by Foddy** [comment]
Can you please update to v2.2.3 and retry?

**Comment by Swiftnesses** [comment]
@Foddy Fixed for me (both issues), thank you!

**Comment by zaphood1967** [comment]
Works for me as well with 2.2.3. Thanks for that lightning fast update !
