### ISSUE TITLE
Hue Magic 'Custom Animation' = "SyntaxError: Unexpected token o in JSON at position 1"

### ISSUE THREAD

**Issue by Swiftnesses** [Foddy/node-red-contrib-huemagic#120]
I get this even using the example flow.

Is there a workaround, would love to use this in my New Year flow tonight!

**Comment by Foddy** [comment]
Sorry for my late response. I was out of space at this time :S 

Hope you had a good alternative for your New Year flow.. This should have been fixed with the latest version.
