### ISSUE TITLE
Recall Hue scenes for groups

### ISSUE THREAD

**Issue by guenter-ms** [Foddy/node-red-contrib-huemagic#121]
Hi,
first of all, this is the best HUE implementation I've ever seen. Congratulations!

What I am really missing is, to launch a scene for a given group of lights.

According to the Philips HUE API, a scene must be recalled by the "Set group State" command and passing the property "scene" with the scene identifier you wish to recall. This command also accepts the group id to specify the group id of affected lights for the scene. Group 0 means "all".

See HUE API 2.5.3. documentation for Sample Body:
Note: Use group id 0 to recall a scene for all lights (which are part of the scene), or use another group id if you want to recall the scene for a specific group of lights. E.g. Using group 2 would recall the scene for all lights that are in group 2 AND are part of the specified scene.

I have created a lot of scenes, containing all Lights from the bridge. And using the HUE API native (what I like to replace with HueMagic), I can launch a scene "Sunset" for each group of lights separateley by specifying the group <id>.

I am kindly requesting either

a) to provide a groups parameter in your "Hue Scene" node, to launch a scene for a specific group of 
lights (assuming today group "0" is passend to the bridge to launch all lights defined in the scene) 

OR

b) to provide a "scene" parameter in your "Hue Group" node to pass the scene id to the bridge, which has the same effect on the HUE API.

I prefer a) because it is more logically to your users.

Hopefully a small change with big advantages for all users!

Thank you very much for your reply.
Guenni/Muenster/Germany

**Comment by Foddy** [comment]
Hi Guenter,

thank you for enjoying it! Your enhancement sounded too useful not to implement it. Therefore it is available now with v2.2.5 :)!
