### ISSUE TITLE
Hue Magic node error

### ISSUE THREAD

**Issue by bergjet** [Foddy/node-red-contrib-huemagic#122]
The node show me "TypeError: Cannot read property 'on' of undefined"

<img width="1369" alt="Screenshot 2020-01-05 10 06 36" src="https://user-images.githubusercontent.com/4241968/71777664-4b6f9500-2fa3-11ea-8460-79a769be3f2a.png">

ioBroker
node.js 10.18.0
node-red 1.14.0

**Comment by Foddy** [comment]
Hmm... can you share your Flow please?

**Comment by bergjet** [comment]
[
    {
        "id": "e9340415.4862d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9e71e69f.4f71d",
        "type": "nighttime",
        "z": "e9340415.4862d",
        "name": "",
        "lon": "23",
        "lat": "15",
        "start": "sunrise",
        "end": "sunsetStart",
        "x": 146.5,
        "y": 322,
        "wires": [
            [
                "eb99bc92.e9093"
            ],
            []
        ]
    },
    {
        "id": "eb99bc92.e9093",
        "type": "hue-magic",
        "z": "e9340415.4862d",
        "name": "LGBT Flag",
        "endless": true,
        "restore": false,
        "preset": "012-lgbt",
        "steps": "[{\"delay\":1000,\"animation\":{\"hex\":\"#e40302\",\"brightness\":100,\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#fc8b02\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#feed02\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#168026\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#054dff\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#750887\",\"transitionTime\":1}}]",
        "x": 370.5,
        "y": 325,
        "wires": [
            [
                "145eb018.42184"
            ]
        ]
    },
    {
        "id": "145eb018.42184",
        "type": "hue-light",
        "z": "e9340415.4862d",
        "name": "Garten Extended color light 2",
        "bridge": "7e6d2135.70b55",
        "lightid": "10",
        "colornamer": true,
        "skipevents": false,
        "x": 616.5,
        "y": 325,
        "wires": [
            []
        ]
    },
    {
        "id": "7e6d2135.70b55",
        "type": "hue-bridge",
        "z": "",
        "name": "Philips hue",
        "bridge": "192.168.1.216",
        "key": "xWDLGSN99dqKtLq-MUzvIf1K5NcZGTRncKlwK7Q8",
        "interval": "500",
        "disableupdates": false
    }
]

**Comment by bergjet** [comment]
`[
    {
        "id": "e9340415.4862d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9e71e69f.4f71d",
        "type": "nighttime",
        "z": "e9340415.4862d",
        "name": "",
        "lon": "23",
        "lat": "15",
        "start": "sunrise",
        "end": "sunsetStart",
        "x": 146.5,
        "y": 322,
        "wires": [
            [
                "eb99bc92.e9093"
            ],
            []
        ]
    },
    {
        "id": "eb99bc92.e9093",
        "type": "hue-magic",
        "z": "e9340415.4862d",
        "name": "LGBT Flag",
        "endless": true,
        "restore": false,
        "preset": "012-lgbt",
        "steps": "[{\"delay\":1000,\"animation\":{\"hex\":\"#e40302\",\"brightness\":100,\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#fc8b02\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#feed02\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#168026\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#054dff\",\"transitionTime\":1}},{\"delay\":1000,\"animation\":{\"hex\":\"#750887\",\"transitionTime\":1}}]",
        "x": 370.5,
        "y": 325,
        "wires": [
            [
                "145eb018.42184"
            ]
        ]
    },
    {
        "id": "145eb018.42184",
        "type": "hue-light",
        "z": "e9340415.4862d",
        "name": "Garten Extended color light 2",
        "bridge": "7e6d2135.70b55",
        "lightid": "10",
        "colornamer": true,
        "skipevents": false,
        "x": 616.5,
        "y": 325,
        "wires": [
            []
        ]
    },
    {
        "id": "7e6d2135.70b55",
        "type": "hue-bridge",
        "z": "",
        "name": "Philips hue",
        "bridge": "192.168.1.216",
        "key": "xWDLGSN99dqKtLq-MUzvIf1K5NcZGTRncKlwK7Q8",
        "interval": "500",
        "disableupdates": false
    }
]`

**Comment by bergjet** [comment]
It's the same with 2.2.6

**Comment by Foddy** [comment]
Thank you! Should be fixed in v2.5.1 +
