### ISSUE TITLE
Support Hue Smart Button

### ISSUE THREAD

**Issue by vbambuch** [Foddy/node-red-contrib-huemagic#123]
Hi, is there a way how to connect [Hue Smart Button](https://www2.meethue.com/en-us/p/hue-smart-button/046677553715) with this project?

If not, would that be possible to add it to the component stack? 🙂

**Comment by dongennl** [comment]
I have the same question! Happy to help develop it, just a bit new to JS.

**Comment by Foddy** [comment]
I started working on it but I couldn’t find any docs for this device. I mean I don’t know what kind of button events there are available for this device and how the bridge addresses them.

Maybe somebody can provide me this information?

**Comment by dongennl** [comment]
Hi @Foddy, thanks.

There's not much documentation, even Philips doesn't have it in their documentation yet.

I did find this thread, which contains the events:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2077 

I don't have one yet, but maybe someone else with one can confirm.

**Comment by Radiotechniman** [comment]
+1 for me too

**Comment by bacongravy** [comment]
I am also curious about this. I looked at the thread linked to by @dongennl and according to [this comment](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2077#issuecomment-554633725) it looks like the Smart Button presents itself as `"type": "ZLLSwitch"`, which also seems to be what the Hue switch node searches for: 
https://github.com/Foddy/node-red-contrib-huemagic/blob/5e65298fa09a42cbc613a6243d04e0b5fba6bc47/huemagic/hue-bridge.js#L152
https://github.com/Foddy/node-red-contrib-huemagic/blob/9a2010e7639cf06ad979103ab924ee2849234e69/huemagic/hue-switch.html#L69
It looks to me like the buttonevents (1000, 1001, 1002, 1003) match up to the events here:
https://github.com/Foddy/node-red-contrib-huemagic/blob/9a2010e7639cf06ad979103ab924ee2849234e69/huemagic/hue-switch.js#L70-L91

So as far as I can tell, the Smart Button should already show up in HueMagic as a Hue Switch that acts like it only has an "On" button. Can anyone confirm? Thanks!

**Comment by dongennl** [comment]
Thanks @bacongravy ; I've just ordered one, as need one anyway; hopefully be able to confirm your findings soon.

**Comment by jimmyeao** [comment]
Looking forwards to this, literally just has a look to see if I could trigger some logic. Sadly, doesn't appear in the Hue Switch List.

**Comment by dongennl** [comment]
Yep, just got mine, It does NOT show up as a Switch or Tap. Do we need to make a new component?

**Comment by jimmyeao** [comment]
It would be great if we could!

**Comment by dongennl** [comment]
I'm very new to all this, but reading the js/html I think we need this info from my bridge to be able to select the Smart Button:

`	"43": {
		"state": {
			"buttonevent": 1003,
			"lastupdated": "2020-08-10T00:04:20"
		},
		"swupdate": {
			"state": "noupdates",
			"lastinstall": "2020-04-17T14:06:01"
		},
		"config": {
			"on": true,
			"battery": 100,
			"reachable": true,
			"pending": []
		},
		"name": "Hue Smart button 1",
		"type": "ZLLSwitch",
		"modelid": "ROM001",
		"manufacturername": "Signify Netherlands B.V.",
		"productname": "Hue Smart button",
		"diversityid": "8b18a40c-eb6a-40d7-a0af-eb0906613d41",
		"swversion": "2.30.0_r30777",
		"uniqueid": "00:17:88:01:06:07:60:0c-01-fc00",
		"capabilities": {
			"certified": true,
			"primary": true,
			"inputs": [
				{
					"repeatintervals": [
						800
					],
					"events": [
						{
							"buttonevent": 1000,
							"eventtype": "initial_press"
						},
						{
							"buttonevent": 1001,
							"eventtype": "repeat"
						},
						{
							"buttonevent": 1002,
							"eventtype": "short_release"
						},
						{
							"buttonevent": 1003,
							"eventtype": "long_release"
						}
					]
				}
			]
		}
	}`

I'm looking at 'hue-switch.html' to see how the selection is done:
I found this line:
`if(sensor.model == "Hue Wireless Dimmer Switch")`

I don't see this value anywhere in the JSON for the Switch, I only see:
`"productname": "Hue dimmer switch"`

So not sure how we change the selection here to make it show buttons instead of switches... 
Anyone knows how this works?

**Comment by dongennl** [comment]
Ok, did some work on this, the "Hue Wireless Dimmer Switch" comes from Huejay, a dependency; it doesn't seem to be maintained.
Created a new mechanism using the bridge JSON to separate the Switches from the Buttons; got it working locally; need to clean up and will do a pull request (I'm new to this!).

Any help testing/reviewing appreciated, my fork is here:
https://github.com/dongennl/node-red-contrib-huemagic

**Comment by jimmyeao** [comment]
Nice, I’ll test it later, thanks for this :)

Jimmy White
________________________________

**Comment by dongennl** [comment]
Just created pull request #191

**Comment by jimmyeao** [comment]
Darn, I run Node-Red in a docker, looks like I'll have to wait for the Pull to be merged first. Everytime I restart Node-Red it just overwrites the package with the original version :/

**Comment by dongennl** [comment]
Oh @jimmyeao it's super-easy on Docker; I use it too; just copy your main node-red container on another port (make sure to map to different volumes if using); now you have a blank node-red install; attach to the container, apt install npm, go into the node-red directory and 'npm install [github URL (not ssh, use https)]'.
You can attach to the same Hue Hub at the same time and test.

**Comment by jimmyeao** [comment]
```
pi@raspberrypi:~ $ npm install git@github.com:dongennl/node-red-contrib-huemagic.git
npm ERR! code ENOLOCAL
npm ERR! Could not install from "github.com:dongennl/node-red-contrib-huemagic.git" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-08-17T11_42_09_047Z-debug.log

```

**Comment by dongennl** [comment]
try
`npm install https://github.com/dongennl/node-red-contrib-huemagic.git`

probably a permission issue; there is a package.json in the root.

**Comment by jimmyeao** [comment]
Got it installed now, can detect long and short presses just fine :)

**Comment by Foddy** [comment]
Thanks you all for contributing and testing! I've just merged the new Hue Button node along with updated docs in v2.8.5+ :)!

**Comment by vbambuch** [comment]
Awesome! Thanks a lot guys. Looking forward to test it out. 😉

**Comment by jimmyeao** [comment]
Hmm, since updating my palette the Hue Button node isn't outputting anything, despite its status text changing

**Comment by dongennl** [comment]
Same for me, I had cloned the Switch Message, but looks like Foddy is already making a fix for 2.8.6 (change to HueButtonMessage).

**Comment by dongennl** [comment]
Just updated to 2.8.6 and works now. Thanks @Foddy

**Comment by jimmyeao** [comment]
Yep, working like a dream, thanks for this @dongennl and @Foddy
