### ISSUE TITLE
Info/topic object to Bridge node output

### ISSUE THREAD

**Issue by johras** [Foddy/node-red-contrib-huemagic#124]
When fetching for ex. lights from the bridge, the output doesn't contain any information from which node the message came. I use two bridges and I need light status from both of them.
As a workaround I use "Change" nodes after the bridge node to add a Topic.

It would be nice if Bridge nodes had an Info object like Light nodes have. Or alternatively a Topic with the Bridge name.

**Comment by Foddy** [comment]
This is possible now with the latest update ;)!
