### ISSUE TITLE
Error: "No group Id defined. Please check the docs." when trying to activate group id 0 (all lights)

### ISSUE THREAD

**Issue by guenter-ms** [Foddy/node-red-contrib-huemagic#125]
Hello,

the above error message comes up, then trying to switch all lights on or off with a group node, when group id is set to 0 in the property.

Group 0 is allowed and accepted by the bridge to adress all lights in a bridge, see attachment.

It is extremly usefull to switch off all lights in a house when leaving home or going to bed, or switch them all on when an alert is detected.

Can you fix?
Regards, Guenni

![Bildschirmfoto 2020-01-08 um 17 51 13](https://user-images.githubusercontent.com/6253315/71998430-eb494f00-323f-11ea-9608-b64a728cfedc.jpg)

**Comment by Foddy** [comment]
Thank you for this note!
It's fixed with v2.2.5
