### ISSUE TITLE
Question: HueMagic Animation selection?

### ISSUE THREAD

**Issue by linkztream** [Foddy/node-red-contrib-huemagic#126]
Should there be a selection list or text box on the HueMagic Node where I can specify which animation to trigger, or do I always need to supply it in the payload as JSON?

![image](https://user-images.githubusercontent.com/3219719/72417698-b2e2cd00-3779-11ea-8b0b-a1c1deaac765.png)

**Comment by Foddy** [comment]
Oh yes! You should be able to see animated previews of each animation there. It looks like some kind of rendering error for me.

Is your used browser connected to the internet and what kind of browser & version are you using? It would also be very helpful if you could share a screenshot of the browser console’s error section here

**Comment by linkztream** [comment]
Interesting. Should I also be able to click and select on the animations there as well? I don't believe the issue is in your code, but rather some aggressive filtering in my firewall. I'll start my troubleshooting there and let you know what I come up with and console errors if the firewall is innocent.

Thanks for the reply

**Comment by linkztream** [comment]
Solved!

Issue was that the spam/abuse blacklist had decided that githubusercontent.com domain was malicious and needed to be blocked completely. Just unblocking it didn't help, I needed to remove and re-install the node to pull the images and extras again.

![image](https://user-images.githubusercontent.com/3219719/72423939-71581f00-3785-11ea-9c89-8f370f006d74.png)

**Comment by Foddy** [comment]
Thanks for this note! External dependencies are now included locally, so this should not happen any longer from v2.2.5+!
