### ISSUE TITLE
incrementBrightness - only for lights which are turned on

### ISSUE THREAD

**Issue by MaStahl84** [Foddy/node-red-contrib-huemagic#128]
Hello, 
first, great work!

Is there a possibility to add a second "incrementBrightness"-command for light groups that will only change the brightness of lights, which are turned on?

This would be a nice enhancement to control different light-scenes.

**Comment by Foddy** [comment]
Try to pass the new "ignoreOffLights" parameter in your payload to ignore turned off lights in a group. This should be possible now! :)

**Comment by MaStahl84** [comment]
Parameter works perferct, thanks
