### ISSUE TITLE
Universal Mode

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#13]
Foddy, just got round to putting this together with my flow and although I send in various light ids the net result is always that light "1" is controlled. I made a slight mod to the node result text and added in the light ID and that always shows "1" (obviously).

**Comment by lespatots** [comment]
Just did some more playing with this and what actually happens is that after the node in initialised and shows 'universal mode', the first external topic gets locked into the node so that whatever topic is sent is then ignored after the first command. So I can set any light (not just '1') but only do it once.

**Comment by Foddy** [comment]
Hmm, with this additional information I guess I’ve found the error. 

I’ll fix this today and let you know when it’s online. Sorry again for all these updates in this short time...

**Comment by lespatots** [comment]
Foddy,

That’s just great and your software and its documentation is just great too. I only try to report real issues and my motivation is often to help other avoid problems. I can’t see that being the case for Huemagic except that I do believe it’s going to come in for a lot of use.

Richard

**Comment by Foddy** [comment]
Fixed with v1.2.3

**Comment by lespatots** [comment]
Foddy,

Just tested it and it seems to be fixed. Must do a lot more playing to insert it into my flow and catch the light states back to the database!

Thanks

Richard

**Comment by lespatots** [comment]
Foddy,

Must be getting a bit fed up of me, here is what I’ve found

1) Setting ‘on’ to false has no effect the only action seems to be on (extended mode)
2) It would be good to add in some more range checking. Brightness values greater than 100 produce a library error?
   "Error: Philips Hue: 7, invalid value, 508,, for parameter, bri”

3) Brightness 0 isn’t off (I think that’s a Hue bridge limitation) but IMHO I think zero should be off also if you use 0 to 100 rather than 0 to 254 then the possible range of brightness levels is reduced?

4) ct is fine using megakelvin !!! but weird IMHO but what about saturation etc?

5) I wonder whether the excellent info might be improved a bit to explain whether commands are additive. So if I send ‘on' without colour and follow up with a colour setting without ‘on’ what is the result?

6) Would it be better to match the parameter names to the Philips ones (even if they are cryptic)?
