### ISSUE TITLE
Update breaks flows on Hue Light nodes

### ISSUE THREAD

**Issue by antil697** [Foddy/node-red-contrib-huemagic#130]
Sending payload with {"on":true,"brightness":40} and the node will respond with 

> Error: Philips Hue: 7, invalid value, null}, for parameter, transitiontime

but the light will eventually turn on.

Sending payload { "on": false } and the node responds the same and shows "input error" as status message but won't turn off. This is breaking all my flows, will have to find a way to downgrade the module now. 

Example flow:
`[{"id":"9e469436.8de8d8","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"98c34b71.f64708","type":"inject","z":"9e469436.8de8d8","name":"On","topic":"","payload":"{\"on\":true,\"brightness\":40}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":180,"wires":[["9e1a6a80.13b948"]]},{"id":"d48674bc.ee5428","type":"inject","z":"9e469436.8de8d8","name":"Off","topic":"","payload":"{\"on\":false}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":280,"wires":[["9e1a6a80.13b948"]]},{"id":"9e1a6a80.13b948","type":"hue-light","z":"9e469436.8de8d8","name":"Living room light","bridge":"e40afd93.0072a","lightid":"2","colornamer":true,"skipevents":false,"x":520,"y":240,"wires":[["2f97727f.2417ee"]]},{"id":"2f97727f.2417ee","type":"debug","z":"9e469436.8de8d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":730,"y":240,"wires":[]}]`

Adding tranitionTime to the ON message clears the error but for the OFF message it will clear the error message but the node will not turn off the light even when setting "on": false or "brightness": 0 with transitionTIme set to any value. 

**Please complete the following information:**
 - NodeRED version: latest docker image v1.0.3
 - NodeJS version: based on latest docker image
 - Device running NodeRED: rpi4

**Comment by Foddy** [comment]
Thank you. This should be fixed with v2.5.2. Let me know if you still face this issue.

**Comment by antil697** [comment]
Confirmed closure. Appreciate your work.
