### ISSUE TITLE
i'm new and i need help with installing

### ISSUE THREAD

**Issue by wolfhond** [Foddy/node-red-contrib-huemagic#132]
Hello

I'm new on home assistant.
I will install Hue Magic on home assistant. I have add the Repositories "https://github.com/Foddy/node-red-contrib-huemagic "
He add something unknown with the link.
But it doesn't work. Do I something wrong? Can anybody help me:

Thanks

"
20-01-19 14:37:26 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-01-19 14:37:26 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/Foddy/node-red-contrib-huemagic repository
20-01-19 14:37:26 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-01-19 14:37:33 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/a37c9651/repository.json: [Errno 2] No such file or directory: '/data/addons/git/a37c9651/repository.json'
20-01-19 14:37:33 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/a37c9651/repository.json
20-01-19 14:37:33 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 0 new - 0 remove
"

**Comment by ryanjohnsontv** [comment]
The easiest way to install would be directly inside of Node Red. Home Assistant will not directly use Hue Magic, however you can set up automations that can be triggered with Home Assistant entities. I recommend, asuming you're using Hass.io, add the Node Red add-on and then inside of Node Red add the Home Assistant (https://github.com/zachowj/node-red-contrib-home-assistant-websocket) palette,  and then this palette.
