### ISSUE TITLE
Dimmer switch - Multiple presses

### ISSUE THREAD

**Issue by rjmcfadd** [Foddy/node-red-contrib-huemagic#133]
Is it possible to program the dimmer switch to respond to multiple presses of a certain button? For example, If I press the on button 3 times within 10 seconds.

**Comment by bertlorenz** [comment]
have you had a look to the _join_ node? (part of node-red core)
haven't used this one so far, but sounds promissing to me.

**Comment by Foddy** [comment]
The node will now respond every time when a button has been pressed on the switch in the latest update
