### ISSUE TITLE
Brightness Settings do not elaborate the full potential

### ISSUE THREAD

**Issue by bertlorenz** [Foddy/node-red-contrib-huemagic#134]
Hi there,

within the huemagic nodes, brightness settings are implemented as percentages, so that only 0 - 100 % is allowed.
On the one hand, this is gives a good visibility of the brightness level, but on the other hand it does not elaborate the full potential of hue, where you have the possibility to select a level between 0 - 254.

Of course, most of use would not see a difference between single levels, so that 0-100 would generally be sufficient, but it can lead to difficulties when working on a very low level.
For example the nightlight scene of hue is working with a brightness level of 1. Due to the calculations, the node is not giving back the level 1 but the level 0, so that visualizations of the brightness settings would show that the light is off, even though it's on.

The huejay adapter supports the correct settings.
Is there any reason for the limitation in huemagic? any plans to change that?

thanks, Bert

**Comment by Foddy** [comment]
Thank you for this suggestion! There is a new option "brightnessLevel" available now so you can adjust brightness more accurate on Groups and Lights.
