### ISSUE TITLE
 Connection error

### ISSUE THREAD

**Issue by oehm2007** [Foddy/node-red-contrib-huemagic#14]
Hi,
my motion sensors and obviously all the other hue nodes are loosing connection all the time. Actually everything is working fine, but after some time the hue motion sensors just don`t interact with motion any more. When I`m havin a look in node-red all the nodes are havin a connection error, until I`m deploying again all my nodes.
If I´m checking the motion sensors in the hue app, I cannot see any abnormal behaviour. 
My system is uptodate, so I`m using the latest software versions on my raspberry pi 3.
Maybe you have any suggestions, why I get the connection errors all the time.
Thanks for your help in advance.

**Comment by lespatots** [comment]
Yes,
I am having the same issue and I am on Pi3 too with most up to date software.

**Comment by oehm2007** [comment]
Looks like I could solve the problem. I had the suspicion, that there might be an issue with a bad connection of the hue bridge in my wifi. So I watched the behave of node red while cutting off the wifi connection of my raspberry. Understandably the nodes will have an connection error. But when the connection is back again, all of the nodes besides the huemagic nodes found the connection again. The huemagic nodes (especially the motion nodes) keep staying in the connection error, till I'm deploying again. The normal group, scene and lamp nodes find the connection again, after I toggled them physically.
So actually there is an issue with huemagic. The connection must be refreshed after a certain time after loosing the connection to the wifi. Maybe you can improve that.

**Comment by lespatots** [comment]
I think it is premature to close this. If this is the problem then it needs a fix. This explanation is reasonable as I did see my Pi roam between two access points but this should be a seamless transition? I just moved my Pi and roaming should cease as the Pi is now just 1M from the AP.

**Comment by oehm2007** [comment]
Yes you`re right sorry. Reopened it. Maybe Foddy gives a feedback, if its possible to fix.

**Comment by Foddy** [comment]
Hi. Thanks for figuring out what causes the problem. I will fix this soon and let you guys know here when there is a fixed version available.

**Comment by oehm2007** [comment]
Thanks for your feedback; In addiion to my explanation, it is possible, that the wifi power saving of the PI is causing the problem as well.

**Comment by Foddy** [comment]
Okay I just released a "fix" with v1.2.1. Now the nodes should automatically try to reconnect if the connection lost before. Please open a new issue if you still get connection errors.

**Comment by oehm2007** [comment]
You`re just fantastic. I updated the module and it looks like you did a perfect job. Everything works fine without connection errors. 
Thanks very much for all your efforts, I really appreciate your great support.

**Comment by Cheddaru** [comment]
Hi. I am having this same issue (I guess). "Hue Light" can handle 1 payload.msg before it reports

> "Error: Philips Hue: 3, resource, /lights/NaN, not available"

"Hue Group" also works fine the first time, but subsequent messages change the id to 0

After first inject:
>{"id":2,"lightIds":"3, 4","name":"Hallway","type":"Room"}

After subsequent injects:
> {"id":0,"lightIds":"1, 2, 3, 4, 5, 6, 7","name":"Group 0","type":"LightGroup"}

On both cases I am injecting a payload with only a boolean value.
> {"_msgid":"486dee22.8b5fb","topic":"","payload":false}

Running on rpi1 with Node-red v0.17.5 and node v6.12.1
