### ISSUE TITLE
2.5.5 Hue Magic  node hangs webpage

### ISSUE THREAD

**Issue by townsmcp** [Foddy/node-red-contrib-huemagic#140]
**Describe the bug**
I add a Hue Magic node to a flow, double click the node to open and the whole webpage freezes - cant see Hue Magic properties

**Flow to Reproduce**
Every flow - drag node from pallet

**Expected behavior**
Node properties window to open

**Please complete the following information:**
 - NodeRED version: 6.0.3
 - NodeJS version: unknown  Hassio install
 - Device running NodeRED:  RPI 4B 4gb

**Additional context**

**Comment by Foddy** [comment]
Which browser and version do you use?

**Comment by townsmcp** [comment]
Ive tried Safari on ipad and iphone (both using ios 13.3.1) and Chrome version 79.0.3945.130 (Official Build) (64-bit)

**Comment by Foddy** [comment]
Can you please try it again with the newest version?

I am working on a more powerful solution for rendering animations. Unfortunately, it currently depends a bit on which device / browser Node-RED is running on.

**Comment by townsmcp** [comment]
Just upgraded HueMagic to 2.6.1. Tried both the browsers above and still getting the same issue - web page crashing when bringing up the properties for this node type. Not a problem to me as I havent used this node type before and havent got it used in any flows but thought i should report it

**Comment by antil697** [comment]
Still an issue on 2.6.5. Just used the node for the first time and it will take about 40 seconds before the node config screen shows and the tab unfreezes.

**Comment by Foddy** [comment]
Should be fixed in the latest release
