### ISSUE TITLE
Cant get decrementBrightness to work

### ISSUE THREAD

**Issue by AndersNorlev** [Foddy/node-red-contrib-huemagic#141]
I cant get decrementBrightness to work.
But incrementBrightness works fine..

![image](https://user-images.githubusercontent.com/60581646/73613670-51838080-45f8-11ea-9296-a4bc8e2a47b7.png)

**Comment by hobbyquaker** [comment]
there is no `decrementBrightness`. Just use `incrementBrightness` with a negative value.

**Comment by Foddy** [comment]
To avoid confusion, "decrementBrightness" is now available for both Hue group and Hue Light nodes :)!
