### ISSUE TITLE
Sorry. Your selected Hue Bridge is invalid [object: Object]

### ISSUE THREAD

**Issue by GHBLoos** [Foddy/node-red-contrib-huemagic#143]
**Describe the bug**
Heads Up Message:
_"The Hue bridge I created in Node  Red is no longer available (connecting...). "_

Debug:
_3-2-2020 17:43:17node: Node red bridge
msg : error
"Error: Huejay: Request failed with status code 404"_

**Expected behavior**
Hue bridge should be connecting/should be found.

**Please complete the following information:**
 - NodeRED version: v1..0.3
 - NodeJS version: v10.18.1
 - Device running NodeRED: Raspberry Pi 3

**Additional context**
I have two Hue bridges on my network. One is a Philips Hue Bridge, and the other one is a diyHue bridge which is running on the same RPi. Both are working when using an app on PC or phone.

It did work very well, until for some reason there is no longer a connection. There seem to be a 404 error. I restarted Node Red, reinstalled huemagic, rebooted the RPi, but it doesn't seem to make a difference. 

When searching for bridges only one appears (the Philips Hue Bridge)

**Summary:**
The diyHue bridge is working
It has been working together with Node Red / Huemagic
It is still visible in the flow, but cannot connect anymore
The diyHue bridge is not found, the Philips bridge is
Both Node Red and diyHue are on the same RPi

**Comment by GHBLoos** [comment]
I'm still not quite sure what the problem is, but might have something to do with https/port 443. Debugging diyHue showed an error on this port. I closed apache2, the other service using this port, and I can now connect to the bridge.

**Comment by mastix** [comment]
I have the same error message... since a couple of days. Didn't change anything - it just stopped working. Have a standard Philips hue bridge 2.

The error message in the node red debug says:

> "Error: Huejay: Request failed with status code 404"

When editing the settings I get the error message:

> Sorry. Your selected Hue Bridge is invalid [object: Object]

Sascha

**Comment by Foddy** [comment]
Should not happen again with the latest version :)
