### ISSUE TITLE
No event sent on hue motion deactivate

### ISSUE THREAD

**Issue by My-userid** [Foddy/node-red-contrib-huemagic#145]
**Describe the bug**
When I use the Hue app to deactivate the hue motion sensor, the hue motion node registers the sensor as deactivated but it does not send and event.

**Flow to Reproduce**
```
[{"id":"a7f2241a.daba08","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"a9a0ecc3.b9668","type":"hue-motion","z":"a7f2241a.daba08","name":"Hue motion sensor - Bryggers","bridge":"6193920.213787","sensorid":"20","skipevents":false,"x":404,"y":119,"wires":[["a04d315c.9fafd"]]},{"id":"a04d315c.9fafd","type":"debug","z":"a7f2241a.daba08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":625,"y":118,"wires":[]},{"id":"6193920.213787","type":"hue-bridge","z":"","name":"Philips hue bridge","bridge":"192.168.1.15","key":"aijMXQ3nMktrwk-jkCpjldzRubPt63RhvQIlzOXp","interval":"3000","disableupdates":false}]
```

**Expected behavior**
I would expect to see an output on the output node when the sensor is deactivated, so I can trigger a flow when the sensor is deactivated.

**Please complete the following information:**
 - Node-RED version: v1.0.3
 - NodeJS version: v10.18.0
 - Device running NodeRED: docker on synology DS918+

**Comment by Foddy** [comment]
I could not replicate this issue. Can you please post your flow?
