### ISSUE TITLE
"TypeError: Expected a valid hex string" - Hue Lightstrip Set To Random For Colour

### ISSUE THREAD

**Issue by townsmcp** [Foddy/node-red-contrib-huemagic#146]
**Describe the bug**
Hue lightstrip has a Change Node with the following JSON feeding into the Hue Light node:

> {
>     "on": true,
>     "brightness": 100,
>     "color": "random",
>     "transitionTime": 0.3
> }

If I remove "color": "random" from the JSON, the light works correctly every time. If I set a specific colour name, the light works correctly every time.

Randomly, the lightstrip won't turn on with "Random" set and instead I get the following error in debug:

> 10/02/2020, 15:41:37node: Kitchen Plinth
> msg : error
> "TypeError: Expected a valid hex string"

**Flow to Reproduce**
`[{"id":"d3302983.27d55","type":"change","z":"be4bcc0c.52ef8","name":"Motion","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"on\":true,\"brightness\":100,\"color\":\"random\",\"transitionTime\":0.3}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":1600,"y":140,"wires":[["b702960d.f1bd08"]]},{"id":"b702960d.f1bd08","type":"hue-light","z":"be4bcc0c.52ef8","name":"Kitchen Plinth","bridge":"e81e9b.75df5168","lightid":"31","colornamer":true,"skipevents":false,"x":1800,"y":140,"wires":[["256c4eec.d552e2"]]},{"id":"e81e9b.75df5168","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.1.5","key":"bzebqVHBEwYSOrxKTGL1Rk2rdHI3O3r3hsatCvJF","interval":"500","disableupdates":false}]`

**Expected behavior**
When triggered, the lightstrip should turn on with a random colour.

**Please complete the following information:**
 - NodeRED version: 6.0.4 (in HassIO 0.105.2 however this was the same on previous versions on HassIO).
 - NodeJS version: HassIO 0.105.2, not sure what the NodeJS version is for that.
 - Device running NodeRED: HassIO, running in a VMWare Workstation 15.5.1 session. Also same behaviour on an RPI4 4Gb
- HueMagic version: 2.6.1, issue also occurred on previous versions.

**Additional context**
The lightstrip (plinth) is set to random colour, however a worktop lightstrip with the following JSON is also always triggered at the same time however that lightstrip always comes on:

> {
>     "on": true,
>     "brightness": 100,
>     "rgb": [
>         255,
>         232,
>         179
>     ],
>     "transitionTime": 0.3
> }
>

**Comment by townsmcp** [comment]
@Foddy any update with this?

**Comment by Foddy** [comment]
> @Foddy any update with this?

Hi, can you please try it with the value “any” and tell me if this worked for you?

**Comment by townsmcp** [comment]
> > @Foddy any update with this?
> 
> Hi, can you please try it with the value “any” and tell me if this worked for you?

Thanks @Foddy. I just did 10 tests and each time the lights came on as expected (random colour each time). Happy to close this ticket and reopen a new one if the issue comes back.

**Comment by Foddy** [comment]
Hi townsmcp, I'm glad that it worked out now :)!
– but you were right – it should also work with the value "random". I will take a close look at this these days…

**Comment by tundratier** [comment]
The issue still occurs with "any" or "random" values and should be reopened
