### ISSUE TITLE
Hue Scene is not working

### ISSUE THREAD

**Issue by bergjet** [Foddy/node-red-contrib-huemagic#147]
Group is turned on/off, but the scene is not set.
V2.6.1

**Comment by amnacog** [comment]
To add to this issue, when transmitting manually the scene/group from the input payload, the scene is being compared to *msg.payload* instead of *msg.payload.scene*
```javascript
else if (typeof msg.payload != 'undefined' && typeof msg.payload.scene != 'undefined')
{
    bridge.client.scenes.getAll()
    .then(scenes => {
        for (var scene of scenes)
        {
            if (scene.name === msg.payload || scene.id === msg.payload)
            {
                scope.proceedSceneAction(scene, groupID, send, done);
                break;
            }
        }
    });
}
```
https://github.com/Foddy/node-red-contrib-huemagic/blob/master/huemagic/hue-scene.js#L51-L58

**Comment by xcorp** [comment]
This affects me as well.
Group turns on, but to the last state and not to the scene selected.

Example flow:
`[{"id":"6ee38b11.eabfbc","type":"tab","label":"debug flow","disabled":false,"info":""},{"id":"91b68abf.c67f3","type":"hue-scene","z":"6ee38b11.eabfbc","name":"Kitchen","bridge":"53fb19d6.8b3ad","sceneid":"vinAejhcSJ-NLFw","groupid":"3","skipevents":false,"x":910,"y":340,"wires":[[]]},{"id":"d4ca24b.6d7ffd8","type":"inject","z":"6ee38b11.eabfbc","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":610,"y":360,"wires":[["91b68abf.c67f3"]]},{"id":"53fb19d6.8b3ad","type":"hue-bridge","name":"Philips hue","bridge":"10.0.0.76","key":"<MASKED KEY>","interval":"500","disableupdates":false}]`

**Comment by Foddy** [comment]
Should be fixed in the latest update :)
