### ISSUE TITLE
Repeated error message "UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded"

### ISSUE THREAD

**Issue by djiwondee** [Foddy/node-red-contrib-huemagic#148]
Even all seems to work, I see a couple of the same error message in my log related to the `node-red-contrib-humagic`. 

```
Feb 12 15:43:07 raspi-smarthome daemon.err node-red: (node:18121) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
Feb 12 15:43:07 raspi-smarthome daemon.err node-red:     at getHttpClient.request.then.catch.error (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15)
Feb 12 15:43:07 raspi-smarthome daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:68:7)
Feb 12 15:43:07 raspi-smarthome daemon.err node-red: (node:18121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
F
```
**Flow to Reproduce**
```
[
    {
        "id": "232ebd58.c158fa",
        "type": "hue-light",
        "z": "1592b621.21a732",
        "name": "Shelf Light",
        "bridge": "b461e4d7.4e0da",
        "lightid": "15",
        "colornamer": false,
        "x": 990,
        "y": 180,
        "wires": [
            [
                "eb0bada7.2d066"
            ]
        ]
    },
    {
        "id": "ef6ee55.f5f5798",
        "type": "change",
        "z": "1592b621.21a732",
        "name": "Set payload to Hue Msg",
        "rules": [
            {
                "t": "move",
                "p": "payload.On",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            },
            {
                "t": "delete",
                "p": "payload.On",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "payload.Toggle",
                "pt": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 750,
        "y": 180,
        "wires": [
            [
                "232ebd58.c158fa"
            ]
        ]
    },
    {
        "id": "eb0bada7.2d066",
        "type": "switch",
        "z": "1592b621.21a732",
        "name": "",
        "property": "payload.on",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 1150,
        "y": 180,
        "wires": [
            [
                "aad34f42.71b058"
            ],
            [
                "2db18103.d7717e"
            ]
        ]
    },
    {
        "id": "2db18103.d7717e",
        "type": "change",
        "z": "1592b621.21a732",
        "name": "Set HKMsg Status Off",
        "rules": [
            {
                "t": "delete",
                "p": "payload",
                "pt": "msg"
            },
            {
                "t": "set",
                "p": "payload.On",
                "pt": "msg",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1340,
        "y": 240,
        "wires": [
            [
                "1111149e.b9c7b3"
            ]
        ]
    },
    {
        "id": "aad34f42.71b058",
        "type": "change",
        "z": "1592b621.21a732",
        "name": "Set HKMsg Status On",
        "rules": [
            {
                "t": "delete",
                "p": "payload",
                "pt": "msg"
            },
            {
                "t": "set",
                "p": "payload.On",
                "pt": "msg",
                "to": "true",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1340,
        "y": 120,
        "wires": [
            [
                "1111149e.b9c7b3"
            ]
        ]
    },
    {
        "id": "b461e4d7.4e0da",
        "type": "hue-bridge",
        "z": "",
        "name": "Philips hue II",
        "bridge": {{MY_BRIDGE_IP}},
        "key": {{MY_BRIDGE_KEY}},
        "interval": "3000"
    }
]
```

**Expected behavior**
The error repeated several times a day independent of user interaction on the Dashboard or triggered by an injection of a payload. So Im interested in the root cause and how to prevent this.

 - NodeRED version: 1.03
 - NodeJS version: 10.18.1
 - Device running NodeRED: RaspberryPi

Thanks in advance!

**Comment by 123dabei** [comment]
I habe the same problem

`

node-red.0 | 2020-04-27 23:18:58.304 | error | (17499) Error: Huejay: timeout of 15000ms exceeded     at getHttpClient.request.then.catch.error (/opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15)     at process._tick
-- | -- | -- | --
node-red.0 | 2020-04-27 23:18:58.303 | error | (17499) uncaught exception: Huejay: timeout of 15000ms exceeded
node-red.0 | 2020-04-27 23:18:58.302 | error | (17499) Error: Huejay: timeout of 15000ms exceeded     at getHttpClient.request.then.catch.error (/opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15)     at process._tick
node-red.0 | 2020-04-27 23:18:58.302 | error | (17499) uncaught exception: Huejay: timeout of 15000ms exceeded
node-red.0 | 2020-04-27 23:18:58.297 | error | (17499) Error: Huejay: timeout of 15000ms exceeded     at getHttpClient.request.then.catch.error (/opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15)     at process._tick
node-red.0 | 2020-04-27 23:18:58.294 | error | (17499) uncaught exception: Huejay: timeout of 15000ms exceeded

`

**Comment by ecdlguy** [comment]
Same problem here:

```
(node:23) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded,
    at getHttpClient.request.then.catch.error (/data/node_modules/huejay/lib/Transport.js:106:15),
    at process._tickCallback (internal/process/next_tick.js:68:7),
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 151)
```

**Comment by Travelbacon** [comment]
Same as: 
#106

**Comment by cedcox** [comment]
Hello,

Same problem for me. Is there a solution found or a workaround ?

`Sep 27 09:28:46 rasp-test Node-RED[19691]: (node:19691) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Sep 27 09:28:46 rasp-test Node-RED[19691]:     at ServerResponse.setHeader (_http_outgoing.js:470:11)
Sep 27 09:28:46 rasp-test Node-RED[19691]:     at ServerResponse.header (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:771:10)
Sep 27 09:28:46 rasp-test Node-RED[19691]:     at ServerResponse.send (/usr/lib/node_modules/node-red/node_modules/express/lib/response.js:170:12)
Sep 27 09:28:46 rasp-test Node-RED[19691]:     at client.lights.getAll.then.catch.error (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js:374:18)
Sep 27 09:28:46 rasp-test Node-RED[19691]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Sep 27 09:28:46 rasp-test Node-RED[19691]: (node:19691) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
`

Thanks

**Comment by cchrisx31** [comment]
Most probably the IP of the Bridge has changed and node-red cannot find it with the current configuration.
Add a new configuration and delete the old.
Set a static IP address for the bridge so it doesn't happen again.

**Comment by djiwondee** [comment]
@cchrisx31 
> Set a static IP address for the bridge so it doesn't happen again.

You may probably right with that but I wonder about a little it. In the past I've configured the DHCP of my router to provide always the same IP to the HUE bridge. 3 weeks ago I've changed the IP of the HUE bridge for some other reasons to a real fix IP not covered by the permitted assignable DHCP range of my router. I just checked the logs of today

```
Jun  9 11:12:53 {{HOST}} node-red: (node:9037) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
Jun  9 11:12:53 {{HOST}} node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15
Jun  9 11:12:53 {{HOST}} node-red:     at runMicrotasks (<anonymous>)
Jun  9 11:12:53 {{HOST}} node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Jun  9 11:12:53 {{HOST}} node-red: (node:9037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 485)
```

as you can see, the problem is still there. In addition to that the [error msg](https://github.com/Foddy/node-red-contrib-huemagic/issues/148#issuecomment-699604760) of @cedcox looks different than mine.

**Comment by cchrisx31** [comment]
> @cchrisx31
> 
> > Set a static IP address for the bridge so it doesn't happen again.
> 
> You may probably right with that but I wonder about a little it. In the past I've configured the DHCP of my router to provide always the same IP to the HUE bridge. 3 weeks ago I've changed the IP of the HUE bridge for some other reasons to a real fix IP not covered by the permitted assignable DHCP range of my router. I just checked the logs of today
> 
> ```
> Jun  9 11:12:53 {{HOST}} node-red: (node:9037) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
> Jun  9 11:12:53 {{HOST}} node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15
> Jun  9 11:12:53 {{HOST}} node-red:     at runMicrotasks (<anonymous>)
> Jun  9 11:12:53 {{HOST}} node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Jun  9 11:12:53 {{HOST}} node-red: (node:9037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 485)
> ```
> 
> as you can see, the problem is still there. In addition to that the [error msg](https://github.com/Foddy/node-red-contrib-huemagic/issues/148#issuecomment-699604760) of @cedcox looks different than mine.

The main cause should still be that node-red cannot find the Bridge and it times out. 
Try to reset the configuration again and see what happens.
I had the same issue.
to make it work I had to remove all huemagic nodes, remove node-red-contrib-huemagic, re-install it and re-add the nodes with a new configuration.
If you have a lot of hueagic nodes, you can export your flows, delete all and after the above process re-import them in node-red.

**Comment by Schmetterfliege** [comment]
Hi,

I have the same issues unfortunately, but I guess worse.

```
2021-11-19 21:58:45.456 - error: node-red.0 (23541) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2021-11-19 21:58:45.493 - error: node-red.0 (23541) unhandled promise rejection: Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:45.495 - error: node-red.0 (23541) Error: Huejay: timeout of 15000ms exceeded
at /opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at runNextTicks (internal/process/task_queues.js:66:3)
at listOnTimeout (internal/timers.js:523:9)
at processTimers (internal/timers.js:497:7)
2021-11-19 21:58:45.496 - error: node-red.0 (23541) Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:45.502 - error: node-red.0 (23541) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-11-19 21:58:45.504 - error: node-red.0 (23541) unhandled promise rejection: Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:45.505 - error: node-red.0 (23541) Error: Huejay: timeout of 15000ms exceeded
at /opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at runNextTicks (internal/process/task_queues.js:66:3)
at listOnTimeout (internal/timers.js:523:9)
at processTimers (internal/timers.js:497:7)
2021-11-19 21:58:45.506 - error: node-red.0 (23541) Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:45.509 - error: node-red.0 (23541) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-11-19 21:58:45.510 - error: node-red.0 (23541) unhandled promise rejection: Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:45.512 - error: node-red.0 (23541) Error: Huejay: timeout of 15000ms exceeded
at /opt/iobroker/iobroker-data/node-red/node_modules/huejay/lib/Transport.js:106:15
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-11-19 21:58:45.513 - error: node-red.0 (23541) Huejay: timeout of 15000ms exceeded
2021-11-19 21:58:46.021 - info: node-red.0 (23541) terminating
2021-11-19 21:58:46.022 - warn: node-red.0 (23541) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-11-19 21:58:46.625 - info: node-red.0 (20712) node-red exited with 6
2021-11-19 21:58:51.626 - info: node-red.0 (20712) Starting node-red: --max-old-space-size=512 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js
```
As you can see in those logs messages, it's not just throwing those errors but also killing my node-red adapter forcing a restart.
Node-Red runs via my iobroker, huemagic is added to node-red directly.
At first I thought this was because next to huemagic also the hue-extended adapter from iobroker was communicating with the hue bridge. But I disabled this adapter, and still the error happens sometimes.
When I still had that and accidentally created some loops in node red I could trigger this actively.
But the hue adapter is disabled and in node-red I would say all loops are fixed.
My bridge has a fixed IP address, so this isn't the issue.

Is there a way to increase the timeout from 15 seconds to idk 30, or even 60?
Could we add some kind of debug logging to see which action is triggering the timeout? Maybe one of my flows is causing this still...
The debug node in node-red is obviously no help since node-red itself crashes due to it

**Comment by Schmetterfliege** [comment]
Seeing that this project hasn't seen an update in 14 months, I assume the Dev is no longer interested in it / supporting it.

Would anybody be capable of fixing the error handling - or has a good alternative solution to use in NR?
This is crashing my NR 3 times a day, completely random.... besides that it's working perfectly fine, but obviously this isn't very useable like that :(

**Comment by Travelbacon** [comment]
Oh oh. Indeed. 14 months was the last commit. I hope the owner has time to continue or somebody else can take over. Besides this bug, Hue has announced new API.

**Comment by djiwondee** [comment]
From my perspective this issue can be closed. 

I understood Huejay isn't longer part of Huemagic 4.x. 

First tests on my setup with the 4.0.3 release haven't shown the behavior at all. 

Thanks for the work on rewrite this nrchk.

**Comment by Schmetterfliege** [comment]
I just jumped through the patch notes - looks good!
Will test it out in a bit.

This makes me so happy that it hurts :D.
