### ISSUE TITLE
Hue Light node outputs twice

### ISSUE THREAD

**Issue by Andreyooo** [Foddy/node-red-contrib-huemagic#150]
Hello,
when I send a value to my hue light node, it sends light state output twice with 3-4 seconds delay between.
Is that normal behaviour?
I´d like it to only output once. I used debug nodes to confirm I only send input once.

**Comment by Andreyooo** [comment]
Is there a way to solve this?

**Comment by Foddy** [comment]
Thank you for your notice. It should be fixed with v2.6.2 :)!

**Comment by Andreyooo** [comment]
Hey, thanks for the update.
The light node does output twice occasionly now. 
What's strange when that happens, is that the first output has some random brightness value, The second output has the correct value. 
It doesn't matter wether it's changing color, powering on or changing the brightness.
