### ISSUE TITLE
Enable/disable schedule on hue bridge

### ISSUE THREAD

**Issue by Harpau** [Foddy/node-red-contrib-huemagic#151]
I have a schedule named "TV mimicking" stored on my hue bridge and would like to enable/disable it using HueMagic

**Comment by Foddy** [comment]
Please check out the docs: https://github.com/Foddy/node-red-contrib-huemagic#enable--disable-rule
You can enable or disable schedules / rules by simply passing a `true / false` boolean on the affected schedule node.

**Comment by Harpau** [comment]
Thank you for your reply! Unfortunately the way described in this document does not work for enabling a formula loaded from Hue Labs: 
https://www.dropbox.com/s/80or4l7095iz50p/IMG_2763.png?dl=0
Is it possible to enable or disable such a formula?

**Comment by Foddy** [comment]
Oh sorry... it seems that this kind of formulas directly from Hue Labs are getting stored in „Ressource links“.

There is no node for that in Hue Magic at this time but I’ll mark this issue as an enhancement.

In the meantime you could take a look at the „HueMagic“ Animations node. You can also create your own animation for that pretty easily and fire it up via HueMagic. The fire animation in the animations folder of the repo could help you out with that.
