### ISSUE TITLE
Hue bridge "not configured"

### ISSUE THREAD

**Issue by roybosch** [Foddy/node-red-contrib-huemagic#152]
**Describe the bug**
I've been using these nodes for a long time now. Since a few days I get a "not configured" message at the bottom of the Hue bridge node and the motion sensor node (maybe more nodes have this, didn't try them all). I tried to delete the configuration of the hue bridge and make a new one. Searching for a bridge works, and after selecting it also generating an API key works without problems. But after saving the config and publishing the node, it still says "not configured". 

**Flow to Reproduce**
```
[{"id":"13adca38.15f556","type":"hue-bridge-node","z":"444774fd.bb442c","name":"Hue Bridge","bridge":"27cac910.b087a6","autoupdates":true,"skipglobalevents":false,"x":2130,"y":1840,"wires":[[]]},{"id":"27cac910.b087a6","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.178.10","key":"<deleted key>","interval":"3000","disableupdates":false}]
```

**Expected behavior**
I expect working nodes after configuring the hue bridge node.

**Screenshots**
![image](https://user-images.githubusercontent.com/45666392/77148538-08946800-6a90-11ea-869c-a37d15bec682.png)

![image](https://user-images.githubusercontent.com/45666392/77148595-23ff7300-6a90-11ea-9029-2688979bd939.png)

**Please complete the following information:**
 - NodeRED version: v1.0.4
 - NodeJS version: I don't know where to find it.
 - Device running NodeRED: Home Assistant NodeRED addon on Intel NUC Virtualbox VM.

**Additional context**
No additional context.

**Comment by Foddy** [comment]
Fixed in the latest version
