### ISSUE TITLE
Repeated but identical before / after events on updating group

### ISSUE THREAD

**Issue by SimonB27P** [Foddy/node-red-contrib-huemagic#153]
HueMagic is great work - I've just donated but I have come across an issue.

If I update the brightness of a group using incrementBrightness, the node sends two messages, one with the brightness at the old level and one at the new level.  I use these messages for feedback with my OpenHab automation system so that I can control dimming and colour temperature from (non-Hue) wall switches but I only want the new level; the old level will confuse things.

With an earlier version of HueMagic, I was able to tell which message was which because for some reason, the "after" message did not have the "class" attribute, while the "before" message did so I could test for this and only use messages without a class attribute.

In v2.6.1 you have "fixed" this and I can no longer tell these messages apart.  The only difference I can find is the before message hold the ID as a number and the after message holds it as a string (please don't fix this).  I shall try to modify my flows to test this.

Is it possible to add an attribute to either the payload or the info objects so that I can tell when the Hub has finished updating and is delivering the final post-update brightness?

Something like postUpdate: true

For information, there are some other strange behaviours when updating.  For example if you set the brightness to zero (from >0), the node first send a message with on: false, allOn: true, anyOn: true, which clearly makes no sense and is presumably a transitional state.  But there is no way to tell that this is not a real state from the message.

Other than that this is a brilliant piece of work and so valuable

Thanks

**Comment by Foddy** [comment]
Thank you for your donation and that you like HueMagic! I really appreciate that!

I just released a fix that fixes the problem differently. Now you should only get one message. Please feel free to reopen this issue if you still face the same errors.

**Comment by SimonB27P** [comment]
Wow!  Such a quick response. I was not expecting that.  

Just had time to test it and the update works perfectly.  One message with the updated status.

Many thanks from an admirer of your work.

Hab noch einen Kaffe von mir

**Comment by Foddy** [comment]
Ich danke dir vielmals! :)

**Comment by readeral** [comment]
This fix seems to have removed the ability to check a group status by passing the group ID via the topic. Any hints on how I can get this functionality back, @Foddy ? In particular I was using the groups node to test if lights were on when my flow received an input from a sensor.
