### ISSUE TITLE
Change brightness without switching light on

### ISSUE THREAD

**Issue by SimonB27P** [Foddy/node-red-contrib-huemagic#155]
Hi

I'm getting more and more into Huemagic and finding out what I can do.  Thanks for your work so far.

I've come across one thing I'd like to do but can't.  There's probably a workaround using variables but what would be useful is to be able to change the brightness of a light or a group without turning it on.  I don't always want the light to come on at the same settings it was at when it was switched off.

So, for example, if I have Light A with brightness at 100% and I turn it off, then the brightness parameter stays at 100% but the "on" parameter is set to false.  If I turn it back on  then it comes back on at 100%.

If the light is off and I change the brightness parameter to 50% then the light turns on at 50%
If the light is off and I send an "extended" object {on:false, brightness: 50} then the on:false is ignored and the light turns on at 50%

What I would like to do is be able to change the stored brightness level so that when the light is next turned on, it comes on at the new level, but do that without turning the light on.

Is it possible to change the node so that from a current state of {on:false, brightness:100%}, the following commands work in the following way:

payload: true -> turns on at 100% (as before)
payload:{brightness:50%} -> turns on at 50% (as before)
payload:{on:false, brightness:50%} -> light stays off but brightness parameter changes to 50%

An even better solution would be that the extended settings would follow the on parameter i.e 
payload:{on:true, brightness:50%} turns on at 50% or stays on at 50%
payload:{on:false, brightness:50%} turns off or stays off  but brightness parameter changed to 50%
payload:{brightness:50%} brightness parameter changed to 50% and on/off state remains unchanged

... but that might break a few people's flows if they are relying on the brightness parameter alone to turn the light on.

A related question:

I'd also like to be able to change the colour temperature while the light is off.  At the moment if the light is off I get an input error "Error:  Philips Hue: 201, parameter, ct, is not modifiable.  Device is set to off."  Perhaps you can't do anything about that if it's a bridge issue.  Maybe I'll have to trap the on/off commands, recall what I want it to switch on at from a variable and send it as an extended command when I want to switch the light on with new settings.

Thanks again for your work

Simon

**Comment by Foddy** [comment]
This works with 2.8.0+ :)!

**Comment by SimonB27P** [comment]
Awesome!  I'll look forward to playing with the new version.

Many thanks

**Comment by SimonB27P** [comment]
Hi 

Just tried this with 2.8 and 2.8.1 and I'm not sure what has changed.  The functionality above doesn't seem to be working.  

Ah OK the last bit has changed.  I no longer get an error if I change the colour temp when the light is off but I can't change the brightness, even if I send an {On : false} at the same time, without the light turning on

If I have a light at 100% and turn it off.  The brightness stays at 100% but the On property changes to false.   If I change the brightness to 50%, the light turns on.  I was hoping it would stay off but when I turn it back on later, it would come on with the brightness already at 50%.

**Comment by SimonB27P** [comment]
Any update on this Foddy?

I still can't change the brightness of a group that's has the ON property set to false (i.e. the lights are off) without the ON property changing to true and the lights coming on at that brightness.  I'm using 2.8.6.

What I'm looking to do is have a timer-based controls that change the brightness and colour temperature settings irrespective of whether the lights are on or off.  Then when someone switches the lights on they come on at those settings without me having to do additional logic or have to keep track of separate variables for what the lights need to come on at next time.

Still finding your nodes super-useful though:^)
