### ISSUE TITLE
Turn colorloop effect on/off

### ISSUE THREAD

**Issue by stieler-it** [Foddy/node-red-contrib-huemagic#157]
**Is your feature request related to a problem? Please describe.**
Currently we can activate the colorloop effect by defining a time duration. It is not possible to activate color loop forever or to disable it if it is active.

**Describe the solution you'd like**
I would suggest that `colorloop: true` results in turning on the effect (without timer) and `colorloop: false` in turning it off again. We should keep accepting a time interval for compatibility, although this feature is not required in my opinion as it should be easily be achieved using a "trigger" node.

**Describe alternatives you've considered**
I could workaround it by setting a very high value when enabling the effect and setting e.g. 100ms when disabling the effect again. Since the high timer is not cleared this would lead to a resource leak, though.

**Additional context**
In OpenHAB Hue addon the effect state can be triggered with a boolean to on/off.

**Comment by Foddy** [comment]
Thanks for that enhancement! It should be available now with v2.6.4 for Hue Lights as well as Hue Groups.
