### ISSUE TITLE
Some bulbs flicker when changing/activating scene

### ISSUE THREAD

**Issue by dafi87** [Foddy/node-red-contrib-huemagic#160]
**Describe the bug**
When switching from one scene to another by using multiple scene nodes, often bulbs that are off in the new scene get switched on for half a second or so. This is not the case when switching between the same scenes in the Hue app.
This also happens when activating the same scene multiple times and is even more obvious then. 
Let's say there's a group with 5 bulbs and the scene would include 3 of them. When activating this scene, the 2 bulbs that should be off get turned on for a second. Activating same scene again keeps the active bulbs on but flickers the 2 bulbs again.

**Expected behavior**
Bulbs not needed in a scene should remain off and don't flicker.

**Please complete the following information:**
 - NodeRED version: 1.0.3
 - NodeJS version: 10+
 - Device running NodeRED: Raspbian on Pi4
 - HueMagic: 2.6.2

Please let me know if you need more info!

Best,
Daniel

**Comment by dafi87** [comment]
Looking at the code helped me track this down.
It only happens when not only the scene is selected in the scene node but also the corresponding group. If I leave the group field empty, only the included lights are triggered but to-be-off lights won't flicker.

Hope it helps!

**Comment by sindalschmidt** [comment]
> Looking at the code helped me track this down.
> It only happens when not only the scene is selected in the scene node but also the corresponding group. If I leave the group field empty, only the included lights are triggered but to-be-off lights won't flicker.
> 
> Hope it helps!

I also experienced this issue. Thank you so much for providing a workaround!
