### ISSUE TITLE
Output message from group node in universal mode incorrect

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#162]
**Describe the bug**
The "anyOn" and "allOn" properties are always false in the output of a group node in universal mode.

**Flow to Reproduce**
```
[{"id":"bc935fbe.4bd9","type":"inject","z":"e89300fe.2a57b","name":"","topic":"1","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":180,"wires":[["79f2ebae.f4f484"]]},{"id":"79d94295.83684c","type":"inject","z":"e89300fe.2a57b","name":"","topic":"1","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":220,"wires":[["79f2ebae.f4f484"]]},{"id":"269d8aca.c82f86","type":"debug","z":"e89300fe.2a57b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":490,"y":200,"wires":[]},{"id":"79f2ebae.f4f484","type":"hue-group","z":"e89300fe.2a57b","name":"","bridge":"7510e6fe.488498","groupid":"","colornamer":true,"skipevents":false,"x":330,"y":200,"wires":[["269d8aca.c82f86"]]},{"id":"7510e6fe.488498","type":"hue-bridge","z":"","name":"Test Hue","bridge":"192.168.86.178","key":"E7EYgH5mcHSqBYTFVrgpMCpMxPClkQB7XqnerXiY","interval":"3000","disableupdates":false}]
```

Injecting a payload of "true" does turn on all the lights in the group. The "on" property is true, as expected. But the "anyOn" and "allOn" properties are false, which is incorrect:

```
{"on":true,"allOn":false,"anyOn":false,"brightness":10,"brightnessLevel":25,"rgb":[255,164,50],"hex":"ffa432","color":"orange","colorTemp":500,"updated":"2020-04-27T11:50:43-07:00"}
```

**Expected behavior**
The "anyOn" and "allOn" properties should be true under the corresponding circumstances.

**Screenshots**
n/a

**Please complete the following information:**
 - NodeRED version: 1.0.4
 - NodeJS version: 12.16.2
 - Device running NodeRED: Raspberry Pi 3B+ (Raspbian buster)

**Additional context**
n/a

**Comment by Onixarts** [comment]
I have also noticed, that status is not beeing refreshed. When I switch off light the group node still **display all lights on (100%)**

**Comment by Onixarts** [comment]
I'm not sure if it helps, but I saw few changes in release 2.8.+ somewhere next to sendstatus to groups. Without deep code review I went to huemagic config node and turn on **Disable events on all nodes**, save, deploy, and turn it off. Now it looks like the status for groups is set properly. Maybe it is related to some settings wasn't set to their default values, cause the status problem.

**Comment by Foddy** [comment]
This node has been completely redesigned in the latest version.
