### ISSUE TITLE
New 'Status' Property - Apply To Hue Brightness, Hue Temperature, Hue Switch, Hue Tap

### ISSUE THREAD

**Issue by townsmcp** [Foddy/node-red-contrib-huemagic#163]
@Foddy is there any way the new 'Status' property introduced in 2.6.5 can be applied to Brightness, Temperature, Switch and Tap nodes? Specially, I would find Brightness and Temperature nodes to be very useful and I just added Switch and Tap in case its possible to add them however I personally dont have a use case for those 2 nodes.

**Comment by Foddy** [comment]
I think it makes sense for the brightness and temperature sensors (added to my _big_ todo list)!

But can you tell me how you would use it on tap / switch nodes?

**Comment by townsmcp** [comment]
I don’t have a use case for switch/tap devices. I included those 2 just as a catch all in case others would find them useful. Personally the ones that I have use case for are temp and brightness sensor. I guess for temp and brightness you would need to add an entry point to the nodes as well as current functionality of exit point? That would be very useful to be able to check status mid flow instead of having the flow start with these devices

**Comment by Foddy** [comment]
Can be done in v3+
