### ISSUE TITLE
Cannot trigger a Scene by its Name

### ISSUE THREAD

**Issue by gcorgnet** [Foddy/node-red-contrib-huemagic#164]
**Describe the bug**
Cannot trigger a Scene by its Name. It works fine with Scene ID, though

**Flow to Reproduce**
```
[{"id":"26a702cc.3d5aee","type":"inject","z":"8ad6993b.ba0b08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":480,"y":680,"wires":[["875ee88b.f7a178"]]},{"id":"875ee88b.f7a178","type":"hue-scene","z":"8ad6993b.ba0b08","name":"Concentrate office","bridge":"d3bca4c8.c0b2e8","sceneid":"Concentrate","groupid":"1","skipevents":false,"x":710,"y":680,"wires":[["a2ed4006.8707f"]]},{"id":"a2ed4006.8707f","type":"hue-group","z":"8ad6993b.ba0b08","name":"Office","bridge":"d3bca4c8.c0b2e8","groupid":"1","colornamer":true,"skipevents":false,"x":910,"y":680,"wires":[[]]},{"id":"d3bca4c8.c0b2e8","type":"hue-bridge","z":"","name":"Philips hue","bridge":"##","key":"xyz","interval":"3000","disableupdates":false}]
```

**Expected behavior**
According to the documentation, it should be possible to trigger a Scene using it's name, not necessarily it's ID. I have a lot of room, all with the same built in Scenes (same names) and I would like to keep things generic... AKA being able to trigger "Concentrate" on the kitchen, as well as the Office, without having to find out the respective Scene Ids.

**Please complete the following information:**
 - NodeRED version: v1.0.5
 - Device running NodeRED: hass.io on NUC

**Comment by Foddy** [comment]
Thanks for this hint! It should work again with the latest version v2.7.0

**Comment by gcorgnet** [comment]
Thanks for this. It seems like you might be picking up the first scene that you can find with this name without checking if actually is associated with the right light/room.
Is there any way to do this?
I have scenes with the same names in multiple rooms and this doesn't work.
Thanks

**Comment by Foddy** [comment]
In this case you also need to pass the correct group ID of the room.

Sorry, it’s not possible to automatically find the correct scene on a room, if the scenes name is not unique. A workaround would be to rename the scenes with unique names. This would work without having to pass an additional group ID.

**Comment by gcorgnet** [comment]
Hi, thanks for your response.
Unless I am missing something, I'm already passing a groupId in the incoming messgae. (see example below). My payload is this: `{"scene":"Concentrate","group":1}`, where there is a valid Scene called "Concentrate" in the room with Id of 1.

```
[{"id":"c4cf0097.a86b2","type":"hue-scene","z":"8ad6993b.ba0b08","name":"Office","bridge":"d3bca4c8.c0b2e8","sceneid":"","groupid":"","skipevents":false,"x":1290,"y":1780,"wires":[[]]},{"id":"65fd26c4.abcf68","type":"inject","z":"8ad6993b.ba0b08","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":780,"y":1780,"wires":[["924fd1bc.bf8d"]]},{"id":"924fd1bc.bf8d","type":"change","z":"8ad6993b.ba0b08","name":"Set payload","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"scene\":\"Concentrate\",\"group\":1}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":990,"y":1780,"wires":[["c4cf0097.a86b2"]]},{"id":"d3bca4c8.c0b2e8","type":"hue-bridge","z":"","name":"Philips hue","bridge":"10.1.1.38","key":"oY2jNLXyPDG3AFdbNUgxadwiGfK4LgOJbkal45ek","interval":"3000","disableupdates":false}]
```

But I could see that the message coming out of my "Scene" node contained a SceneID which was for another Scene named "Concentrate" but belonging to a different room...
Do I need to pass a group ID somewhere else to help with that?

I guess the idea behind using the same name is that it would keep things very straight forward to build a flow where all my room are being set to their "Early Evening" scene, say (whatever that means to that room) instead of having to set the Lounge to "Lounge Early Evening", etc...

**Comment by gcorgnet** [comment]
For know, I have worked around this byt building up a list of my groups (including there scenes) in the global data context. I then swap out my Human friendly name with the right ID (the one that I know actually belongs to the right group)
But it would be good if this was done for us.
