### ISSUE TITLE
Detect when a group of light is being turned on (as opposed to a different scene being set)

### ISSUE THREAD

**Issue by gcorgnet** [Foddy/node-red-contrib-huemagic#165]
**Is your feature request related to a problem? Please describe.**
I would like to be able to know when my lights are being toggled on (be it from motion sensor, manual use of a Dimmer Switch or tap, Home Assistant timer, etc..)

Is there a way to detect this in a universal way?

**Comment by Foddy** [comment]
Of course! You could create a Hue Group node and select the “All lights” option. Wire it with it a function which checks if the “anyOn” or “allOn” property is set to true and return your custom event(s).

**Comment by gcorgnet** [comment]
Thanks forr that. Wouldn't that event be fore whenever something happens on these lights though? Say someone changes the Scene from the official Hue app when the lights where already on?
Simply put, I'd like to know whenever a group of light goes from the off state to the on state, regardless of how that happened... but only that... I don't want these event to fire when the lights were say changed from 100% brightness to 80% brightness.
Does that make sense?

**Comment by Foddy** [comment]
It makes sense! I was able to bring this kind of functionality in the newest version pretty quickly.

To make the whole thing available consistently for each node, the "lastState" object is now also sent in addition to the updated properties. This can either have the state false (boolean) or the entire last state of a node.

You could now write a simple function and compare specific properties from the last state and the new state to solve your problem without redundant actions.
