### ISSUE TITLE
Group with topic 0 ("all groups / lights") fails to control lights

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#166]
**Describe the bug**
Sending a message to a group node using topic 0 results in an error message in the debug pane, "No group Id specified." The same occurs in group nodes with "All groups / lights" configured using the drop-down control in their properties and when topic 0 is passed in the input to a node configured in universal mode.

**Flow to Reproduce**
```
[{"id":"45c962d3.9750ec","type":"inject","z":"94bbc344.05722","name":"","topic":"0","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":160,"wires":[["76649728.b314f8"]]},{"id":"76649728.b314f8","type":"hue-group","z":"94bbc344.05722","name":"","bridge":"d75a339d.b8a97","groupid":"","colornamer":true,"skipevents":false,"x":290,"y":160,"wires":[[]]},{"id":"3866a0ce.988c8","type":"hue-group","z":"94bbc344.05722","name":"All groups / lights","bridge":"d75a339d.b8a97","groupid":"0","colornamer":true,"skipevents":false,"x":310,"y":240,"wires":[[]]},{"id":"ca28c8cd.07d018","type":"inject","z":"94bbc344.05722","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":240,"wires":[["3866a0ce.988c8"]]},{"id":"d75a339d.b8a97","type":"hue-bridge","z":"","name":"Hue Chez Nous","bridge":"192.168.86.21","key":"V7BxU8fI9bL2Pz7Mun4hBLG3g4CBTeaorkAc1uAH","interval":"3000","disableupdates":false}]
```

**Expected behavior**
The group node would control all lights, as in version 2.6.1

**Screenshots**
![all-lights-bug](https://user-images.githubusercontent.com/4588250/80709750-b0934d00-8aa2-11ea-87cc-80c8f8740b3b.png)

**Please complete the following information:**
 - NodeRED version: 1.0.6
 - NodeJS version: 12.16.3
 - Device running NodeRED: Raspberry Pi 3B+ (Raspbian buster)

**Additional context**
n/a

**Comment by Spampunk** [comment]
Hi,
I confirm this bug.

Greetz,
Timo

**Comment by sjodriederedder** [comment]
I can confirm this too, but when creating a zone in the hue app holding all your fixtures you have a workaround :).

**Comment by Foddy** [comment]
"0" as a topic in universal mode for Hue Group nodes should work now with the latest release.

**Comment by aav7fl** [comment]
@Foddy I think something changed in your release this morning. While `0` as a topic works for all lights, any scene group that I have selected seems to be changing all groups. 

My `msg.payload` sent into the Hue node:

```json
{
    "on": true,
    "brightness": 30,
    "transitionTime": 1
}
```

My Hue node: 

![image](https://user-images.githubusercontent.com/3487107/84599134-c59f2200-ae3d-11ea-8a37-6ef88b304de7.png)

**Comment by ryanschmidt** [comment]
I'm also experiencing this issue. Flows that use to correctly control certain Hue Groups now control all lights. e.g. set counter lights to 15% brightness on motion now sets all lights in the house to "on" (varying level of brightness and color) on motion.
