### ISSUE TITLE
Motion sensor node sending null value for "active" property when flow starts

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#168]
**Describe the bug**
Motion sensor node is sending null value for "active" property in output message when flows start.

**Flow to Reproduce**
```
[{"id":"da35ab1.9970358","type":"hue-motion","z":"7e1b178a.ad5968","name":"Kitchen Motion Sensor","bridge":"d75a339d.b8a97","sensorid":"118","skipevents":false,"x":330,"y":180,"wires":[["d6e8954a.cadab8"]]},{"id":"d6e8954a.cadab8","type":"debug","z":"7e1b178a.ad5968","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":530,"y":180,"wires":[]},{"id":"d75a339d.b8a97","type":"hue-bridge","z":"","name":"Hue Chez Nous","bridge":"192.168.86.21","key":"V7BxU8fI9bL2Pz7Mun4hBLG3g4CBTeaorkAc1uAH","interval":"3000","disableupdates":false}]
```

**Expected behavior**
The value for the "active" property should reflect the current state of the motion sensor device.

**Screenshots**
![motion-sensor-bug](https://user-images.githubusercontent.com/4588250/80721066-a11c0000-8ab2-11ea-883c-40f80c8f425f.png)

**Please complete the following information:**
 - NodeRED version: 1.0.6
 - NodeJS version: 12.16.3
 - Device running NodeRED: Raspberry Pi 3B+ (Raspbian buster)

**Additional context**
n/a

**Comment by Foddy** [comment]
This should no longer occur in the latest version. Please reopen if you still face this issue.
