### ISSUE TITLE
Please throw errors when operations fail

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#169]
**Is your feature request related to a problem? Please describe.**
Some failure conditions are logged to the debug pane without throwing errors that could be handled using `catch` nodes. This makes flows more fragile than they ought to be when issues arise.

Specific example: a recently introduced bug in `group` nodes broke some of my flows. The bug (reported separately, see [issue 166](https://github.com/Foddy/node-red-contrib-huemagic/issues/166#issue-609913614)) causes a `group` node to fail to control the lights under certain conditions that previously worked. The failure is logged to the debug pane by the `group` node but no exception is thrown. This means that my error detection and reporting logic is not triggered. The previously working feature in my flow silently fails to work from the point of view of a user of my dashboard with no indication of the cause of the failure or, in some scenarios, without it being clear that anything failed at all until someone notices that some physical device failed to change state or the like.

**Describe the solution you'd like**
Error conditions should be signaled by throwing exceptions, not just logging. Since this would be a breaking change, I would be ok with this being a configurable option.

**Describe alternatives you've considered**
Not really applicable. It might be possible to work around this to some extent in Node-RED 1.x on a case-by-case basis if huemagic nodes supported the functionality required by the `complete` node but the last time I checked, they did not. This would be a very poor work-around, in any case.

**Additional context**
Not applicable

**Comment by Foddy** [comment]
Should happen in the v4 update
