### ISSUE TITLE
Is it possible to check if a device is offline / not responding?

### ISSUE THREAD

**Issue by jensrossbach** [Foddy/node-red-contrib-huemagic#170]
I have a light bulb in a conventional lamp with a conventional power switch on the wall. This means if I turn off the light via the wall switch, it has no power and is offline. In my Node-RED dashboard, the lamp appears to be turned on although it is actually turned off. Therefore I would like to detect the offline state of the bulb and then set the dashboard switch to off state.

**Comment by Foddy** [comment]
This should work now automatically with the latest version :)!
