### ISSUE TITLE
Hue Light node outputs twice

### ISSUE THREAD

**Issue by Andreyooo** [Foddy/node-red-contrib-huemagic#171]
The light node does output twice occasionly now.
What's strange when that happens, is that the first output has some random brightness value, The second output has the correct value.
It doesn't matter wether it's changing color, powering on or changing the brightness.

**Comment by philosoma** [comment]
Fairly new to this, but I am getting double messages from a light group if I change the state via a switch on the dashboard. The switch will go on, off, slight pause, back on. It's like msg.laststate.payload is getting pushed to msg.payload as well.

**Comment by chrismox** [comment]
I'm seeing the same issue from both the light node and the group node. I get the first event message then a second comes through about a second later.

This makes the lastState info useless, because the second event message therefore shows the current settings.

**Comment by Foddy** [comment]
Fixed with the latest version :)
