### ISSUE TITLE
hue-bridge-config.js not loading Hue Switch drop-down

### ISSUE THREAD

**Issue by mectors** [Foddy/node-red-contrib-huemagic#173]
**Describe the bug**
When using the Hue Switch node and doing a search for a Switch, none are shown although the Hue Bridge has a Hue Smart Button connected. Directly introducing the ID works.

**Flow to Reproduce**
```
[{"id":"2763da57.a890d6","type":"hue-switch","z":"87190a9b.f156e8","name":"","sensorid":"","skipevents":false,"x":160,"y":200,"wires":[[]]}]
```

**Expected behavior**
A drop-down should appear with all the detected switches.

**Please complete the following information:**
 - NodeRED version: [v.1.0.6]
 - NodeJS version: [v10.19.0]
 - Device running NodeRED: [Hue Smart Button]

**Additional context**
This stops none technical users from being able to use the Hue Switch node.

**Comment by Foddy** [comment]
Please try again with the latest version :)
