### ISSUE TITLE
Poll light status when sending command

### ISSUE THREAD

**Issue by jensrossbach** [Foddy/node-red-contrib-huemagic#175]
As far as I understood there is no event based API for the Hue bridge available and therefore the status of lights is polled regularly by Huemagic. Especially when using dashboard buttons that are supposed to switch on/off a light and change their appearance depending on the actual status, unfortunately this leads to a delay between button press and appearance update which is equal to the poll delay in worst case.

As a proposal, would it be possible to explicitly trigger a poll for the light status after a command has been sent which supposes to change the light status in order to get a faster update?

**Comment by Foddy** [comment]
Sure, simply send a `msg.payload.status` command to the affected node to immediately get the current status of the node. Please feel free to reopen this issue if I misunderstood your plan.
