### ISSUE TITLE
Error: Huejay: read ECONNRESET

### ISSUE THREAD

**Issue by bausi2k** [Foddy/node-red-contrib-huemagic#176]
## Versions 
__node-red: 1.0.6__
__node-red-contrib-huemagic: 2.7.0__
__node: 10.20.1__

## Problem
I'm controlling 8 lights and two groups within in page and with one Bridge. Everything runs fine, but o often geht the error in den Debug section... I don't know if this is something to worry or just an "not well handled" behavior in the _Huejay_ library or not...

One thing I'm not completely convinced yet, is that it only happens, when i connect more than 7 HueMagic nodes. From the time, the 8th node is connected, those errors start happening.

Additionally I see also "socket hang up" Errors in the log...
![Error_ Huejay_ read socket hang up](https://user-images.githubusercontent.com/3243728/83847057-e2d04400-a70b-11ea-9d68-38f9213ca430.png)

Is there a way to debug that further? I'm using a Synology NAS and everything runs under Docker
![Error_ Huejay_ read ECONNRESET](https://user-images.githubusercontent.com/3243728/83846618-2aa29b80-a70b-11ea-9c8f-87b64c6856d6.png)

**Comment by ozett** [comment]
i think  this error occured long time ago...
i am already used to see this on and on in the logs ....

if it is a bug, i would be glad it could be solved... 👍 

![image](https://user-images.githubusercontent.com/5937811/83860847-1917be80-a720-11ea-93c5-dcaecb71bb1c.png)

**Comment by Foddy** [comment]
Should not happen any longer with the latest release :)

**Comment by valbuz** [comment]
Hi
After update to 4.04

i have the following error and NodeRed restarts:

TypeError: Cannot read property 'on' of undefined at HueGroup.applyCommands (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:329:49) at HueGroup._inputCallback (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:95:54) at /opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26 at Object.trigger (/opt/iobroker/node_modules/@node-red/runtime/lib/hooks.js:113:9) at HueGroup.Node._emitInput (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11) at HueGroup.Node.emit (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25) at HueGroup.Node.receive (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10) at Immediate.<anonymous> (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/Flow.js:679:52) at processImmediate (internal/timers.js:464:21)
