### ISSUE TITLE
Connection Errors since Dimmer switches

### ISSUE THREAD

**Issue by oehm2007** [Foddy/node-red-contrib-huemagic#18]
Hey foddy, 
since I put in the new functionality with dimmer switches I get a lot of connection errors through all of the huemagic-nodes. I can`t see a rule behind that behavior. The only thing is a constantly : "Error: Huejay: read ECONNRESET" and after a while : "Error: Huejay: timeout of 15000ms exceeded".

Have you got any idea? I think it appeared first time , after putting in a dimmer switch in my project.
Thanks again for your support :-)

Edit: Yes I am sure now, that the error is thrown cause of my dimmer switch. Obviously if I am pushing a button while there is that connection error, I can solve that behaviour. Until it is starting again after some time by itself.

**Comment by lespatots** [comment]
Foddy,
I have a similar error
"8 Dec 17:17:31 - [error] [hue-switch:KitchenSwitch] TypeError: Cannot read property 'toString' of null"
All my switches throw this error after a long time and it stays until I press a button. A restart of node-red did not fix the error, just the button press. Does that imply it is something in the data coming back from the switch?

**Comment by ycharron-cstj** [comment]
I got a lot of connection error to or not reacheable. This is only in node-red because the app on my phone work perfectly.

**Comment by oehm2007** [comment]
I just noticed that of my motion sensors are not working any more. If I redeploy everything looks fine but after a while all of the nodes say connextion error. The lamps can be temporarily healed by switching them on. But the motion sensors and the dimmer switches anyway stay in the error till I redeploy. 
So actually the plugin is not usable anymore on node-red

**Comment by Foddy** [comment]
Wow there are a lot of issues going on here! Sorry for that…
I just released v1.3.1 which should fix some of the mentioned errors.

@oehm2007 It seems to be an issue with the Philips Hue API / Bridge if I am not wrong. If I remember right you are running Node-RED on a non-wired connection to your router. In this case it's probably better to increase your poll interval setting in your Hue Bridge node to something bigger than 3000. If you have more than 10 Hue nodes active I suggest you to choose something between 5000 and 10000. I know this makes some actions a bit slower but it will definitely decrease the workload on your Router, Node-RED Host and your Philips Hue Bridge & hopefully this connection errors.

I am thinking of a new poll interval improvement in a future release to reduce the latency on Hue Switch and Hue Tap devices without affecting the whole network.

Until then it's probably better to use a wired connection to your router or to increase the "Poll interval" setting on your Hue Bridge to something between 3000 - 10000.

**Comment by oehm2007** [comment]
Thanks for your fast feedback. I am running huemagic on a lan driven raspberry and on a wifi raspberry. There were errors on both devices, but I changed the polling time to 5000 and obviosly its running much better. One of the motion sensor still has much more errors than the other two.I dont know why. But maybe its due to your latest release, that the whole system is running a bit better. I will observe the behavior the next days.
