### ISSUE TITLE
Lights now flicker on/off since 2.8.2 fix

### ISSUE THREAD

**Issue by kazzyUK** [Foddy/node-red-contrib-huemagic#181]
I was getting the same issues people had reported about 2.8.1 which required going back to 2.7.2.

I've installed 2.8.2 but now the lights try to turn off but they then turn back on and you get this flickering off/on affect.

I can stop this from happening if i stop the node-red service.. 

Very simple on/off flow and also via the Extended mode. neither work..

so far.. 2.7.2 code works...  2.8.1 and 2.8.2 have issues.

ta.

**Comment by Foddy** [comment]
I hope this will not happen again with the newest update!
