### ISSUE TITLE
Try to query state of a light

### ISSUE THREAD

**Issue by Tho5170** [Foddy/node-red-contrib-huemagic#182]
Hello,

I started with huemagic a few days ago. Now I tried to make a flow acting as a nightlight. There are some input events i will recognise (blinds are up or down, light outside is bright or dark) and depending of these states I will switch a HUE led tripe on or off. This works fine.

Now I startet some optimization. If the ligth is on there shoud not be sent a new switch-command to switch the light on, and vice versa.

Bevor switching the light, I did send a {"status":0} to the light and decide on the resulting payload.on true/false if I need to switch the light or not. But now it seems there is an interaction between getting the state and switching the state. For a view minutes the light goes on then off, and on and off ...

What is wrong in my flow?

![flow](https://user-images.githubusercontent.com/68482503/87862721-7e7fe180-c953-11ea-898a-f205d5ccf990.png)

Thank you

**Comment by Tho5170** [comment]
No hints for me?

**Comment by behtjes** [comment]
Those nodes outputs a msg at every change of your light. So your flow starts (sometimes) in the middle at the blue light nodes. 

cut the light node out of your flow and create a flow variable for it's state with a function node and this code inside: flow.set("light", msg.payload.on);

Read the flow variable value in a switch.
if flow.light == true (on) or false (off)

![Knipsel](https://user-images.githubusercontent.com/9257476/102925315-6e84a480-4493-11eb-8fe6-d809e8f8164c.JPG)
