### ISSUE TITLE
Friends of Hue problems

### ISSUE THREAD

**Issue by SimonB27P** [Foddy/node-red-contrib-huemagic#183]
Hi Foddy

Still loving what you're doing here but I'm having problems with a Friends of Hue switch.

I have a Senic Friends of Hue switch, that is registered to the hub but neither the Hue Switch nor the Hue Tap nodes can find it.  Teh switch node says there are no switches; the Tap node just shows an empty list.  The switch operates the light I have set it to control OK using the Hue App and I get a load of stuff from the Bridge node but I can't seem to find a simple way just to generate button events in node-red so I can do more sophisticated stuff.

Other people seem to have got a Senic switch to work in HueMagic

Can you help?  Am I doing something wrong?

Many thanks

**Comment by SimonB27P** [comment]
OK solved this but there is still a problem.  I think I have the same issue as mectors @mectors identified on 10 May.  Sorry for having not searched hard enough to find it.

If I enter the ID number of the switch as a Hue Tap then the node accepts it and everything works as it should.  The search function does not work though so I can't find the Friends of Hue switch from the drop down list.  Took me a while to work this out.

Keep up the good work

**Comment by gewaechshaus** [comment]
Hey,

@Foddy @SimonB27P - same here...

**Comment by Foddy** [comment]
Please try it again with the latest version. All buttons/switches should be compatible with the new Hue Buttons node, if there is a valid connection to the bridge.
