### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by hklages** [Foddy/node-red-contrib-huemagic#184]
**Describe the bug**
There are a lot "Unhandled promise rejections" in my debug file. 
192.168.178.26 is the Hue gateway in my network.

Error message is: 
(node:918) UnhandledPromiseRejectionWarning: Error: Huejay: connect EHOSTUNREACH 192.168.178.26:80
at getHttpClient.request.then.catch.error (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1336)

**Expected behavior**
promises should be handled :-)

**Please complete the following information:**
 - Node-RED version: 1.1.2
 - NodeJS version: 10.21.0
 - Device running Node-RED: CCU3 (raspi 3)

**Additional context**

**Comment by Travelbacon** [comment]
Same as #106

**Comment by Foddy** [comment]
Fixed with the v4 update :)
