### ISSUE TITLE
Unclear documentation what day light en dark is in light sensor.

### ISSUE THREAD

**Issue by Travelbacon** [Foddy/node-red-contrib-huemagic#185]
It is for me unclear what the definition of daylight and dark/light of a light sensor is. Are they not the same?
What is it defined in lux and is it possible to change it?

It would be better if this is written in the description of the light sensor.

**Comment by Foddy** [comment]
Unfortunately, this information comes directly from the sensor itself. According to the official Philips Hue documentation, there is no further information on how a sensor determines this status. 

If both the "dayLight" and "dark" are set to false, the sensor recognises some kind of "twilight". Then it's neither dark nor day for the sensor _(just in case you're wondering why sometimes both are set to false)_.

If you're not happy with the states that are coming from the sensor directly, you could write your own simple if/else function in NodeRED and just use the lux information to define dark/dayLight on your own. In some situations and (sensor) locations this might make sense.

**Comment by Travelbacon** [comment]
It is not I am unhappy. The information was missing what is daylight defined as. A value is my opinion really usuable if you know the definition.

My geuss is that daylight is ethical labor condition. That could be 80 Lux.

**Comment by Foddy** [comment]
Sure! No you’re right. This should and will be better documented from my side as good as I can with the current information I can get.

In my “experiments” I can have a much lower Lux value in another sensor but it shows dayLight to true while the other with a higher Lux value shows dark = true. There must be another factor in this calculation... maybe the colour temperature of the light hitting the sensor?!

It seems that many people also from other libraries have the same issue with the lack of the detailed information: https://github.com/ebaauw/homebridge-hue/issues/83#issuecomment-287618222

**Comment by Travelbacon** [comment]
Let's hope that Signify maintain the Philips spirit regarding documentation and openness...
