### ISSUE TITLE
A way to query a Hue Dimmer for it's battery level?

### ISSUE THREAD

**Issue by MorningZ** [Foddy/node-red-contrib-huemagic#187]
Maybe I am just missing it, but is there a way to query a switch device for it's current battery level?   I am trying to put together a Node-RED flow to report all battery levels to me and I've got everything reporting back except for these particular types of device.

The "status" option on the Motion Sensor works great to reveal the current battery level.  I see and understand that this "input" option on a Hue Switch node doesn't exist but is there some clever work around to this without needing to push a button?

Thanks in advance

**Comment by Foddy** [comment]
Can be done in v3+
