### ISSUE TITLE
Support changing colour when device is off

### ISSUE THREAD

**Issue by hazymat** [Foddy/node-red-contrib-huemagic#188]
I have developed a NodeRED [Home Lighting Zone Management system](https://discourse.nodered.org/t/home-lighting-zone-management-system/23848), which outputs separate messages for brightness and colour.

In the case where the light is off (because I set brightness to 0), then I set the scene in my zone management system which turns the light on and sets the colour, this is usually no problem. My system outputs the brightness first, which turns the bulb on, then the colour. After all, if the system set the colour first, and the bulb was turned off, then the bulb would come on without having received the correct colour. This is because it appears you cannot set colour of a bulb that is OFF.

On rare occasions the messages get out of sequence, and an OFF bulb is sent a colour then a brightness. This may be because someone has turned the light off in the app (not through my system) or MQTT didn't deliver messages in order. Either way it doesn't work, as you cannot set the colour of an OFF bulb.

I presume this is a Hue limitation (I see no reason why a bulb shouldn't have a colour state that persists whether the bulb is on or off, but hey...)

But is there a way to make this work smoothly?

For example, HueMagic might be able to support setting the colour of a bulb that is off?

Another example, it may be possible to query the bulb to see if it's actually off before attempting to set it (maybe this could be a workaround that I could implement without a resolution of this issue here on GitHub?)

**Comment by Foddy** [comment]
Do you have the latest version installed? You can change light and group properties like colours etc. on turned off devices with version 2.8.0+ (or did I misunderstood something?).
