### ISSUE TITLE
Random Light Color generates invalid values

### ISSUE THREAD

**Issue by tundratier** [Foddy/node-red-contrib-huemagic#189]
**Describe the bug**
When setting the light color to "random", "any", or "whatever" the error "Expected a valid hex string" might occur.
This issue is a duplicate of the closed issue #146. I was not sure if closed issues are getting any attention.

The bug is caused by 5 digit HEX codes that might be generated by the random color function.
I have extracted the relevant code into this runkit: https://runkit.com/tundra/node-red-contrib-huemagic-random-issue

The erroneous code can be found here: https://github.com/Foddy/node-red-contrib-huemagic/blob/master/huemagic/hue-light.js#L154
There are also duplicates of this code within the HUE group code.

**Expected behavior**
The code should generate a 6 digit RGB hex code every time.

**Additional context**
It should be an easy fix, I might issue a PR this week myself.

**Comment by Foddy** [comment]
Thanks for contributing! I just merged your changes :)!
