### ISSUE TITLE
Losing id

### ISSUE THREAD

**Issue by Cheddaru** [Foddy/node-red-contrib-huemagic#19]
Hi. I am having an issue where "Hue Light" can handle 1 payload.msg before it reports

>"Error: Philips Hue: 3, resource, /lights/NaN, not available"

"Hue Group" also works fine the first time, but subsequent messages change the id to 0

After first inject:

>{"id":2,"lightIds":"3, 4","name":"Hallway","type":"Room"}

After subsequent injects:

>{"id":0,"lightIds":"1, 2, 3, 4, 5, 6, 7","name":"Group 0","type":"LightGroup"}

On both cases I am injecting a payload with only a boolean value.

>{"_msgid":"486dee22.8b5fb","topic":"","payload":false}

Running on rpi1 with Node-red v0.17.5 and node v6.12.1

**Comment by Foddy** [comment]
Thank you for reporting this issue. It has just been fixed in HueMagic v1.3.0.

**Comment by loadedtech** [comment]
I'm getting a similar issue ... but on the first try -- 

I have a light:
> {"payload":{"on":true,"brightness":100,"rgb":[255,202,124],"hex":"ffca7c","updated":"2018-01-08T12:15:42+00:00"},"info":{"id":4,"uniqueId":"00:17:88:01:10:55:a9:76-0b","name":"Lounge 1/2","type":"Extended color light","softwareVersion":"5.50.1.19085","model":{"id":"LCT007","manufacturer":"Philips","name":"Hue bulb A19","type":"Extended Color Light","colorGamut":"B","friendsOfHue":true}},"_msgid":"652308c3.7737b8"}

and I try to inject some new values
> {"_msgid":"6023df8d.062b8","topic":"","payload":{"on":true,"brightness":20,"rgb":[80,40,0,0]}}

The config looks fine, but get the error after the injection:
"Error: Philips Hue: 3, resource, /lights/NaN, not available"

The lights are listed correctly in the search and the id (4) is saved in the light field

node v6.11.2; node-red v0.17.5 on a Raspberry Pi v3b

Any tips appreciated.

**Comment by Foddy** [comment]
Hi @loadedtech! Thank you for this report. It should be be fixed with the most recent version of HueMagic. Please let me know if you still face this kind of errors.
