### ISSUE TITLE
Please make motion sensor node features consistent with light, group nodes

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#192]
**Is your feature request related to a problem? Please describe.**
Inconsistent features of motion sensor node vs lights, groups.

**Describe the solution you'd like**
Please support "universal mode" for motion sensors. Please emit motion sensor state change messages, e.g. activate true / false, as global events from bridge node.

**Comment by Foddy** [comment]
Should be more consistent now with the latest version (v3)
