### ISSUE TITLE
Question: What is the meaning of "skip events"

### ISSUE THREAD

**Issue by hklages** [Foddy/node-red-contrib-huemagic#194]
I can not find any documentation about the "skip events" in light node, group node.
Does it activate a listener? Is it recommended to tic that option in case the node only sets a state (and node output is not used)?

**Comment by GeorgeCastanza** [comment]
I find that "skip events from this node" (bulb node) stop all events from passing through the node, whereas, I expected it to not pass changes made external to Node Red, but to pass on messages via an input wire from within Node Red.  

Great job with HueMagic!

**Comment by Foddy** [comment]
You can find the information in the docs section of the node in NodeRED with v3.0+
