### ISSUE TITLE
Change brightness without turning lights on

### ISSUE THREAD

**Issue by SimonB27P** [Foddy/node-red-contrib-huemagic#196]
I still can't change the brightness of a group that's has the ON property set to false (i.e. the lights are off) without the ON property changing to true and the lights coming on at that brightness. This happens even if I send a message with the on property set to false.

I'm using 2.8.6.

What I'm looking to do is have a timer-based controls that change the brightness and colour temperature settings irrespective of whether the lights are on or off. Then when someone switches the lights on they come on at those settings without me having to do additional logic or have to keep track of separate variables for what the lights need to come on at next time.

Every time I change the brightness setting, the lights come on at that level of brightness.  This behaviour is the same for both individual lights and for groups.

This is the same as issue#155 which has been marked as closed but the problem doesn't seem to have been fixed unless I am missing something.

**Comment by denisulmer** [comment]
I have the same problem, any update on this?

**Comment by SimonB27P** [comment]
I don't suppose you have found a way around this have you Denis?

Maybe this is something the Huemagic API won't let us do?!

That would be a shame.  I'd really like this feature.  I am programming my lights to come on at different colour temperatures depending on the time of day / sunrise / sunset etc and I'd like to be able to just change the colourtemperature without turning the light on so that, next time it is turned on, it is already at the right setting.

At the moment, I am having to program logic that traps the intention to turn the light on, look-up the new temperature I want it to be (stored somewhere else in a variable) and inject that variable into the message before sending it to turn the light on.  It's not an elegant or easy way to do it!

If I can create a simple standard flow that does this then I'll share it.

**Comment by Kenny-JTK** [comment]
+1 I'm trying to do the same thing with a group of lights. Now when the lights are off and i send an brightness level of eg. 20% you see the lights turn on to the last value eg 100%. I was going thru the code and there is indeed a fixed param that adds group.on = true to the msg ignoring any passed value.

**Comment by SimonB27P** [comment]
That would be a fantastic spot Kenny and if it's simple to fix then hopefully Foddy can have a look at it soon.  

I was about to embark upon some NodeRed coding this evening using variables to store the brightness and colorTemp I want the lights to come on at next time and a means of directing all on commands through some code to check whether the lights need to come on at a different setting from when they were turned off.  Fixing this would save me from doing all that  because I can just store the next-on setting with the light itself :^)

**Comment by Kenny-JTK** [comment]
I found some time and tried it out myself edditing the hue-group.js file and changed the following around line 
[https://github.com/Foddy/node-red-contrib-huemagic/blob/0503ad3b1c234d496c3d349635ef66e24ed625a1/huemagic/hue-group.js#L301](url)

From 
`else
                    	{
                    		group.on = true;
                    		group.brightness = parseInt(msg.payload.brightnessLevel);
                    	}`

To 
`                        else {
                        	if (typeof msg.payload.on != 'undefined')
                        	{
                        		group.on = msg.payload.on;
                        	}
                        	else
                        	{
                        		group.on = true;	
                        	}
                            group.brightness = Math.round((254 / 100) * parseInt(msg.payload.brightness));
                        }`

If you want to to do it for a single light it would require the same change in hue-light.js i presume
the default behaviour was kept ; no "on" in the msg will turn the group on
when send a command on:false,brightness:50 the value changed without turning on the lights.
the next time an "on" was send they came on at 50%

@Foddy Maybe a quick fix to implement in the next build?

**Comment by SimonB27P** [comment]
Nice work Kenny.  I'll have a play with that.   A quick try didn't work for me but I think we have to make the change in two places, one to trap the brightnessLevel property and the other to trap brightness property depending on which is provided.  I think the code above has the two mixed up, or am I wrong there?

I'll have another look.

I did find a work around by playing with the hue api itself.  It's easy to do with the HTTP request node.  According to the api documentation, apparently you are not supposed to be able to change the brightness or ct parameters if the light is switched off (I don't know why and I've asked on the hue developers' forum for this to be enabled).  Sure enough the bridge returns an error if you try to **_but_** the new values are still actually stored.

It does work but if you send a high brightness value with the on property set to false, the lights flicker on briefly, which is not what we want.  I tried to get round this by adding in a transition time but it all got very unreliable if I did that.  Sometimes the values were not stored at all.  Maybe something to do with the order the commands are processed by the hub

What did work was changing the brightness with bri_inc with the on property set to false.  That seems to do exactly what I need but I will have to get the current brightness first and do some maths to get to the new brightness or ct.  

If I can get your way to work though, it would be better.

**Comment by SimonB27P** [comment]
Hmmm I changed the code in both areas to deal with brightness and brightnessLevel but it's still not working.  The lights come on still.  I'll have a look to see if I can find somewhere else that is changing group.on to true when it shouldn't

**Comment by jeankone** [comment]
im also interested in this feature

**Comment by Foddy** [comment]
Should work with the latest update :)
