### ISSUE TITLE
Error: Huejay: Parse Error Invalid Character in Chunk Size

### ISSUE THREAD

**Issue by TheOddPanda** [Foddy/node-red-contrib-huemagic#197]
Im using the Philips Hue Bridge Emulator (http://steveyo.github.io/Hue-Emulator/) in order to test a flow. The flow is a simple flow which changes the color of the hue bulbs randomly. Whenever I trigger the Function i get the following error: _[error] [hue-light:Testbridge] Error: Huejay: Parse Error: Invalid character in chunk size_
As I have no clue what that could mean I thought I might ask here because I think Im doing everything right. 
The Emulator only supports Bridges of V1 which is kinda unlucky but I don't think that should be the problem? 

The Flow:
<img width="1115" alt="Screenshot 2020-09-08 at 15 02 49" src="https://user-images.githubusercontent.com/17354531/92479847-5dfe3600-f1e4-11ea-84b9-41015a9dafe6.png">

**Setup**
 - Node-RED version: v1.1.3
 - NodeJS version: v14.7.0
 - Device running Node-RED: MacOs Catalina (Localhost)
 - Emulator version: 0.0.8

**Comment by Foddy** [comment]
This shouldn't occur with the latest version & the a CLIP/v2 API compatible Bridge / simulator.
