### ISSUE TITLE
Motion Sensor - No Temp

### ISSUE THREAD

**Issue by heydemar** [Foddy/node-red-contrib-huemagic#2]
Hello, i have a Problem with my new and now second Motion-Sensor in Node-Red. 
The Device give me no "Battery-Status", only this Information over the Debug-Node: 

18.9.2017, 20:13:32node: 60fc994.ba3b9e8
msg.payload : Object
object
lightLevel: 0
dark: true
daylight: false
updated: "2017-09-18T18:05:17"

My first give me the Battery-Status. 
The two Devices have the Same Part/Model-Number on back. 
9290012607

Some Ideas?

**Comment by Foddy** [comment]
Hi, it seems that you’ve chosen your Lux / Brightness Sensor but not your motion sensor node. Is this correct? Note that your Hue Motion sensor has also a Lux and Temperature sensor included.

The battery status also moved on all nodes into the msg.info object. Please check this section at the documentation: https://github.com/Foddy/node-red-contrib-huemagic/blob/master/README.md#additional-motion-sensor-information

**Comment by heydemar** [comment]
Sorry :) I mean the Hue Lux/Brightness Sensor. 
Nice, in the msg.info i find the Battery. 
But take a look at this: 
In my new Motion/Lux/Brightness-Sensor ;) i have this Infos of Battery: (NULL)

18.9.2017, 20:44:40node: 607fbccd.36b694
msg.info : Object
object
id: 14
uniqueId: "*****"
name: "Hue ambient light sensor 2"
type: "ZLLLightLevel"
softwareVersion: "6.1.0.18912"
battery: null
model: object
id: "SML001"
manufacturer: "Philips"
name: "Hue Motion Sensor"
type: "ZLLPresence"

At a other Motion/Lux/Brightness-Sensor, the correct Infos: 

18.9.2017, 20:45:55node: 607fbccd.36b694
msg.info : Object
object
id: 9
uniqueId: "*******"
name: "Hue ambient light sensor 1"
type: "ZLLLightLevel"
softwareVersion: "6.1.0.18912"
battery: 100
model: object
id: "SML001"
manufacturer: "Philips"
name: "Hue Motion Sensor"
type: "ZLLPresence"

**Comment by Foddy** [comment]
Hm interesting.. This must be a bug by the Philips Hue API, since the correct information is displayed properly on your other motion sensor..

The only possible solution I could suggest is to try to reset the sensor and link it again to your bridge. :S

**Comment by heydemar** [comment]
I have delete the Motion-Sensor and pair it again with my Bridge, same issue: 

19.9.2017, 18:05:54node: 607fbccd.36b694
msg.info : Object
object
id: 18
uniqueId: "*********"
name: "Hue ambient light sensor 2"
type: "ZLLLightLevel"
softwareVersion: "6.1.0.18912"
battery: null
model: object
id: "SML001"
manufacturer: "Philips"
name: "Hue Motion Sensor"
type: "ZLLPresence"
