### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" when using http request node

### ISSUE THREAD

**Issue by Torsten85** [Foddy/node-red-contrib-huemagic#200]
**Describe the bug**
Sometimes lights don't react to input from an http request node.

A "RangeError: Maximum call stack size exceeded" error is logged in the server console

**Expected behavior**
The error  should not happen obviously

**Please complete the following information:**
 - Node-RED version: [latest docker image]
 - Device running Node-RED: [raspberry]

**Additional context**

the http request node adds `msg.req` und `msg.res` to the message object.
Huemagic tries to merge that req object with a future state here: https://github.com/Foddy/node-red-contrib-huemagic/blob/master/huemagic/hue-light.js#L283

The `req` object has circular fields, so the merge function would call itself indefinitly.
This should be an easy fix.

**Comment by Foddy** [comment]
Should be fixed with the latest version. Let me know if you still face this issue for some reasons...

**Comment by dbowerman** [comment]
I still have this issue with v3.0.0. what can I do to help resolve it?
