### ISSUE TITLE
Unhandled promise in 

### ISSUE THREAD

**Issue by hklages** [Foddy/node-red-contrib-huemagic#204]
**Describe the bug**
See the log message: 
Oct 22 06:53:51 ccu3-webui daemon.err node-red: (node:1073) UnhandledPromiseRejectionWarning: Error: Huejay: timeout of 15000ms exceeded
Oct 22 06:53:51 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/node_modules/huejay/lib/Transport.js:106:15
Oct 22 06:53:51 ccu3-webui daemon.err node-red:     at runMicrotasks (<anonymous>)
Oct 22 06:53:51 ccu3-webui daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Oct 22 06:53:51 ccu3-webui daemon.err node-red: (node:1073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)`

**Flow to Reproduce**
No - its from the log fiel

**Expected behavior**
No unhandled promises because they might break Node-RED

**Please complete the following information:**
 - Huemagic 3.0
 - Node-RED version: 1.1.3
 - NodeJS version: 14.13.1
 - Device running Node-RED: CCU3 (raspberry 3b)

**Comment by mondface** [comment]
you must increase the time in the properties for the hue bridge: Polling interval to 10000

**Comment by Foddy** [comment]
Fixed in the latest release
