### ISSUE TITLE
huemagic only for hue bridge?

### ISSUE THREAD

**Issue by Staubgeborener** [Foddy/node-red-contrib-huemagic#206]
Does `huemagic` only work with a Hue Bridge or even with virtual bridges like Phoscon? If not, could you please patch this up? 

I own many Hue devices, but these are connected via phoscon and not with a Hue Bridge. Phoscon also offers the possibility of a virtual button push.

**Comment by Foddy** [comment]
Please try it out with your virtual bridge. I never heard about "phoscon", but if it imitates the official Hue Bridge and it's API, then I don't know why this shouldn't work with HueMagic.

Let us know if it worked :)!

**Comment by Staubgeborener** [comment]
I pressed the connect button in the Phoscon app. This is the equivalent of the Hue button. An API key was automatically obtained. Nevertheless, I get the error message "The selected Hue Bridge is invalid"

![Unbenannt](https://user-images.githubusercontent.com/28908603/98450092-fb6cdc00-2139-11eb-9859-0d8b7f58d754.png)

**Comment by Foddy** [comment]
As long as your virtual bridge is supporting the latest CLIP/V2 API from Philips Hue, it shouldn’t be the case any longer.
