### ISSUE TITLE
Support for Friends of Hue Aurora dimmer (by Lutron)

### ISSUE THREAD

**Issue by hurenkam** [Foddy/node-red-contrib-huemagic#207]
There seems to be good support for Dimmer Switch and Smart Button to use as input devices, however i also have a few Aurora Dimmers that I would love to couple to node-red, but could not find support for it.
The devices are really nice, and resemble a traditional rotary dimmer that can be turned left and right, and have a center button. Typically they are set up to do dimming when turning the rotary, and on/off when pressing the button. In essence they are not very different from the Dimmer Switch and Smart Button.
I managed to get some events in through home assistant, but this is not ideal, and just adds another layer of latency.

See here for the device:
https://www.lutron.com/en-US/products/pages/standalonecontrols/dimmers-switches/smartbulbdimmer/overview.aspx

**Comment by ryanschmidt** [comment]
+1 for this one. It would be a great addition. I’ll use Lutron Picos for now but would love to use the Lutron Dimmer buttons to cover some old flip switches.

**Comment by Foddy** [comment]
Should be supported now :)

**Comment by PepeVegas** [comment]
Dears,

 

can you please unsubscribe me from all emails from node-red-contrib-huemagic?

I can't do this.

 

Thank you very much.
 

Best regards,
Stephanie Grandits

 
 

Gesendet: Dienstag, 11. Januar 2022 um 13:12 Uhr
Von: "Foddy" ***@***.***>
An: "Foddy/node-red-contrib-huemagic" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: Re: [Foddy/node-red-contrib-huemagic] Support for Friends of Hue Aurora dimmer (by Lutron) (#207)


 

Should be supported now :)
