### ISSUE TITLE
Christmas Animation

### ISSUE THREAD

**Issue by mattbruman** [Foddy/node-red-contrib-huemagic#208]
**Is your feature request related to a problem? Please describe.**
Using Rasta as Christmas animation but would rather have yellow be blue

**Describe the solution you'd like**
Take Rasta and change Yellow to Blue

**Describe alternatives you've considered**
Thought about making my own animation but the directions are beyond my understanding of node red at this time, still noob.

**Comment by Foddy** [comment]
I am so sorry... The latest update took way longer than originally assumed. I hope that you enjoy the included Christmas animation from the newest update in a 348 days, 2h and 55 minutes again :)
