### ISSUE TITLE
Can we receive information into Node-RED when a light colour is changed e.g. in the Hue app?

### ISSUE THREAD

**Issue by hazymat** [Foddy/node-red-contrib-huemagic#209]
I want to get information when someone changes only the COLOUR of a light e.g. in the Hue app (or from another source like Alexa).

I believe an event is only triggered in the light node when the status is changed (as per the documents, it says "Events will only be sent if the light bulb state is changed.")

Is this correct?

Is there any other way to retrieve the information when ONLY the colour is changed in the Hue app?

**Comment by Foddy** [comment]
Hi Hazymat, sure! All you need to do is to click on the light node and select the option "Skip events from node" ;)!

<img width="1340" alt="ignore" src="https://user-images.githubusercontent.com/5302050/101143731-982a7880-3617-11eb-836c-13e445e5380c.png">
