### ISSUE TITLE
Problem with additional message properties 

### ISSUE THREAD

**Issue by lucwuyts** [Foddy/node-red-contrib-huemagic#21]
Sending a message with payload a json string for the lamp
but also properties like  topic and  retain  (from an mqtt message)
makes the lamp throw an exception: 
"Error: Philips Hue: 3, resource, /lights/NaN, not available"

If i make a new message with the same json-payload, all is working ok.

**Comment by robertjochemsen** [comment]
Same for me. Behaviour for groups was even worse: somehow all my lights were set, not just that of the indicated group. Thanks to above poster I could resolve these quickly.

**Comment by Foddy** [comment]
Thank you for this report!
I was able to reproduce this error and fixed it with the just released v1.3.2.
