### ISSUE TITLE
Get light state without triggering an event

### ISSUE THREAD

**Issue by chripede** [Foddy/node-red-contrib-huemagic#210]
I have a flow like this (first line)
![image](https://user-images.githubusercontent.com/406836/101098924-10ffe500-35c4-11eb-9471-4a82c195aeac.png)

If it's not dark outside and my outside lights are on then turn them off.

My problem is that the light in the middle of the flow will trigger everything connected to it whenever any event is created by it. I send `{"state":true}` to get the state, so I cannot ignore events from it.

Is there any way I can query the state of a light without it resulting in events being sent to all other instances for that light?

**Comment by behtjes** [comment]
cut the light node out of your flow and create a flow variable for it's state with a function node and this code inside: flow.set("light", msg.payload.on);

Read the flow variable value in a switch.
if flow.light == true (on) or false (off)


![Knipsel](https://user-images.githubusercontent.com/9257476/102924526-0c776f80-4492-11eb-92ad-c8192fd67d24.JPG)

**Comment by zeysh** [comment]
Hi,

I get the idea but don't manage to do it. 

`if flow.light == true (on) or false (off)` must be in place of `On Payload` and `Off Payload` ?

![image](https://user-images.githubusercontent.com/794625/103516399-c5658300-4e70-11eb-83c8-044d5e271e58.png)



Is that possible to something like:

The nodered switch can toggle the light but also, get in input an event if the light is switched externally ?

![image](https://user-images.githubusercontent.com/794625/103516046-204aaa80-4e70-11eb-955d-bfdbec42f52c.png)

```json
[
    {
        "id": "6e716fb5.71658",
        "type": "tab",
        "label": "Flow 2"
    },
    {
        "id": "f28b9c10.487ed",
        "type": "ui_switch",
        "z": "6e716fb5.71658",
        "name": "",
        "label": "",
        "tooltip": "",
        "group": "398f3885.c7cf38",
        "order": 1,
        "width": 0,
        "height": 0,
        "passthru": false,
        "decouple": "true",
        "topic": "",
        "style": "",
        "onvalue": "{\"on\": true}",
        "onvalueType": "json",
        "onicon": "",
        "oncolor": "",
        "offvalue": "{\"on\": false}",
        "offvalueType": "json",
        "officon": "",
        "offcolor": "",
        "x": 210,
        "y": 200,
        "wires": [
            [
                "79952bd5.73a3d4"
            ]
        ],
        "info": "<font color = \"black\" i class=\"fa fa-barcode fa-2x\"> </i><font size=5 font color =\"blue\"> Scan"
    },
    {
        "id": "79952bd5.73a3d4",
        "type": "hue-light",
        "z": "6e716fb5.71658",
        "name": "",
        "bridge": "",
        "lightid": "",
        "colornamer": true,
        "skipevents": false,
        "universalevents": false,
        "x": 460,
        "y": 180,
        "wires": [
            [
                "78d1dbe8.258184"
            ]
        ]
    },
    {
        "id": "78d1dbe8.258184",
        "type": "function",
        "z": "6e716fb5.71658",
        "name": "",
        "func": "flow.set(\"light\", msg.payload.on);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "x": 700,
        "y": 200,
        "wires": [
            [
                "aa1d233b.c03f5",
                "f28b9c10.487ed"
            ]
        ]
    },
    {
        "id": "aa1d233b.c03f5",
        "type": "debug",
        "z": "6e716fb5.71658",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 920,
        "y": 200,
        "wires": []
    },
    {
        "id": "398f3885.c7cf38",
        "type": "ui_group",
        "name": "Default",
        "tab": "29b92bbd.0a4f74",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "29b92bbd.0a4f74",
        "type": "ui_tab",
        "name": "test",
        "icon": "dashboard",
        "disabled": false,
        "hidden": false
    }
]
```
Thanks for your help.

**Comment by behtjes** [comment]
@zeysh 
Try this and  you'll see how it works. Replace the timestamp with a different trigger in your flow! 
never use the blue light node to continue your flow. Make a side step.

`[{"id":"590083dd.b3f5ac","type":"hue-light","z":"6e716fb5.71658","name":"Light","bridge":"8b2389c6.6ee198","lightid":"25","colornamer":true,"skipevents":false,"x":190,"y":60,"wires":[["e7913307.48f06"]]},{"id":"e7913307.48f06","type":"function","z":"6e716fb5.71658","name":"set flow variable ","func":"flow.set(\"light\", msg.payload.on);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":400,"y":60,"wires":[[]]},{"id":"745548e4.3c8358","type":"inject","z":"6e716fb5.71658","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":160,"wires":[["17ce4f84.6df74"]]},{"id":"960d99eb.4c35e8","type":"hue-light","z":"6e716fb5.71658","name":"Light","bridge":"8b2389c6.6ee198","lightid":"25","colornamer":true,"skipevents":false,"x":550,"y":160,"wires":[["ff2081ad.072c8"]]},{"id":"17ce4f84.6df74","type":"function","z":"6e716fb5.71658","name":"switch","func":"var light=flow.get(\"light\");\n\nif(light === false){\n         msg.payload = {\n            \"brightnessLevel\": 254\n    }\n}\nelse if (light === true){\n        msg.payload = {\n            \"on\": false\n        }\n    }  \n    return msg;\n\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":390,"y":160,"wires":[["960d99eb.4c35e8","d363ab8f.bd7698"]]},{"id":"d363ab8f.bd7698","type":"debug","z":"6e716fb5.71658","name":"Continue your flow here","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":730,"y":280,"wires":[]},{"id":"ff2081ad.072c8","type":"debug","z":"6e716fb5.71658","name":"Don't continue your flow here","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"continue flow here","targetType":"msg","statusVal":"","statusType":"auto","x":780,"y":140,"wires":[]},{"id":"8b2389c6.6ee198","type":"hue-bridge","name":"Philips hue","bridge":"192.168.0.130","key":"YDSZNb8M1YWitGciLD3c-9LBx869YAhTadN0XfNk","interval":"750","disableupdates":false}]
![1](https://user-images.githubusercontent.com/9257476/103518179-96044580-4e73-11eb-9c49-20aae94186a4.JPG)
`
