### ISSUE TITLE
hue-switch stops responding after few hours

### ISSUE THREAD

**Issue by ooii** [Foddy/node-red-contrib-huemagic#211]
**Describe the bug**
I'm using node-red-contrib-huemagic with home assistant to catch events of my dimmers.
The events stop being detected by node-red-contrib-huemagic few hours after I have redeployed my flows. The node remains stuck on "waiting..." while the dimmers blinks green.

**Flow to Reproduce**
No specific flow. It happens with all my flows using these nodes.

**Expected behavior**
The node should keep receiving events.

**Screenshots**
<img width="198" alt="image" src="https://user-images.githubusercontent.com/6420072/101212748-8b3e7100-3679-11eb-961a-ce938ddceec4.png">

**Please complete the following information:**
 - Node-RED version: 1.2.5
 - NodeJS version: 
 - Device running Node-RED: Intel NUC

**Additional context**
Used with Home Assistant 0.118.4

**Comment by Foddy** [comment]
Hi, please take a look at this post: https://www.reddit.com/r/Hue/comments/7s0i0h/hue_dimmer_switch_issue/

You've probably an issue with your Hue dimmer switches, are low on battery or a weak connection to the bridge?
