### ISSUE TITLE
Limit scenes shown to selected light or group

### ISSUE THREAD

**Issue by hendersj** [Foddy/node-red-contrib-huemagic#212]
I have run into a situation where multiple lights and light groups have scenes with the same name (because they are the same configuration) - for example, I have a scene called "Energize" (one of the default scenes) that's defined for all lights and groups.

When I select the scene in the Hue Scene Node, I get a list of all of the scenes defined in my bridge, and I have to pick the right one called "Energize" or the light won't change.

It would be useful to first require a light or light group be selected, and then to present only the scenes that are defined for that light or light group.  That would lead to a lot less need to use trial and error to find the right scene definition (I would prefer to not have to use unique names in each room - if I'm using "Energize" in one room and some other name for the same scene in another room, that gets confusing as well - and requires that I remember the name per-room for my Google Assistant integration).

**Comment by My-userid** [comment]
Yes, I just had this problem. 
Couldn't understand why the scene change didn't work. Then I read this issue, and just tried everyone until it worked.

Would be nice with an easier approach :)

**Comment by Foddy** [comment]
This node has been completely redesigned in the latest version.

**Comment by hendersj** [comment]
Cool, thanks.  I'll open a ticket with a proposed enhancement, but I really like the new design.
