### ISSUE TITLE
Question: how to control the CCT light on a RGB + CCT light?

### ISSUE THREAD

**Issue by gitpower2017** [Foddy/node-red-contrib-huemagic#213]
**Describe the question**
I have a Paulneuhaus LED Pannel with RGB and CCT light.
Under ioBroker I can activate the CCT light with 2500 at "colortemeratur".
Under huemagic you can only set a maximum of 500.

How to turn on the CCL light under huemagic ?

Gruß
Lothar

**Comment by Foddy** [comment]
500 is the greatest possible value that a device can get in the "mirek" unit that HueMagic & the Philips Hue Bridge supports. Can you please try it again with the latest version?
