### ISSUE TITLE
Problems with FoH ID

### ISSUE THREAD

**Issue by damianarnold1993** [Foddy/node-red-contrib-huemagic#214]
Hi Foddy

I'm using a Friends of Hue "Feller" switch. https://online-katalog.feller.ch/kat_details.php?fnr=4120.2.S.FMI.61

I want to integrate the Friends of Hue switch into Node Red. Unfortunately the ID contains a letter. This is not accepted by Node Red ..... Can you help me?

Philips HUE API Id ":" 00: 00: 00: 00: 01: 70: 88: b0-f2 "

I try it also with 017088B0 according to the sticker on the switch

Thanks a lot

**Comment by Foddy** [comment]
Should work now :)
