### ISSUE TITLE
Status battery of a HUE Botton

### ISSUE THREAD

**Issue by Donni1966** [Foddy/node-red-contrib-huemagic#216]
**Describe the bug**
will get status of a hue botton 

may be not an error oder bug, but i want to check every Botton in my house für battery status. so i make a inject with payload status an hoply wait for information. but nothing happen. 

is there a way to geht battery status from a botton without waiting for the first press?

**Comment by Foddy** [comment]
It is possible with the latest "Hue Buttons" node now
