### ISSUE TITLE
Eine Lampe mit einem Button einschalten aber nur auf 50% helligkeit

### ISSUE THREAD

**Issue by HookHM** [Foddy/node-red-contrib-huemagic#218]
Hallo, ich habe Huemagic soweit am laufen. Ich bekomme es allerdings nicht hin, eine Lampe mit einem Button einzuschalten die sich aber nur auf 50% Helligkeit einschaltet. Ich bekomme die Lampe über den Button nur auf volle Helligkeit eingeschaltet oder eben per slider Dimmen. Kann mir bitte jemand erklären wie ich das machen muss? Danke.

**Comment by Foddy** [comment]
Please try it with this payload :)

`[{"id":"f07e62245409fac4","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"5de2459b592d28d0","type":"hue-light","z":"f07e62245409fac4","name":"Küche","bridge":"1595acc.3886b53","lightid":"11","colornamer":true,"skipevents":false,"universalevents":false,"x":310,"y":60,"wires":[["d70a334386a158d5"]]},{"id":"848c5e2edd190d12","type":"inject","z":"f07e62245409fac4","name":"50 Prozent","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"on\":true,\"brightness\":50}","payloadType":"json","x":160,"y":60,"wires":[["5de2459b592d28d0"]]},{"id":"d70a334386a158d5","type":"debug","z":"f07e62245409fac4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":470,"y":60,"wires":[]},{"id":"1595acc.3886b53","type":"hue-bridge","name":"Bridge #2","bridge":"192.168.0.100","key":"redacted","interval":"3000","disableupdates":false}]`
