### ISSUE TITLE
Create own animation 

### ISSUE THREAD

**Issue by JonasPunkt** [Foddy/node-red-contrib-huemagic#219]
Hello guys,
I am new to node red so sorry for my less knowledge. I wanted to ask how I can program my own animation and how a template for the code would be like (probably Java I guess). I want to create an animation where the light is flashing red for some seconds. Can someone please help me with this?

Thank you

**Comment by Foddy** [comment]
Please have a look at this directory: https://github.com/Foddy/node-red-contrib-huemagic/tree/master/huemagic/animations
There are lots of examples for reference.
