### ISSUE TITLE
payload.on=false does not work

### ISSUE THREAD

**Issue by robertjochemsen** [Foddy/node-red-contrib-huemagic#22]
According to info: "msg.payload values of: on boolean, True to turn on the light bulb, false to turn it off"

msg.payload.on=off results in "Error: Philips Hue: 7, invalid value, null}, for parameter, bri"

Adding a bri parameter does eliminate the error, but does not turn the light off.

Luckily, msg.payload=off does work

**Comment by oehm2007** [comment]
Hi, 
why not using : msg.payload ={"on":false}. That works perfectly in all of my flows.

**Comment by robertjochemsen** [comment]
Never mind, turns out that in my scenario there was an additional (but undefined) brightness property inside. Removing this solved the problem.

Thanks!
Robert
