### ISSUE TITLE
"Unexpected end of JSON" error when stopping not running Hue Magic animation

### ISSUE THREAD

**Issue by jensrossbach** [Foddy/node-red-contrib-huemagic#222]
**Describe the bug**
When passing a boolean `msg.payload` of `false` to Hue Magic node and there is currently no animation running, an error message "SyntaxError: Unexpected end of JSON input" is emitted. During running animation, the same input stops the animation which is okay.

**Expected behavior**
An input of `msg.payload` equal to `false` should simply be ignored, if animation is not running.

**Please complete the following information:**
 - Node-RED version: 1.2.2
 - NodeJS version: 14.15.0
 - Device running Node-RED: Raspberry Pi 3B

**Comment by Foddy** [comment]
Fixed in v4
