### ISSUE TITLE
Support for new Hue Dimmer Switch: RWL022

### ISSUE THREAD

**Issue by Cafun** [Foddy/node-red-contrib-huemagic#223]
It appears the new Hue Dimmer Switch RWL022 isn't recognised in Node-Red.
I hope you can add this to your great Hue Magic :-)

**Comment by csmale** [comment]
Definitely adding my support to this request!

**Comment by csmale** [comment]
It looks like it may need an upstream fix in huejay. I added the RWL022 to node_modules/huejay/lib/SensorModel by copying RWL021.js to RWL022.js and editing the IDs. Now the RWL022 is showing up in the list of switches in the Hue Switch node.

**Comment by domhauton** [comment]
I have created a temporary patch for this: https://gist.github.com/domhauton/fde796e7f88e3e3a8992aedc2f5f2068

**Comment by hubient** [comment]
Realy good support file. Do you think you can create a merge request to hope this makes it in to the standard?

**Comment by Foddy** [comment]
Is supported in the v4 :)
