### ISSUE TITLE
Bridge and sensors stop updating after +/- 5 minutes until flows are restarted

### ISSUE THREAD

**Issue by ErwinP** [Foddy/node-red-contrib-huemagic#227]
**Describe the bug**
My setup suddenly stopped working after several months, with no change in hardware. When I create a flow that includes motion sensors, everything works fine after deployment. However, after a short amount of time (~5 minutes), statuses are not getting updated anymore (i.e. they remain "frozen" in their current status). When I deploy a (minor) change or restart all flows, everything works again for only a short amount of time. I get no errors and all statuses remain "active" or "connected", but it just doesn't respond to changes anymore. 
Some sensors, which are also added in the Flow, control lights via the normal Hue app. Those sensors work (i.e. they turn on the light), but their status is not updated in node-red. Furthmore, those sensors are also entities in Home Assistant (which is directly connected to the Hue Bridge) and I can see them being updated. It thus seems that the problem lies with Hue Magic and/or node-red.

**Flow to Reproduce**
```
It relates to all flows that include the motion sensors. I do not have any other flows.
```

**Expected behavior**
Statuses of the motion sensors should get updated properly, or an error should be thrown when there is a problem in the connection.

**Screenshots**
Although everything is apparently connected, the status does not get updated
![error](https://user-images.githubusercontent.com/1286494/112443672-8519f080-8d4d-11eb-89e5-e06de18af0cc.png)

**Please complete the following information:**
 - Node-RED version: 1.2.9, using the official docker container
 - NodeJS version: v10.23.2
 - Device running Node-RED: Raspberry Pi 4 8GB

**Additional context**
Again, everything has worked very reliably for a few months, and my setup has not changed at all. I did notice that the Hue bridge has been automatically updated on March 17th, and although my problems have started only later on, this could perhaps be related. I have already removed hue-magic from node-red and reinstalled it, with no avail. 
I'm not sure if it is related, but my bridge cannot be detected on the network automatically. After having entered the the (fixed) IP, it is able to get the API key automatically (i.e. it gets it after the push), and when adding sensors, it is able to find the sensors and fetch the names automatically. So the problem seems to be limited to network detection of the hub only.

 The absence of any errors is disturbing, if there is anything I can do to monitor the connection more close, please tell me how to do so. 

Thanks a lot in advance!
Erwin

**Comment by FoeMaz** [comment]
I seem to have a similar problem, my motion sensors do not send messages at all - unless they are triggered by an inject node.

- Node-RED version: 1.2.9, using the official docker container
- NodeJS version: v10.23.2
- Device running Node-RED: Raspberry Pi 4 4GB

**Comment by ErwinP** [comment]
FYI, I wasn't able to resolve this issue. The only thing left for me to do was reset the hub and hope for the best, but I didn't feel much for having to reconnect all the sensors, setup my scenes, reintegrate everything with home assistant,...

I did therefore a reset of the only 2 sensors that I was using with node-red, and connected them to a cheap zigbee2mqtt dongle. Works very reliable, and I haven't used node-red since then anymore.

Hope you have more luck,
Erwin

**Comment by Foddy** [comment]
Should not happen with the v4 update

**Comment by robertvanlienden** [comment]
@Foddy here experiencing this situation.

Added HueMagic yesterday to get a Hue Button working in nodered. So far so good.

But after some minutes after deploying, HueMagic doesn't catch the button presses.

For me, the Hue Button is now simply worthless.

Running HueMagic 4.2.2.

**Comment by cwickstr** [comment]
@Foddy my experience:

Having the same problem with motion sensor and buttons. Among other things i use the lux-value from motion sensor to adjust brightness for my hue lights. After re-starting flow everything works as it should for some hours. Then at some random point in time there is no more messages sent from the nodes.

If manually querying the nodes i get the old values with old timestamp before it stopped working:

![image](https://user-images.githubusercontent.com/106800555/171803860-2f86a577-bd74-480b-bbdd-a72271b1240a.png)


Looking at the sensors in Philips hue app on the mobile phone, it shows motion activity and button presses as it should so the devices are working and communicating correctly with the bridge.

I have downgraded from 4.2.2 to 4.2.1 but there is exactly the same problem.
All buttons and other sensors are completely worthless now.

**Comment by jeggs** [comment]
Hi, I am experiencing the same issue with version 4.2.2. I am trying to catch a button press from a hue dimmer. Activity is shown in the Hue app, however after the first one or two button press after re-deploying flows huemagic stops to capture the button actions.
