### ISSUE TITLE
Love the "New" Auto Color Temperature but...

### ISSUE THREAD

**Issue by Galapagon** [Foddy/node-red-contrib-huemagic#228]
It seems the maximum warm temperature is 400. I prefer 495/500, but I don't see a way to change that, and also take advantage of this new system.

Either change the max value to 500, or allow us to configure our maximum and minimum values automatically.

How often does the automatic color temperature need to be set? Each time the bulb turns on? If it switches between available/unavailable (due to a physical power switch) exc.

Thank you!!

**Comment by tsm121** [comment]
I'd one up this too. I'm not sure if this limitation is set due to it's the only values Hue has, but for me I'd love to use this fully for my IKEA bulbs. Everything seems to work out of the box, but the min/max limit on `colorTemp` limits my usage somewhat as the bulbs can go lower than `153`.

**Comment by Foddy** [comment]
This limitation has been removed in v4 ;)
