### ISSUE TITLE
Duplicate scene names cause confusion in scene node drop down

### ISSUE THREAD

**Issue by CoryAlbrecht** [Foddy/node-red-contrib-huemagic#231]
**Is your feature request related to a problem? Please describe.**
I made my first blow in node-red yesterday, one that would use a Philips Hue dimmer switch on button to turn on the lights and set them to a Time appropriate brightness. Brighten bluish when waking up, bright and more Pure White during the day to concentrate, dimmer 2 relax in the evenings, and so on. However, I was making use of the standard Philips Hue scenes that are placed for any new group / room that you make using the Hue app. Energize, concentrate, read, relax, and so on. This meant that the scene drop down for the scene node had multiple entries that all look exactly the same. I chose once, and it turned out I didn't get them right, however I did not know that at first. The end result was that when I tap the on button on the dimmer switch this morning, it didn't set the lights to energize like I expected, it merely turn them on to the last used settings because the scene that was attempting to be applied was not for the lights in the room. It was the concentrate scene for a completely different room. 

**Describe the solution you'd like**
The drop-down containing the list of scenes should have the group they are for in parentheses, or somehow otherwise indicated to remove the confusion described above. Other processing to sort the list either alphabetically or by room name, perhaps by both would also be helpful.

**Describe alternatives you've considered**
While you can rename the individual seen in each room to be more descriptive of that room, it messes up voice recognition on Alexa and Google home and you can no longer ask them to activate concentrate, or whatever, in the room once they are renamed. Having to remember different scene names for different rooms for what is actually the very lighting profile would be confusing.

**Comment by joekeslar** [comment]
Leaving a bump for this enhancement..

**Comment by Foddy** [comment]
The scene names now also contain the linked group / zone in the newest update :)
This node works a bit differently now. Please read the README for more information
