### ISSUE TITLE
Uninstall on Home Assistant

### ISSUE THREAD

**Issue by Wolk9** [Foddy/node-red-contrib-huemagic#232]
**Describe the bug**
I would like to start over again, but I can't uninstall the node-red-contrib-huemagic palette. I get an error without a clear log.

**Flow to Reproduce**
not relevant.

**Expected behavior**
I expect the palette to be removed properly so that I can install it again.

**Screenshots**
![Schermafbeelding 2021-04-29 om 21 59 45](https://user-images.githubusercontent.com/66083478/116611343-8d5de080-a936-11eb-8a72-ae2d4f0d789d.png)
![Schermafbeelding 2021-04-29 om 21 59 56](https://user-images.githubusercontent.com/66083478/116611406-9c449300-a936-11eb-8067-bd5a78e1ac51.png)

**Please complete the following information:**
 - Node-RED version: v 1.3.3
 - NodeJS version: [...]
 - Device running Node-RED: RaspberryPi4 with Home assistant core-2021.4.6

**Additional context**
How do I uninstall the palette manually?

**Comment by Foddy** [comment]
Sorry, but this seems to be a bug in Home Assistant. I can't control within HueMagic the uninstallation process.
