### ISSUE TITLE
Please add support for Hue Dimmer Switch V2. 

### ISSUE THREAD

**Issue by dissemin8** [Foddy/node-red-contrib-huemagic#236]
When trying to add a new "Hue Switch" node to a flow I noticed it did not appear in the drop-down of available switches after I had I hit the search icon. Only my existing (v1) switch shows up in the list. 

It would be nice if support for the "Dimmer Switch v2" could be added to this great node. 

I should add that my Dimmer Switch v2 was successfully added to my setup via the Philips Hue app and is working properly, it just doesn't show up in huemagic.

**Comment by csmale** [comment]
I encountered this as well. I found and fixed the problem in huejay, but that has been basically dead for 2 years now. I think we need someone to fork and maintain huejay in order to keep huemagic going. My PR on huejay is here: https://github.com/sqmk/huejay/pull/120

**Comment by dissemin8** [comment]
I copied your file into my setup and it's working for me now.  Thank you very much :+1: 
Yes, the long term fix is to get this incorporated into huejay, hopefully your pull request will get picked up at some point. We can hope! :smiley:

**Comment by Stasfe** [comment]
hey @dissemin8 how did you got it to work? can you give me some hint pls?

**Comment by dissemin8** [comment]
> hey @dissemin8 how did you got it to work? can you give me some hint pls?

You will need to find where nodered is installed and find the huejay SensorModel directory. On my Raspberry Pi setup it is here:
/home/pi/.node-red/node_modules/huejay/lib/SensorModel 
If you can see a file named RWL021.js then you are in the right place.  
Now take the link in csmale's comment above (the one that looks like this:  sqmk/huejay#120)
Click on the "files changed" tab and copy the code into a new file named RWL022.js in the above directory.
It should look like the contents on RWL021.js but all references to RWL021 should be RWL022 instead. 

There may be other and/or better ways to achieve the same thing but that is what worked for me.

Note: if you reinstall / update hue magic at a later date, you might have to redo the above again.    
It's a bit of a hack ;)

**Comment by domhauton** [comment]
Has there been any progress on adding these directly into huemagic? The file copying doesn't work if you install node-red as a docker image via the supervisor add-on (the default install method).

**Comment by domhauton** [comment]
For those looking to backport @csmale's fix into their existing nodered installation: https://gist.github.com/domhauton/fde796e7f88e3e3a8992aedc2f5f2068

**Comment by Foddy** [comment]
Should be supported in the newly released v4 ;)
