### ISSUE TITLE
Issues with unreachable nodes

### ISSUE THREAD

**Issue by docbobo** [Foddy/node-red-contrib-huemagic#24]
I have a few nodes in my hue network that are shown as "unreachable", e.g. devices from Osram. However, there is no issue controlling them via the Hue app on my iOS devices.

With Huemagic it seems as if commands are not being sent to devices shown as "not reachable" - at least I've never been able to get such a devices activated, even though there are no issues with the Hue app.

**Comment by oehm2007** [comment]
I think thats not a issue with huemagic. Ive got lots of problems with the osrams as well with the hue bridge. The hue app sometimes says not reachable or other weired behavior. The problem with osram is the dirty programming of the zigbee protocol. I guess there is no different treating of osram devices by the hue bridge, so there will be no point of solving that issue in huemagic.

**Comment by docbobo** [comment]
While the snippet below doesn't suggest special Osram handling, it does suggest special handling for devices it deems unreachable... That even breaks a few of my regular hue devices, that - from time to time - show as unreachable although they perfectly respond to commands.

https://github.com/Foddy/node-red-contrib-huemagic/blob/8a9eb677e2559b7b6be9a9f2fd7ecd8a019c0ad0/red/hue-light.js#L135-L144

**Comment by Foddy** [comment]
I just released a new update (v1.3.2) and removed the reachability checking to increase the compatibility with other Philips Hue compatible light bulbs. I don't own any light bulbs from Osram so debugging is pretty hard 😕 …

Please reopen this issue if you still face this kind of error with your Osram light bulbs.

**Comment by lucasCFO** [comment]
Same problem with my Living Color.... Any ideas ?

**Comment by blckwngd** [comment]
same here, Hue Iris with gen2 bridge
