### ISSUE TITLE
False/true for groups and lights not working

### ISSUE THREAD

**Issue by jfreak80** [Foddy/node-red-contrib-huemagic#240]
**Describe the bug**
The groups and lights do not switch my lights. The debug tells me:
„SyntaxError: missing ) after argument list“ for the nides not working.

i can call scenes but i cannot call groups or lights/switches

**Flow to Reproduce**

**Expected behavior**
A boolean command should switch the lights or groups on/off.

**Screenshots**

**Please complete the following information:**
 - Node-RED version: 7.2.1
 - NodeJS version: 
 - Device running Node-RED: ccu3 homematic

**Additional context**
It came suddenly

**Comment by Foddy** [comment]
Fixed in v4
