### ISSUE TITLE
[Feature request]: Hue Hub API push notifications on changes

### ISSUE THREAD

**Issue by SuraMendis** [Foddy/node-red-contrib-huemagic#242]
**Is your feature request related to a problem? Please describe.**
HueMagic currently polls the Hue Hub for updates. This results in latency when one uses Hue accessories such as the motion sensor or remote switch. This is a common approach as until recently an alternate did not exist

**Describe the solution you'd like**
An undocumented new API feature has been added to the latest Hue Bridge firmware that enables callback/webhooks - this means  Hue updates can be pushed to subscribers instantly. 

**Describe alternatives you've considered**
Whilst the polling interval be reduced (i.e more frequent polling), this feels suboptimal.

**Additional context**
Note: capability is now in the **Home Assistant** Hue integration with the 2021.6 updates for an implementation reference.

**Comment by marcus-j-davies** [comment]
To add to this, The following is how one will consume the events using the none HueMagic nodes (tested)

Add a node that allows to consume multipart streams. i.e `multipart-decoder`
set the URL to `https://<IP-Of-Hue>/eventstream/clip/v2`

HTTPS is needed for this API - so ensure you ignore SSL errors in your `settings.js` file

Send the following `msg` to `multipart-decoder`

```json
 "headers": {
        "Accept": "multipart/mixed",
        "hue-application-key": "<Hue-API-Key>"
    }
```

`multipart-decoder` will now emit a payload for every event from the Hue Bridge, in real time

**Comment by dongennl** [comment]
Hi, I just got an email from Philips that the V2 API is now in early access with some documentation on the developer site. This definitely seems like the way to go! Do we need a new project?? 
Otherwise I might do something myself on Elixir, GenServer would be ideal to model the resources.

**Comment by lougreenwood** [comment]
@dongennl that would be really cool to see, however, I suspect that with the introduction of the `matter` standard (which Hue have said they will support at launch) I suspect that the core features (and maybe all features) of this package and any future push-enabled Hue package will become obsolete by a `node-red-matter` package which will allow interacting with Hue and any other `matter` devices in node red.

So maybe a new `node-red-matter` project is better place to put your effort?

**Comment by dongennl** [comment]
thanks @lougreenwood I wasn't aware of that. Let's hope!

**Comment by begner** [comment]
There is already a "library" for it:

https://github.com/homegraph/philips-hue-push-client

**Comment by dhlavaty** [comment]
@marcus-j-davies Exacly, it can be easily tested using `node-red-contrib-sse-client` with these settings:

Check your Hue Bridge IP and Application ID in your Global Configuration:

<img width="1195" alt="Screenshot 2022-01-06 at 22 24 55" src="https://user-images.githubusercontent.com/513138/148454544-ce48fdac-fd0c-4912-837e-1ef9ebc64c44.png">

And then just a simple `node-red-contrib-sse-client` example flow works nicely:
 
<img width="1236" alt="Screenshot 2022-01-06 at 22 26 42" src="https://user-images.githubusercontent.com/513138/148454845-5b70289a-c4a5-4ad0-b533-50516c6ec734.png">

**Comment by dongennl** [comment]
thanks @dhlavaty that looks amazing.

Can someone help me with the basics. I keep getting 'Error: self-signed certificate' on the test node. I know it says above to change the settings.js to ignore SSL erros, but I'm not sure how to do that.

I've added:
`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`
to settings.js for node-red (in root of my docker settings for node-red); but it doesn't work. 
I've also tried `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

I've also tried adding NODE_TLS_REJECT_UNAUTHORIZED as an env setting on my docker container. None of them work

I'm probably missing something simple, can anyone point me in the right direction?? (@marcus-j-davies ?)
Thanks!!

**Comment by marcus-j-davies** [comment]
Hi @dongennl 

The last time I tried this, I done this.
Where are you putting the env, I put mine before the export.

![image](https://user-images.githubusercontent.com/55892693/148524844-8822790d-fd4c-49e4-8602-bbaed3539d64.png)

I don't use docker or any other layer - my NR is on bare metal.

**Comment by dhlavaty** [comment]
I didn't change anything in `settings.json`. (_I'm really new to nodered - just playing with it for two days now._) There is `Reject unauthorized https requests` checkbox in `sse-client` node, that should be unchecked imho:
 
 
<img width="673" alt="Screenshot 2022-01-07 at 12 55 18" src="https://user-images.githubusercontent.com/513138/148540937-cfef5c51-a817-40f8-9173-405af9ebf2eb.png">

**Comment by dongennl** [comment]
thanks @dhlavaty unchecking 'Reject' fixed it! prob needs both settings and checkbox.

great!

**Comment by dongennl** [comment]
This works brilliantly; I did a bit of processing on the message coming out of the sse-client (I'm not good with JS, so prob can be improved):
`var arr = JSON.parse(msg.payload);

msg.processed = arr[0]["data"][0]
msg.object_id = msg.processed.id
msg.type = msg.processed.type
return msg;`

the `msg.object_id` is now the unique UUI of the button, sensor, group or light that triggered the message.
'msg.type' now gives you what sort of even it is "button", "temperature', etc.

this will allow me to use this for button triggered events in my house and I can massively reduce the polling frequency on my two hubs. Only using HueMagic now for sending commands. Great as I use a few Hue motion sensors to trigger Sonos players for ceiling speakers in my bathrooms. Now they respond more quickly and consistently as they don't have to wait for the polling interval. (which I had at 1.5 s)
Neat.

**Comment by Foddy** [comment]
Natively supported in the v4 update now ;)
Let me know what you think!

**Comment by SuraMendis** [comment]
@Foddy - thank you for the complete update and revamp of HueMagic! I've tested the button node and the new API implementation means status updates are instant! I use the Hue remote to control non-hue lights using this technique

**Comment by Foddy** [comment]
Thank you for your generous donation! :)
