### ISSUE TITLE
hue-brightness check status doesn't return anything

### ISSUE THREAD

**Issue by shnabz** [Foddy/node-red-contrib-huemagic#243]
**Describe the bug**
When injecting msg.payload="status" into the hue ambient sensor node, nothing is returned.

**Flow to Reproduce**
inject msg.payload="status" -> Hue ambient sensor -> debug

**Expected behavior**
Returns the current status of the node without taking any action

**Please complete the following information:**
 - Node-RED version: [1.3.5]
 - NodeJS version: [14.17.2]
 - Device running Node-RED: [Ubuntu 21.04 (GNU/Linux 5.11.0-25-generic x86_64)]

**Comment by shnabz** [comment]
Needed to pass json object with key "status"

**Comment by MrMiracles** [comment]
Thanks @shnabz! Had the same problem. 
For everyone who is also struggling with this, create an inject node like this:

![image](https://user-images.githubusercontent.com/56234178/130103130-b71ca637-41f2-4bcf-bfc3-e3228bd9b1cd.png)
