### ISSUE TITLE
Sending on: false turns light on

### ISSUE THREAD

**Issue by astromediaonly** [Foddy/node-red-contrib-huemagic#244]
**Describe the bug**
Im sending {"on":false,"rgb":[255,98,0],"brightness":100} to light node and it turns light on.

**Flow to Reproduce**
```
Send {"on":false,"rgb":[255,98,0],"brightness":100} as msg.payload to light node.
```

**Expected behavior**
Light should not be turned on.

**Please complete the following information:**
 - Node-RED version: v1.3.5
 - Hassio version: core-2021.7.3
 - Device running Node-RED: Raspberry pi (Raspbian GNU/Linux 10 (buster), Docker 19.03.12)

**Comment by Foddy** [comment]
Fixed in v4
