### ISSUE TITLE
msg.topic is always 0

### ISSUE THREAD

**Issue by stefan90403** [Foddy/node-red-contrib-huemagic#245]
**Describe the bug**
when i use msg.topic in universal mode to set the group id, the group id is always set to 0 

**Expected behavior**
msg.topic should set the group id

**Additional context**

In my opinion, the Problem is in this line:

var tempGroupID = (msg.topic != null && isNaN(msg.topic) == false && msg.topic.length > 0) ? parseInt(msg.topic) : config.groupid;

msg.topic is an integer and has no length. when i use it like that:

var tempGroupID = (msg.topic != null && isNaN(msg.topic) == false ) ? parseInt(msg.topic) : config.groupid;

it works for me.

**Comment by Foddy** [comment]
Fixed with v4
