### ISSUE TITLE
Nodes do not forward information in msg which is send to them.

### ISSUE THREAD

**Issue by apfffr** [Foddy/node-red-contrib-huemagic#249]
**Describe the bug**
Nodes do not forward information (msg.x) which is send to them.

E.g. the Light Node.
"Ignore node messages" is - of course - turned off.
When information is send to the node (e.g. turn on) the node emits a reponse. The node also emits a response when the light is switched externally (e.g. with hue app).
The nodes response does not contain any of the previous information, which makes it not usable in the flow.

Example usecase:
A light is switched on for 5 minutes when motion detector is activated, IF the light is currently off. If the light is already on, it just stays on and nothing happens.
So to get the current status of the light in the flow I'd like to use the status command. But as the response does not contain my previous information, in my flow I have no way to know why the response was emitted. It could also have been just an external switch of the light, e.g. light off. Which would then switch the light on and trap in an update cycle.

**Flow to Reproduce**
```
[{"id":"7134d679ffda7750","type":"tab","label":"example","disabled":false,"info":"","env":[]},{"id":"d506b2fbd6723535","type":"hue-light","z":"7134d679ffda7750","name":"Spot Licht","bridge":"ba58d77c.95ca98","lightid":"17","colornamer":true,"skipevents":false,"universalevents":false,"x":480,"y":540,"wires":[["c82a9b57ac05d255","e7c7ce395f7b7455"]]},{"id":"5d79fec9703ff5bd","type":"debug","z":"7134d679ffda7750","name":"payload","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":220,"wires":[]},{"id":"8b0fec2694dc6cca","type":"inject","z":"7134d679ffda7750","name":"","props":[{"p":"payload"},{"p":"payload2","v":"{ \"test\": true }","vt":"json"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test-topic","payload":"{ \"status\": \"\" }","payloadType":"json","x":220,"y":220,"wires":[["5d79fec9703ff5bd","1227f85c39292224"]]},{"id":"1227f85c39292224","type":"debug","z":"7134d679ffda7750","name":"payload2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload2","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":260,"wires":[]},{"id":"c82a9b57ac05d255","type":"debug","z":"7134d679ffda7750","name":"payload","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":540,"wires":[]},{"id":"b1cca690b9d89475","type":"inject","z":"7134d679ffda7750","name":"","props":[{"p":"payload"},{"p":"payload2","v":"{ \"test\": true }","vt":"json"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"test-topic","payload":"{ \"status\": \"\" }","payloadType":"json","x":220,"y":540,"wires":[["d506b2fbd6723535"]]},{"id":"e7c7ce395f7b7455","type":"debug","z":"7134d679ffda7750","name":"payload2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload2","targetType":"msg","statusVal":"","statusType":"auto","x":700,"y":580,"wires":[]},{"id":"ba58d77c.95ca98","type":"hue-bridge","name":"Philips hue","bridge":"192.168.0.103","key":"APIKEY","interval":"3000","disableupdates":false}]
```

**Expected behavior**
When the node receives input (via node-red flow), everything except the msg.payload (and maybe msg.topic) are forwarded to the response

**Screenshots**
Example of information which is injected in the node
![f1](https://user-images.githubusercontent.com/94207338/141699862-f84f5339-7bac-4afd-8d66-cb5cfd58bb6e.jpg)

The current behaviour/result
![f2b](https://user-images.githubusercontent.com/94207338/141699912-f5201c56-9293-4200-ad92-5a5175f26577.jpg)

The expected/fixed behaviour
![f3](https://user-images.githubusercontent.com/94207338/141699877-94e6a851-4ba0-4f87-b7a3-44e4ceeff9d9.jpg)

**Please complete the following information:**
 - Node-RED version: 2.1.3: Maintenance Release
 - NodeJS version: v16.13.0
 - Device running Node-RED: HP ProLiant MicroServer Gen8 G1610T / Windows Server 2016

**Comment by Foddy** [comment]
This feature is now available in v4
