### ISSUE TITLE
Transition Time and Status

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#25]
Thanks for the update!

I haven't done extensive testing but I think that if a Transition time is set (I have five seconds), then the status response will give an intermediate value for brightness, somewhere between start and target? I think this is just worthy of a note as what happens is obviously ok-ish?

Whether other parameters are affected I haven't checked but I guess they would B?

**Comment by Foddy** [comment]
Hey @lespatots,

I just published a new update which "fixed" this issue. Now HueMagic waits for the transition to finish and then sends the status.
