### ISSUE TITLE
Node-Red will not boot now with HueMagic enabled.

### ISSUE THREAD

**Issue by Jazzik777** [Foddy/node-red-contrib-huemagic#250]
**Describe the bug**

Node-Red stuck in boot loop with error message shown in screenshot.

**Flow to Reproduce**
`[{"id":"79a59468.8fa7ec","type":"tab","label":"Carolines Remote","disabled":false,"info":""},{"id":"c8dedd00.1d5bd","type":"comment","z":"79a59468.8fa7ec","name":"Caroline First Remote","info":"","x":180,"y":180,"wires":[]},{"id":"4d721a85.c7f674","type":"switch","z":"79a59468.8fa7ec","name":"button switch","property":"payload.name","propertyType":"msg","rules":[{"t":"eq","v":"On","vt":"str"},{"t":"eq","v":"Dim Up","vt":"str"},{"t":"eq","v":"Dim Down","vt":"str"},{"t":"eq","v":"Off","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":430,"y":260,"wires":[["cbb699c2.4d9738"],["24ca3500.340b3c"],["6650fb79.7cec34"],["e79bb14a.1b238"]]},{"id":"cbb699c2.4d9738","type":"switch","z":"79a59468.8fa7ec","name":"On Button","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"pressed","vt":"str"},{"t":"eq","v":"holded","vt":"str"},{"t":"eq","v":"short released","vt":"str"},{"t":"eq","v":"long released","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":660,"y":240,"wires":[[],[],["70a9e933.9e8fa8"],[]]},{"id":"24ca3500.340b3c","type":"switch","z":"79a59468.8fa7ec","name":"Dim Up","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"pressed","vt":"str"},{"t":"eq","v":"holded","vt":"str"},{"t":"eq","v":"short released","vt":"str"},{"t":"eq","v":"long released","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":660,"y":300,"wires":[[],[],["484abcf0.cf6234"],[]]},{"id":"6650fb79.7cec34","type":"switch","z":"79a59468.8fa7ec","name":"Dim Down","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"pressed","vt":"str"},{"t":"eq","v":"holded","vt":"str"},{"t":"eq","v":"short released","vt":"str"},{"t":"eq","v":"long released","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":670,"y":360,"wires":[[],[],["7362a449.c55edc"],[]]},{"id":"e79bb14a.1b238","type":"switch","z":"79a59468.8fa7ec","name":"Off Button","property":"payload.action","propertyType":"msg","rules":[{"t":"eq","v":"pressed","vt":"str"},{"t":"eq","v":"holded","vt":"str"},{"t":"eq","v":"short released","vt":"str"},{"t":"eq","v":"long released","vt":"str"}],"checkall":"true","repair":false,"outputs":4,"x":660,"y":420,"wires":[[],[],["ae148c68.5e292"],[]]},{"id":"70a9e933.9e8fa8","type":"api-call-service","z":"79a59468.8fa7ec","name":"Netflix","server":"72bb9bd3.b57314","version":3,"debugenabled":false,"service_domain":"script","service":"turn_on","entityId":"script.launch_netflix","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":810,"y":260,"wires":[[]]},{"id":"484abcf0.cf6234","type":"api-call-service","z":"79a59468.8fa7ec","name":"Iplayer","server":"72bb9bd3.b57314","version":3,"debugenabled":false,"service_domain":"script","service":"turn_on","entityId":"script.launch_iplayer","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":810,"y":320,"wires":[[]]},{"id":"7362a449.c55edc","type":"api-call-service","z":"79a59468.8fa7ec","name":"Prime","server":"72bb9bd3.b57314","version":3,"debugenabled":false,"service_domain":"script","service":"turn_on","entityId":"script.launch_prime","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":810,"y":380,"wires":[[]]},{"id":"ae148c68.5e292","type":"api-call-service","z":"79a59468.8fa7ec","name":"Youtube","server":"72bb9bd3.b57314","version":3,"debugenabled":false,"service_domain":"script","service":"turn_on","entityId":"script.launch_youtube","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":800,"y":440,"wires":[[]]},{"id":"67c830e3.016f4","type":"hue-switch","z":"79a59468.8fa7ec","name":"TV Remote","bridge":"d084f9eb.14e468","sensorid":"124","skipevents":false,"universalevents":false,"x":180,"y":220,"wires":[["4d721a85.c7f674"]]},{"id":"72bb9bd3.b57314","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30},{"id":"d084f9eb.14e468","type":"hue-bridge","name":"Philips hue","bridge":"172.16.1.4","key":"REDACTED","interval":"3000","disableupdates":false}]`

**Expected behavior**
Node-Red to boot.

**Screenshots**
![image](https://user-images.githubusercontent.com/53336917/144884073-e54eace1-993d-4ad2-9b3f-66aa945dd7b9.png)
**Please complete the following information:**
 - Node-RED version: [2.1.4]
 - Device running Node-RED: [Home Assistant Blue]

**Additional context**
All was working perfectly until Node-Red Addon updated.

**Comment by Foddy** [comment]
Please retry it with the latest version. It shouldn't produce this error again.
