### ISSUE TITLE
Scenes created by iConnectHue don’t show up after update.

### ISSUE THREAD

**Issue by andesse** [Foddy/node-red-contrib-huemagic#260]
**Describe the bug**
Just original HUE App created Scenes shown up after Update, all Scenes from iConnectHue disappeared. 

**Expected behavior**
Choosing a Scene, but it didn't show up.

**Please complete the following information:**
 - Node-RED version: RedMatic 7.2.1
 - NodeJS version: [...]
 - Device running Node-RED: Tinkerboard S

**Additional context**
I workaround the Problem by triggering the scene from the App, save it as new scene, Rename it with "1" at the end, delete the old scene, rename the scene to original name. It shows up in Node Red again

**Comment by andesse** [comment]
Thanks for making it trigger the groups / lights again with 4.0.2. Probably it was the same issue for the scenes, can't reproduce it now anymore, I copied all by hand.

If nobody has the same problem you can probably close this bug report. Thanks again, love your work!
Andreas

**Comment by Foddy** [comment]
Thanks for telling me! :)

**Comment by B0rax** [comment]
I just updated from 3.0.0 to the current release. All Scenes from iConnectHue don't show up. The groups I created are also not there, just the rooms from the official hue app...

Is there any way to fix this issue?

**Comment by andesse** [comment]
> I just updated from 3.0.0 to the current release (4.2.2).  **This issue is still there.**
> 
> All Scenes from iConnectHue don't show up. The groups (for example ambient lights which are also part of other rooms) I created are also not there, just the rooms from the official hue app...
> 
> 
> 
> Is there any way to fix this issue?
> 
> 
> 
> This is an essential feature for me.
> 
> 
> 
> NodeRed v2.2.2
> 
> 

@B0rax 
Restart the Bridge, restart node Red. Check the other open big tickets. There is a description from me how to use simple https requests to communicate with the bridge. Busy at the moment, no time to link it.
