### ISSUE TITLE
Can’t turn my light off anymore.

### ISSUE THREAD

**Issue by andesse** [Foddy/node-red-contrib-huemagic#261]
**Describe the bug**
I can't turn off lights or groups with a false. I changed all groups to the new scheme. I even made new groups with lamps. I can turn scenes on, but I can't turn anything off. A really stupid situation. My wife hates me, using an app now. 

**Flow to Reproduce**
```
[{"id":"8888888.eeeeee","type":"tab","label":"Example Flow"...}]
```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://user-images.githubusercontent.com/76150626/148709538-5d111b8b-65fa-4115-836b-02eccd8eaa1c.jpeg)

**Please complete the following information:**
 - Node-RED version: [...]
 - NodeJS version: [...]
 - Device running Node-RED: [...]

**Additional context**
Please help! I really don't want to rollback because I changed everything now already. Took me 3 hours.

**Comment by Foddy** [comment]
Hi. Do you send an empty `msg.topic` with the request to the node?
If so, please don't.

**Comment by Foddy** [comment]
Please upgrade to v4.0.2. This should be fixed there

**Comment by andesse** [comment]
Es geht nicht. Nur mit injection nodes. Kann ich auf diese email antworten und detailliert mein Problem beschreiben?

Mit freundlichen Grüßen
Andreas Strehlau

**Comment by Foddy** [comment]
Gerne!

**Comment by andesse** [comment]
Hi,

bei mir läuft im Moment fast gar nichts mehr. 
Ich muss gestehen das ich auf einer Bridge die aktuelle Beta Firmware drauf habe, bei der geht kaum was. Szenen werden teilweise nicht ausgeführt ( Node hat den Status „führt Befehl aus“ und es passiert nichts) 



Ausschalten über den Raum geht gar nicht



ich wollte mir jetzt mit ausgeschalteten Szenen helfen.. aber die Szenen hängen ja manchmal. 

Bewegungsmelder ein und ausschalten über true / false führt auch zu einem Fehler 



Auf meiner nicht Beta Bridge sieht es jetzt ganz ok aus, da hat die 4.0.3 geholfen. 
Bis vor dem Update gestern liefen beide mit der alten HueMagic einwandfrei.

Beta Firmware:


Aufgefallen ist mit das die Leuchtmittel schneller reagieren, und die neuen Integrationen gefallen mir auch. Gute Arbeit. 

Meine Frau reißt mir aber jetzt den Kopp ab, weil nix mehr funktioniert. Ich muss jetzt die App für sie einrichten. Passiert noch was mit Korrekturen am Release? Kann ich helfen? Was musst Du wissen? Ich hab Zeit und kann auch Listen mit Test bearbeiten die Du schickst. 

Wenn jetzt erst mal me Zeit lang nichts passiert, muss ich irgendwie auf die 3er Version zurückrollen. Wie geht das?
(Flows sichern, Ich habe noch alle vor dem Update, alles mit Hue löschen, huemagic deinstallieren, deployen, huemagic 3xx installieren, deployen, Flows importieren, deployen, korrekt? Nur wo bekomme ich die letzt 3xx her? Kannst du mir die schicken? Wie installiere ich diese, wenn es nicht direkt über Node Red geht? Konsole? Kenn ich mich kaum mit aus…

Was kann ich tun?

Andreas

**Comment by Foddy** [comment]
Oh, das hört sich nicht so toll an :S... Ich bin froh, dass du wenigstens ein Backup vorher aller Flows unter v3 durchgeführt hast.

Also, ein Downgrade auf die zuletzt bei dir funktionierende Version ist immer möglich, indem du im Node-RED-Ordner deiner Instanz die package.json-Datei öffnest und anschließend in den dependencies weiter unten unter HueMagic die Versionsnummer auf 3.0.0 zurücksetzt. Anschließend musst du nochmals nen ’npm install‘ in diesem Ordner durchführen, um die Änderungen sozusagen zu übernehmen. Meines Wissens nach geht das leider nicht so intuitiv direkt über die Node-RED-Oberfläche.

Dass es aber unter der v3 funktioniert hat, deutet darauf hin, dass die Bridge offenbar die neueste API-Version nicht unterstützt – was ich komisch finde, da eine Beta ja mindestens die Funktionen mitbringen sollte, die die stabile öffentliche Version schon hat.

Die andere Sache: Wie bist du auf die Beta-Firmware der Bridge gekommen? Kannst du mir eventuell auch sagen, welche Versionsnummer(n) sie hat? Ich finde leider keinerlei Informationen dazu im Netz und auch nicht im Entwicklerportal von Philips Hue?! Oder ist es eventuell eine virtuelle Bridge Simulation?

Ich denke, mit diesen Informationen würdest du mir schonmal sehr weiterhelfen. (Auch wenn ich ehrlich gesagt etwas Angst vor meiner Frau habe, wenn ich sie dann ausprobiere und dann auch uns nichts mehr geht)...

Meine (hoffentlich nicht korrekte) Vermutung ist, dass sie die aktuell als "neu" deklarierte Schnittstelle noch etwas umgebaut haben. Das Problem ist, solange ich keine Dokumentation oder Hinweise dazu im Netz finde, wüsste ich auch nicht, wie man sie jetzt dann ansprechen müsste, um auf die jeweiligen Funktionen zu kommen – was das Ganze nochmals etwas erschwert.

Andererseits könnte es aber auch daran liegen, dass sie leider einfach noch fehlerhaft ist und Befehle nicht korrekt ausführt, obwohl sie korrekt angewendet werden.

Schwieriges Thema...

**Comment by andesse** [comment]
Moin,

Ich bin in der Philips Hue Beta community. Dort kann man sich einfach anmelden. Ich hatte dadurch zb diese Spotify integration schon 2-3 Monate früher, weil es dort getestet wurde. 
Außerdem hat man in der Regel eine App Version früher. Ich bin bei der normalen App bei 4.01, benutze aber in der Regel iConnectHue. 

Die Versionsnummer der Beta Zentrale ist folgende (und sollte normalerweise Firmware mäßig weiter fortgeschritten sein als die nicht Beta)


Ich habe die Admins darum gebeten meine Zentrale downzugraden, das können die aus der Ferne, ich habe eine 2. Zentrale die nicht auf Beta läuft im Wohnzimmer bei der funktioniert die Contrib

 


Außerdem hab ich ne neue Zentrale bestellt. 
Ich richte die dann lieber bei ein als in Nodered einen Downgrade zu machen. Die Fehlerhafte lass ich als Backup liegen und werde die dann, wenn das normale Release der FW höher ist als die jetzige Beta. 

Mal sehen ob die heute antworten und downgraden… Das wäre die einfachste Lösung. 

Und erstmal vielen Dank für die coole contrib und Dein Engagement :)

Gruß 
Andreas

**Comment by andesse** [comment]
Hallo,

vielleicht meldest Du Dich auch mal bei der Beta an und holst Dur ne Bridge zum testen. 
Falls die Firmware (oder spätere), dann public gehen, die momentan Fehler verursacht, haben alle ein Problem mit der contrib

https://auth.meethue.com/u/login?state=hKFo2SB0RnhwMUZDUklrWk5vLWNMSzczVFM5cHIzZWlHbGU0bqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIDZuc2J6OC1TVUFHSVdOWkplb0gySGhOd19rMHplbExMo2NpZNkgeE9GRU42NXVQRXdwMGFNbEo2SkExQ0syc2xGeVp0R1E

Oder einfach „hue beta“ googeln 

Gruß 
Andreas

**Comment by Foddy** [comment]
Ich weiß nicht ob du da eventuell etwas verwechselst oder ich einfach nur etwas blind bin – aber ich finde leider keine Informationen zu einer Beta-Firmware der Philips Hue Bridge. Im Beta-Portal sehe ich lediglich die Beta-Apps für iOS und Android dazu?

Es macht sicherlich Sinn Betas direkt ins Visier zu nehmen – sie aber direkt zu unterstützen ist etwas schwierig, weil sich in der Regel vieles noch ändert und sie generell offenbar nicht ganz so stabil sind, wie sie es sein sollten. Sollten größere Änderungen tatsächlich geplant sein, so teilt Philips Hue das normalerweise schon Monate im Voraus mit oder geben genug Zeit nach dem Release, bevor sie die alten Versionen nicht mehr unterstützen, wie es aktuell der Fall ist mit der v1 und v2 API, die parallel laufen.

**Comment by andesse** [comment]
Sobald die Beta App drauf ist, und die bridge registriert, kommen die Beta-Firmware Updates von dem Beta Team automatisch auf die Bridge und Lampen. Man kann es nicht manuell machen.

Ich habe jetzt auch das Problem auf meiner Standart Bridge, das ich beim injizieren von z.b. brightness mit transitionTime von den Lampen immer einen Fehler bekomme. (Error: Request failed with status code 400) Das sind alte flows und hat vorher immer funktioniert. Da ich kein Experte in coding bin habe ich die Werte immer mit changed nodes gesetzt. Als ich Deinen Beispiel Flow grad installiert habe, und gesehen hab das es über JSON gesetzt wird, hab ich das mal ausprobiert. Es geht. Mein Fehler. Werde jetzt alle flows auf Function nodes umschreiben. Wieder etwas gelernt. 

Also Standard Bridge alles ok
Beta Bridge, geht nichts. 

Versuche jetzt zu recherchieren ob bei einem Factory Reset der Bridge eine alte Firmware gesetzt wird (die sich vielleicht auf der Bridge befindet) 

Wenn nicht, morgen kommt eine neue Bridge, dann wird die frisch aufgesetzt ohne Beta Firmware 

Danke für deine Zeit und Grüße 
Andreas

**Comment by andesse** [comment]
Hi Foddy, vom Foto her bist Du der Programmierer von HueMagic für Nodered, ich habe ein großes Problem, habe auch schon zwei Tickets auf. Ich hoffe ich störe nicht. 

Problem ist, das ich eine neue Beta Software auf meiner Bridge habe und keine Szenen mehr triggern kann, Error: Request failed with status 500. zudem geben Räume keine Daten mehr raus on/off. 

Ich habe mich nun selbst in die Clip API 2 rein gearbeitet, und kann von dort aus Szenen in den Räumen trigern, indem ich http request mit der Rest App mache. Mein String und Body sieht so aus.


Bei einer Lampe bekomme ich es hin. Ich kann die http request Node für scenen in Node red aber nicht benutze, da ich dort den secret key für meinen benutzter (beim Knopf drücken angelegt) nicht hinterlegen kann wie in der Rest App. 

Kann es sein das, wenn HUE die neue Firmware freigibt , was bald der Fall ist, es bei keinem mehr geht? Ich gehe stark davon aus. 

Kannst Du helfen? Wenn dich meine Nachricht nerven sollte oder Du keine Zeit hast, ignoriere es einfach. 😅 Ich versuche nur zu helfen, Gruß Andreas.
