### ISSUE TITLE
HueMagic should not use msg.topic for Hue ID's

### ISSUE THREAD

**Issue by SuraMendis** [Foddy/node-red-contrib-huemagic#262]
Issue: In Hue Magic v4, msg.topic is used to set Hue ID's (e.g Light IDs). This conflicts with the actual purpose of msg.topic which is to carry the MQTT Topic. 

For example I have a motion sensor that publishes to an MQTT broker on a certain topic when triggered. I then have a MQTT-IN node that subscribes to this topic in node-red which then turns on a HUE light. The MQTT-IN node however adds msg.topic which breaks HueMagic as its expecting msg.topic to be the light ID, instead its the MQTT subscription path. 

For example, consider an inject node (connected to a Light node) that sets
```
msg.payload = true
msg.topic = subscription/topic
```
then the Light node will not turn the Hue light On. If the msg.topic is NOT set, then the light will turn on (or off depending on the msg.payload value).

**Flow to Reproduce**
```
[
    {
        "id": "6847771bf697c318",
        "type": "inject",
        "z": "8a4fe7b8.3b06e8",
        "g": "dd39d78.f72da28",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "some_value",
        "payload": "true",
        "payloadType": "bool",
        "x": 230,
        "y": 240,
        "wires": [
            [
                "081f8b33ee779289"
            ]
        ]
    },
    {
        "id": "081f8b33ee779289",
        "type": "hue-light",
        "z": "8a4fe7b8.3b06e8",
        "g": "dd39d78.f72da28",
        "name": "Bedroom 1 ceiling",
        "bridge": "b9cc9782.ebb6c8",
        "lightid": "2c26b515-3a63-4ce1-8ee5-17020a2fe6dc",
        "colornamer": true,
        "skipevents": false,
        "initevents": false,
        "x": 760,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "b9cc9782.ebb6c8",
        "type": "hue-bridge",
        "name": "Philips hue",
        "bridge": "192.168.202.245",
        "key": "KEY REMOVED",
        "disableupdates": false
    }
]
```

**Expected behavior**
```
msg.payload = true
msg.topic = some_value
```
should cause the light to turn on (if payload = true; else off if payload = false) regardless of msg.topic. Perhaps HueMagic should not evaluate msg.topic and the ID (e.g Light ID) can be defined in another parameter such as msg.hue_id

**Screenshots**

**Please complete the following information:**
 - Node-RED version: 2.1.3
 - NodeJS version: [...]
 - Device running Node-RED: Raspberry Pi

**Additional context**
This issue might be related to the way msg.topic is used by HueMagic - however this breaks MQTT based control.

**Comment by Foddy** [comment]
Hmm.. that would be a huge change tbh.

However, the v4.0.3 update may solve your issue. From now on, nodes only take the msg.topic value as the new resource ID if an ID is missing in the configuration of the node **and** if the ID follows a correct and valid UUID pattern.

**Comment by SuraMendis** [comment]
@Foddy 4.0.3 solves this issue. The approach you've implemented is superior than my suggestion.
