### ISSUE TITLE
Group reacts to inject command but not to HmIP device

### ISSUE THREAD

**Issue by max-stockhausen** [Foddy/node-red-contrib-huemagic#263]
**Describe the bug**
I want to turn on my lights with my HomematicIP motion sensor. The sensor sends a boolean with the value "true" if it detects motion, but my lights don´t change. If I inject "true" with the inject node it works.
The same behaviour is shown on the group-node.

**Flow to Reproduce**
```
[{"id":"71b2c9e2.651f2","type":"ccu-value","z":"be5856f.1dfb628","name":"","iface":"HmIP-RF","channel":"00091BE9910A2D:1 HmIP-SMI 00091BE9910A2D:1","datapoint":"MOTION","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":300,"y":380,"wires":[["f09c8d08.8161b","1bf84487.e158ab"]]},{"id":"f09c8d08.8161b","type":"debug","z":"be5856f.1dfb628","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":870,"y":380,"wires":[]},{"id":"9c4bcc93.58644","type":"debug","z":"be5856f.1dfb628","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1120,"y":440,"wires":[]},{"id":"d3d32a70.f2899","type":"inject","z":"be5856f.1dfb628","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":410,"y":440,"wires":[["f09c8d08.8161b","1bf84487.e158ab"]]},{"id":"4037732e.a95cfc","type":"inject","z":"be5856f.1dfb628","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":410,"y":480,"wires":[["f09c8d08.8161b","1bf84487.e158ab"]]},{"id":"1bf84487.e158ab","type":"hue-light","z":"be5856f.1dfb628","name":"Vitrine Spots","bridge":"ee846f71.e72e78","lightid":"f0736e63-9b0c-4ce8-8a0e-12691ec81059","colornamer":true,"skipevents":false,"initevents":false,"x":890,"y":440,"wires":[["9c4bcc93.58644"]]},{"id":"38263145.35ea0e","type":"ccu-connection","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":false,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","tls":false,"inSecure":false,"authentication":false,"username":"","password":"","queueTimeout":"5000","queuePause":"250","contextStore":""},{"id":"ee846f71.e72e78","type":"hue-bridge","name":"hue-bridge","bridge":"192.168.1.8","key":"g5nm1c-qUMcD0q2Va5Lf4JpjWtA3k41R8bOlK1Fx","disableupdates":false}]
```

**Expected behavior**
I expect the light-node to turn on if it receives "true"

**Screenshots**

![1_s](https://user-images.githubusercontent.com/44135545/148810398-6a4ee386-9886-4a84-8c7c-2a1a0c12590b.png)

![2_s](https://user-images.githubusercontent.com/44135545/148809941-7668789f-cc86-445e-b687-633e834a8639.png)

**Please complete the following information:**
 - Node-RED version: [V1.2.9]
 - NodeJS version: [?]
 - Device running Node-RED: [CCU3]

**Additional context**
I deployed the nodes again, rebooted node-red and then rebooted the CCU.

**Comment by Foddy** [comment]
This is really weird. I unfortunately don't have a motion sensor from Homematic but I don't see any "errors" with your sensor's output.

Can you please share the whole message coming from the motion sensor? Or is it just the boolean value inside the payload?

**Comment by max-stockhausen** [comment]
It's just the boolean. I don't understand it as well...

**Comment by Foddy** [comment]
So, this is all that you get from the motion sensor?

`{ "payload": true }`

Or is there also something like:
`{ "playload": true, topic: "XXXXX" … }`

?

**Comment by andesse** [comment]
I am facing the same problem with all my Homematic wall Switches. 

I debug them, see a boolean true without a topic, I change it to a false in a change node, that is connected to a hue group, nothing happens. Light is still on.

If I send a false without a topic from an inject node it works. 

I replaced every hue node since the new update.
Before the update all flows where flawless. 

I rely just on motion sensors now in my whole apartment, hope this get fixed asap

**Comment by max-stockhausen** [comment]
You´re right. It has a topic embedded.

![3](https://user-images.githubusercontent.com/44135545/148821011-6db9a135-6595-4364-97e6-cf6e63b2d6dd.png)

**Comment by max-stockhausen** [comment]
Removing the msg.topic works. Is that the intended behaviour?
![4](https://user-images.githubusercontent.com/44135545/148823537-092ada10-6daf-4158-8ded-6af571fc1eff.png)

**Comment by Foddy** [comment]
Okay, this msg.topic thing obviously broke a lot. I've just released a little "hotfix". From now on, each node checks whether the ID in msg.topic is a valid UUID and only accepts the value if the node is not in universal mode.

Please feel free to reopen this issue, when you still face the same errors with the latest version (I hope not :P)

**Comment by andesse** [comment]
> Removing the msg.topic works. Is that the intended behaviour?
> 
> ![4](https://user-images.githubusercontent.com/44135545/148823537-092ada10-6daf-4158-8ded-6af571fc1eff.png)
> 
> 

How did you delete the topic?
Can't figure it out. Pretty sure it isn't an intended behavior, but it Is a workaround that I can practically live in my apartment

**Comment by andesse** [comment]
> > Removing the msg.topic works. Is that the intended behaviour?
> > 
> > ![4](https://user-images.githubusercontent.com/44135545/148823537-092ada10-6daf-4158-8ded-6af571fc1eff.png)
> > 
> > 
> 
> How did you delete the topic?
> Can't figure it out. Pretty sure it isn't an intended behavior, but it Is a workaround that I can practically live in my apartment 

Figured it. You move the msg.topic to nothing

**Comment by andesse** [comment]
> Removing the msg.topic works. Is that the intended behaviour?
> 
> ![4](https://user-images.githubusercontent.com/44135545/148823537-092ada10-6daf-4158-8ded-6af571fc1eff.png)
> 
> 

That works for me too, but pretty sure it isn't intended
