### ISSUE TITLE
Strange behaviour with new version

### ISSUE THREAD

**Issue by Ascarsy** [Foddy/node-red-contrib-huemagic#266]
**Describe the bug**
I have several light control flows created with a rather complicated logic. Everything worked fine until I updated to the new version 4.0.2.
Now I have very strange behaviour:
1. I have a homematic switch that changes the lights by iterating through the scnarios. (Works fine). Then I have a Switch that is supposed to turn the lights off. That does not work anymore. When I click the button (on the left) then I get exactly the same debug messages as when I click the Inject-Node. However the button does not turn off the lights, the Inject-Node does. The two debug nodes show exactly the same information regardless whether the event was triggered by the switch or the injection node.
2. I have a flow that tries to iterate through different scenarios, but I get an error message: "Error: Request failed with status code 404". That looks like page not found?! 

**Flow to Reproduce**
I have described this here with pictures: https://discourse.nodered.org/t/serious-huemagic-problem/56429

**Expected behavior**
There should be no 404 errors and the node should behave the same with the same input.

**Screenshots**
see https://discourse.nodered.org/t/serious-huemagic-problem/56429
see pictures below

**Please complete the following information:**
 - Node-RED version: 4.0.2
 - NodeJS version: v14.18.2
 - Device running Node-RED: Raspberry Pi 3 with Raspberian

**Additional context**
none
![Screenshot 2022-01-10 224939](https://user-images.githubusercontent.com/30209690/148911618-538acd1a-3091-4c59-a096-f911f6c7a897.png)
![Screenshot 2022-01-10 225402](https://user-images.githubusercontent.com/30209690/148911629-a76e6637-367f-4d38-bf43-cf81a0934bdc.png)

**Comment by Foddy** [comment]
Please upgrade to the latest version. This might fix your issue

**Comment by andesse** [comment]
> **Describe the bug**
> 
> I have several light control flows created with a rather complicated logic. Everything worked fine until I updated to the new version 4.0.2.
> 
> Now I have very strange behaviour:
> 
> 1. I have a homematic switch that changes the lights by iterating through the scnarios. (Works fine). Then I have a Switch that is supposed to turn the lights off. That does not work anymore. When I click the button (on the left) then I get exactly the same debug messages as when I click the Inject-Node. However the button does not turn off the lights, the Inject-Node does. The two debug nodes show exactly the same information regardless whether the event was triggered by the switch or the injection node.
> 
> 2. I have a flow that tries to iterate through different scenarios, but I get an error message: "Error: Request failed with status code 404". That looks like page not found?! 
> 
> 
> 
> **Flow to Reproduce**
> 
> I have described this here with pictures: https://discourse.nodered.org/t/serious-huemagic-problem/56429
> 
> 
> 
> **Expected behavior**
> 
> There should be no 404 errors and the node should behave the same with the same input.
> 
> 
> 
> **Screenshots**
> 
> see https://discourse.nodered.org/t/serious-huemagic-problem/56429
> 
> see pictures below
> 
> 
> 
> **Please complete the following information:**
> 
>  - Node-RED version: 4.0.2
> 
>  - NodeJS version: v14.18.2
> 
>  - Device running Node-RED: Raspberry Pi 3 with Raspberian
> 
> 
> 
> **Additional context**
> 
> none
> 
> ![Screenshot 2022-01-10 224939](https://user-images.githubusercontent.com/30209690/148911618-538acd1a-3091-4c59-a096-f911f6c7a897.png)
> 
> ![Screenshot 2022-01-10 225402](https://user-images.githubusercontent.com/30209690/148911629-a76e6637-367f-4d38-bf43-cf81a0934bdc.png)
> 
> 
> 
> 

are you running HUE Beta community Firmware? I do, and have very similar issues.

**Comment by Ascarsy** [comment]
I have found the problem. Somehow my HUE Bridge does not update to the required firmware, so HueMagic 4.x ist not valid anymore. I have downgraded to 3.0.0 and that works just fine. It is a strange behaviour though.
Thanx for the input and help!
