### ISSUE TITLE
4.0.3 "fetch" command results are always empty

### ISSUE THREAD

**Issue by begner** [Foddy/node-red-contrib-huemagic#267]
**Description**
Sending Command "fetch" to a "Hue Bridge" node always results in an empty array. (no matter which data to fetch (groups, sensors, lights, scenes...)

**Flow to Reproduce**
```
[{"id":"c6f55db5099d4b58","type":"hue-bridge-node","z":"504917ce2da1f7ee","name":"","bridge":"24cc2049.752bc","autoupdates":false,"skipglobalevents":false,"initevents":false,"x":510,"y":1160,"wires":[["3596ecbf7f4ae22c"]]},{"id":"3596ecbf7f4ae22c","type":"debug","z":"504917ce2da1f7ee","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":670,"y":1160,"wires":[]},{"id":"efe44d84d393323f","type":"inject","z":"504917ce2da1f7ee","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"{\"fetch\":\"groups\"}","payloadType":"json","x":290,"y":1160,"wires":[["c6f55db5099d4b58"]]}]
```

**Expected behavior**
The Hue Bridge Node should return a list of all groups/lights/scenes/sensors on fetch commands (as in previous versions).

**Screenshots**
Response of previous Versions of HueMagic
![image](https://user-images.githubusercontent.com/5068180/148923710-9d77cc5d-11d4-4a53-ad57-ef746d764279.png)

Response of 4.0.3
![image](https://user-images.githubusercontent.com/5068180/148923821-9caa1830-fd24-42e7-86b8-d17d8288373e.png)

 - Node-RED version: 2.1.4
 - NodeJS version: v14.18.2
 - Device running Node-RED: Docker Container (nodered/node-red) on a RaPi4

**Comment by Foddy** [comment]
Please take a closer look to the documentation. The available fetch commands have changed in the v4: https://github.com/Foddy/node-red-contrib-huemagic#get-all-devices-and-resources

**Comment by begner** [comment]
Hey foddy - you're totally right. But the new commands dont help me either.

i cant determine which light is in which group (i got this info with the v3-groups command).
i could not access any scene data in any case.

background: My implementation in node red was completely dynamic. I read the group -> light mapping and the matching scenes from the bridge and used that data in my flow. This is impossible now.

should i add this functionality (i guess thats lost with the huejay removal) or do you got other plans for that kind of "meta information"?

**Comment by aL1aL7** [comment]
Hi,
is there an alternative way to fetch all scenes and groups?
I need these data also and it was very easy at the old version with the fetch command

**Comment by bjschuit** [comment]
+1 would also like to have fetch working again to get a list of all scenes. I've built a flow that loops through all scenes after the press of a button, so I can easily swap it with a simple physical button.
