### ISSUE TITLE
not able to pair to bridges at the same time with control light an plugin. 

### ISSUE THREAD

**Issue by Donni1966** [Foddy/node-red-contrib-huemagic#268]
**Describe the bug**
have two bridges in version 1949107040, but can only pair one of them to control lights and so on. 

**Flow to Reproduce**
no flow a example 

**Expected behavior**
if i pair a bridge ... geht userid per button press this bridge works fine. if i pair the second bridge the first one read data, an you see list of objects - but no control. you get errors like 404 oder nothing- 

if you relink the 1. Bridge the second one are not able to control lights. 

how i can go back to 3.0?

**Comment by andesse** [comment]
Did you add a second profile for the second bridge?

**Comment by Foddy** [comment]
Hm. Interesting behaviour. I will take a look at this the next days. In the meantime, if you want to downgrade, you need to open the nodered folder on your device and change the version to 3.0.0 in your package.json file inside the folder.

After that run `npm install` to actually perform the downgrade.

**Comment by Donni1966** [comment]
> Did you add a second profile for the second bridge?

Yes. I do.

**Comment by Donni1966** [comment]
> Hm. Interesting behaviour. I will take a look at this the next days. In the meantime, if you want to downgrade, you need to open the nodered folder on your device and change the version to 3.0.0 in your package.json file inside the folder.
> 
> 
> 
> After that run `npm install` to actually perform the downgrade.

I install with @v3.0.0 at the end.  

I hope this works. Have tobtest it later. 

If you need help logs or something let me know. I can because betatester.

**Comment by Donni1966** [comment]
finish test - all nodes run now again.
