### ISSUE TITLE
Nothing is working... again 

### ISSUE THREAD

**Issue by andesse** [Foddy/node-red-contrib-huemagic#269]
**Describe the bug**
Never touch a running system. After everything seemed to be ok, I facing the next problem. I really wanna downgrade to 3.xx soon...

**Flow to Reproduce**
Screenshot added

**Expected behavior**
Light turns on with a function node, after it got turned off with a boolean false.

**Screenshots**
![image](https://user-images.githubusercontent.com/76150626/149027115-7d2e1bc6-9d4a-4347-9848-731b6a35a3d9.jpeg)

**Please complete the following information:**
 - Node-RED version: all good
 - NodeJS version: all dood
 - Device running Node-RED: Tinkerboard S

**Additional context**
When I inject the function node to a light node I get the debug message that the light is "soft off". I turned it out with a boolean false before, inject node. I can't turn it on anymore. Even with a true inject node it isn't possible. I need to use my app to turn it on.
This is my non beta hue bridge faceing this error. 

Also some group / lamp nodes give my the 404 debug message sometimes. I change back and forth the selected group, deploy, change the correct group, deploy, and it works "for some time" then again until it isn't working anymore. 

Also the motion sensors sometimes doesn't accept a true / false, and give an error message back: "TypeError: Cannot read property 'active' of undefined" I do the same, chose another sensor, deploy, choose the correct sensor, deploy... and it works for some time again.

This situation is more than confusing at the moment. I considering to downgrade, even I appreciate the work that went into this contrib, I like that everything is faster, but at this moment it isn't useful... :(

**Comment by andesse** [comment]
Ok... I was brave, deleted around 100 huemagic nodes in my flows, went on the Philips Hue Account website, removed the permissions for node red, deleted the accounts in node red, deinstalled the whole contrib, did a reboot and installed the contrib again. Now I started to add everything again, FRESH room by room. 

I don't want to use a backup, to avoid importing an error doing this. 

2.5 rooms are setup now and it seems to work.

@Foddy you can close it

**Comment by Foddy** [comment]
Oh, I am sorry for that..

I am pretty sure that I have to fix a lot of new code in the v4 for so many different setups... So, thanks for sharing your experiences and information about sour setup and trying out the v4 that early. This helps a lot to prevent and fix this issues.

Still curious to know what caused these errors on your "normal" bridge 🤨...
