### ISSUE TITLE
Suppress "Checking for Hue Bridge firmware updates…" in node-red-log

### ISSUE THREAD

**Issue by djiwondee** [Foddy/node-red-contrib-huemagic#271]
Thank you very much for the recent update 4.x. Migration to this went smooth in my setup! 

After running this for a while I've found out  there is an info message written to the node-red-log each five minutes:

```
...
12 Jan 12:24:57 - [info] [hue-bridge:Philips hue II] Checking for Hue Bridge firmware updates…
12 Jan 12:29:58 - [info] [hue-bridge:Philips hue II] Checking for Hue Bridge firmware updates…
12 Jan 12:34:58 - [info] [hue-bridge:Philips hue II] Checking for Hue Bridge firmware updates…
...
```
**Describe the solution you'd like**
I have recognized there is a checkbox in the bridge node configuration property dialog
<img width="348" alt="image" src="https://user-images.githubusercontent.com/37173958/149133416-2f6b333b-dfad-43b3-981e-d1992397c02f.png">
Guess the intention is, if this is switched off, the check for update shouldn't be performed.

Please suppress the info msg mentioned above, at least in case this property is switched _off_. We all know which update cadence is provided be Philips. So it is not really helpful having  so much useless information documented in the log.

**Additional context**
I'm running a rsyslog service and the log size increases over the time to much witch less meaningful information.

**Comment by Foddy** [comment]
You are right, I will suppress this information completely in the next version. For now what I meant with fixed is, that HueMagic will not output this message that frequently as on the versions before.
