### ISSUE TITLE
Cannot connect two Hue Bridges

### ISSUE THREAD

**Issue by gerdschadler** [Foddy/node-red-contrib-huemagic#272]
**Describe the bug**
I am not able to setup two hue bridges - the config nodes are ok - but on any node it does not take inot account the selection of the bridge in the in individual nodes.

**Comment by Foddy** [comment]
Can you please try it out again with the 4.0.4?

**Comment by Donni1966** [comment]
hi, 

in the first test it look like that all works fine. 

thanx a lot - i love this plugin an will spent some money next time per PayPal. 

One question: 
with this nodes: 
`[
    {
        "id": "3884b871.c06958",
        "type": "hue-group",
        "z": "4017e5c7.708454",
        "g": "85bd5806753239e4",
        "name": "Terrasse Garten",
        "bridge": "63d7db56.1e617c",
        "groupid": "5061ea86-c641-4ff3-9325-b3be5ad0e909",
        "skipevents": false,
        "initevents": false,
        "x": 1070,
        "y": 735,
        "wires": [
            [
                "4b92ee7a.66e6e8",
                "e44ae8e9.8b92e8",
                "e6e8f84e.d07538",
                "4eab36f1.8ba758"
            ]
        ]
    },
    {
        "id": "4eab36f1.8ba758",
        "type": "function",
        "z": "4017e5c7.708454",
        "g": "85bd5806753239e4",
        "name": "Abfrage Helligkeit Sonneninsel",
        "func": "\nif (msg.payload.on==true){\n    if(msg.payload.brightness<=10){\n        msg.payload=3;\n        return [msg];\n    }\n    if(msg.payload.brightness<=30){\n        msg.payload=2;\n        return [msg];\n    }\n    if(msg.payload.brightness>30){\n        msg.payload=0;\n        return [msg];\n    }\n} \nmsg.payload=1;\nreturn [msg];",
        "outputs": 2,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1320,
        "y": 715,
        "wires": [
            [
                "f5704047.15586"
            ],
            []
        ]
    },
    {
        "id": "4b92ee7a.66e6e8",
        "type": "function",
        "z": "4017e5c7.708454",
        "g": "85bd5806753239e4",
        "name": "Fake Lampe Gartenlich erstellen",
        "func": "if (msg.payload.on == true){\n    msg.payload = {\"On\":1, \"Brightness\":msg.payload.brightness};\n}else {\n    msg.payload = {\"On\":0, \"Brightness\":msg.payload.brightness};\n}\nreturn [msg];\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1320,
        "y": 755,
        "wires": [
            [
                "88683a69a88fde3e"
            ]
        ],
        "icon": "node-red/swap.svg"
    },
    {
        "id": "63d7db56.1e617c",
        "type": "hue-bridge",
        "name": "HUE Garten",
        "bridge": "192.168.2.70",
        "key": "cAPkeqp1jX9YdYtvPjkRz0U4IM5kQv1SCHjN-j8G",
        "disableupdates": false
    }
]`

i get the brightness form the lamps in a group an send it out. This not work at the moment. So is there a way to get the acutely brightness from  a group oder a room with lamps?

**Comment by krisxxxx** [comment]
Hi,
I had the same problem. Now it seems to work. Thanks

**Comment by Foddy** [comment]
Nice! Thanks for testing it out guys. There are so many different setups with this library, it’s nearly impossible for me to test every case on my own to find possible issues in advance

**Comment by Foddy** [comment]
@Donni1966 Thanks for you donation :)! Unfortunately it's not possible with the newest API from Philips to get the current brightness from a Group / Zone.

The old API had this feature, now they removed it because groups / zones can contain different kind of devices besides lights. Not every device inside a group for example has the capabilities to set a brightness, different colors...

If they would, I also don't see what kind of values the bridge should output for the group if one light is set to 100% brightness and yellow, when another is set to 50% blue.

Should it be 75% brightness and green then? :S

I would suggest you to put a light node right after the group node where you know that it is linked with the group and get the brightness value from this light for the whole group, if you still need to access this value. It luckily happens all in real time without any overhead to your bridge when using multiple, additional nodes with the v4, so maybe this is a solution for you (and others relying to this previous features)?

**Comment by gerdschadler** [comment]
Hello - it does not work for me.

Bridge seems to be connected, but trun off/on lights ends in an error
... "Error:
Request failed with status code 503"
(on the node it shows "executing command"



Am Mi., 12. Jan. 2022 um 19:20 Uhr schrieb Foddy ***@***.***>:

**Comment by gerdschadler** [comment]
Hello - it does not work for me.
Bridge seems to be connected, but trun off/on lights ends in an error ... "Error: Request failed with status code 503"(on the node it shows "executing command"

**Comment by Donni1966** [comment]
> node it shows "executing command"

in my case i relink the bridge a second time.

**Comment by Donni1966** [comment]
> I would suggest you to put a light node right after the group node where you know that it is linked with the group and get the brightness value from this light for the whole group, if you still need to access this value. It luckily happens all in real time without any overhead to your bridge when using multiple, additional nodes with the v4, so maybe this is a solution for you (and others relying to this previous features)?

Jes, absolut no problem. i only ask for the brightness. in my case it is enough to read the brightness from one lamp of the room, so i have the group brightness thanx.
