### ISSUE TITLE
Only brightness doesn’t switch light on

### ISSUE THREAD

**Issue by Missenberger79** [Foddy/node-red-contrib-huemagic#273]
Hi,

since update to 4.0.x my flows doesn’t work anymore.

before only with payload brightness it works to switch the light on and set the brightness to the value.

can you fix this or I must change all my functions.

Thank for your great work.

**Comment by Foddy** [comment]
Hi,

what is your current HueMagic version? Do you have the Hue Beta Firmware on your bridge or the latest stable Hue Bridge firmware?

Did you read the [upgrade note](https://github.com/Foddy/node-red-contrib-huemagic#v403) in the README before upgrading?

**Comment by Missenberger79** [comment]
4.0.3 huemagic 
1949107040 from 08.01.2022 an the bridge

yes i read the note. 
i Update the device from the list.

I don’t have problem with switch and brightness. 
brightness value “0” switch off the light.
But f.e. “25” alone doesn’t switch on the light. 
after I switch on I can increase and decreases the brightness.

**Comment by Foddy** [comment]
Oh… I am sorry. My response was for another issue :D
Bu anyways, thanks for the information. This is a correct and new behaviour in the v4. If you just set the brightness parameter without a `{ payload: { on: true }}`, the new brightness state will be saved until you turn on the light next time.

So you have to also turn the light on now with your brightness request like this:

`{ payload: { on: true, brightness: 25 }}`
