### ISSUE TITLE
Error - [red] Uncaught Exception with v4.0.4

### ISSUE THREAD

**Issue by ZEi20T** [Foddy/node-red-contrib-huemagic#278]
**Describe the bug**
NR fails to load with version huemagic 4.0.4

it crashes then reloads NR and loops this error

14 Jan 10:36:18 - [info] [hue-bridge:Philips hue] Initializing the bridge (192.168.10.16)…
[10:36:18] INFO: Starting NGinx...
14 Jan 10:36:19 - [red] Uncaught Exception:
14 Jan 10:36:19 - [error] TypeError: Cannot read properties of undefined (reading 'on')
    at HueGroup.applyCommands (/config/node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:320:46)
    at HueGroup._inputCallback (/config/node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-group.js:95:54)
    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:207:26
    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:149:13)
    at HueGroup.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:199:11)
    at HueGroup.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:183:25)
    at HueGroup.Node.receive (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:482:10)
    at Immediate.<anonymous> (/opt/node_modules/@node-red/runtime/lib/flows/Flow.js:814:52)
    at processImmediate (node:internal/timers:464:21)

 - Node-RED version: 2.1.5
 - Device running Node-RED: HA Supervised

**Additional context**
appears to works fine on huemagic 3.0.0

not too sure if a bug or if its my config

thank you

**Comment by philosoma** [comment]
I am also getting this error on 2.1.4 and 2.1.5. So far all I have to do to trigger it is join the Hub via API key and restart Node-RED. Everything works fine until its restarted.

**Comment by rvanbaalen** [comment]
I can't use any light node due to this bug.

**Comment by rvanbaalen** [comment]
Did some more digging. My error is happening on this line

https://github.com/Foddy/node-red-contrib-huemagic/blob/master/huemagic/hue-light.js#L349

I injected some console logs and these are the results:

```
msg {
  topic: '',
  payload: false,
  _msgid: '9355e346ea8b1f76',
  _event: 'node:a26c693eea765b47'
}

currentState false

patchObject {}
```

**Comment by Foddy** [comment]
Can you guys please try to reconfigure your Hue Bridge configuration and try it again?

**Comment by rvanbaalen** [comment]
I did. I removed this plugin, went over all my flows and removed all Hue nodes, reinstalled and reconfigured the config node. Instant crash.

**Comment by shawnli87** [comment]
I have the same issue here. I'm running Node-RED 10.3.2 on HA Supervised. I can replicate the issue on all v4.0.0+. Unfortunately, v3.0.0 is unable to communicate with my bridge.

The issue only occurs for me when I have a "Hue Light" node on an enabled flow. I have "Hue Motion" nodes on a flow, but they are not causing the crash to occur. As a workaround, I am currently using an http request node to send commands directly to the Hue API.

**Comment by rvanbaalen** [comment]
@Foddy is there anything I can do/debug that will help you pinpoint this issue? Any tests I can do for you? I'd like to assist you to get this resolved asap.

**Comment by Foddy** [comment]
Hmm very strange, as I am unable to reproduce this. This must be a flow related issue. Do you fire an event right after you deploy a flow to a HueMagic node?

**Comment by rvanbaalen** [comment]
Let me look into that. I do know that I have one `node-red-contrib-light-scheduler` node that is talking to one of my Hue Switches to turn it on and off on a schedule. Let me strip it down to the bare basics. I'll comment when I'm done.

**Comment by Foddy** [comment]
Nice! I think that caused the error for the others as well. I just released a new update. The command is still not executed until HueMagic is connected to the bridge, but at least a fatal error (Node-RED restart) is no longer produced and a notification message is issued.

**Comment by rvanbaalen** [comment]
That's awesome, @Foddy! I'll update right away and give it a try without the delay node inbetween.

**Comment by rvanbaalen** [comment]
That does the trick. I do get the following message now:

```
"The light in not yet available. Please wait for the bridge to connect before sending any command."
```

That's a lot better than an indefinitely rebooting NodeRED ;-)

**Comment by Foddy** [comment]
Haha, yeah I think so too! :D
Please feel free to reopen this issue if the error still occurs on your side @ZEi20T / @philosoma / @shawnli87.
