### ISSUE TITLE
Cannot action lights or groups, scenes are fine

### ISSUE THREAD

**Issue by vBiggles** [Foddy/node-red-contrib-huemagic#28]
Just loaded huemagic up today to try it out.  v1.3.4.

I can action scenes, but cannot action lights or groups.

When node-red restarts the following error is thrown highlighting hue-group as containing a syntax error.  I ran a validator over the code and couldn't find the error in the syntax.  (NB: ** added by me)

Any ideas?

Jan 18 22:38:36 thecollector Node-RED[1479]: 18 Jan 22:38:36 - [info] Linux 4.9.59-v7+ arm LE
Jan 18 22:38:37 thecollector Node-RED[1479]: 18 Jan 22:38:37 - [info] Loading palette nodes
Jan 18 22:38:41 thecollector Node-RED[1479]: 18 Jan 22:38:41 - [info] Settings file  : /home/pi/.node-red/settings.js
Jan 18 22:38:41 thecollector Node-RED[1479]: 18 Jan 22:38:41 - [info] User directory : /home/pi/.node-red
Jan 18 22:38:41 thecollector Node-RED[1479]: 18 Jan 22:38:41 - [info] Flows file     : /home/pi/.node-red/flows_thecollector.json
Jan 18 22:38:41 thecollector Node-RED[1479]: 18 Jan 22:38:41 - [info] Server now running at http://127.0.0.1:1880/
Jan 18 22:38:41 thecollector Node-RED[1479]: 18 Jan 22:38:41 - [info] Starting flows
**Jan 18 22:38:42 thecollector Node-RED[1479]: 18 Jan 22:38:42 - [error] [hue-group:7ba1b057.dea88] SyntaxError: Unexpected token =**
Jan 18 22:38:42 thecollector Node-RED[1479]: 18 Jan 22:38:42 - [info] Started flows
Jan 18 22:38:42 thecollector Node-RED[1479]: 18 Jan 22:38:42 - [info] [mqtt-broker:650c0fee.7aed4] Connected to broker: mqtt://localhost:1883

**Comment by vBiggles** [comment]
My bad!!!  The error is on my side.  There must've been a dependancy in the npm's as once I updated the npm's problem went away.  thanks for your awesome work!

**Comment by Flup23** [comment]
i just downloaded 1.3.4 and i have the same **"SyntaxError: Unexpected token ="** Problem like vBiggles. 

I only can action scenes, but no lights and groups. 
I updated NPM to Version 5.6.0, but doesn't help.
Can you or vBiggles please help me with the Problem and describe your solution? I'm not so firm with Linux, NPM and the details of Node-Red 

thx
