### ISSUE TITLE
Hue dimmer is missing.

### ISSUE THREAD

**Issue by bergjet** [Foddy/node-red-contrib-huemagic#280]
Version: 4.0.4
Hue dimmer is missing.

**Comment by Foddy** [comment]
Please read the version hint in the README of the v4.

**Comment by bergjet** [comment]
When button 1 is pressed, 2 msg.payload.
1. msg.payload.action initial_press
2. msg.payload.action short_release

For a long press on a key
msg.payload.action initial_press
msg.payload.action repeat

There will be a msg.payload every second until the key is released.

**Comment by Foddy** [comment]
This is indeed the behaviour of the new CLIP/V2 API by Philips Hue. The initial press is always fired by the bridge. You may want to respond only to this message and filter out the other ones.

HueMagic will only fire out a message when it differs from the previous one.
