### ISSUE TITLE
Using two Hue bridges error

### ISSUE THREAD

**Issue by MBombeck** [Foddy/node-red-contrib-huemagic#299]
**Describe the bug**
My first hue bridge was completely full so I tried to add a second one (both v2) to shift some load to it. After installing the bridge via Hue App and adding some lights and scenes to it I added it to Huemagic without a problem. When I try to discover lights or scenes via light or scene node i get the error "Something went wrong. Please retry" (see error log). Using the bridge directly with Home Assistant or official Hue App works fine.
If I remove the new bridge, then everything works again without any problems. 

**Error Log:**
```
...
24 Jan 22:42:16 - [red] Uncaught Exception:
24 Jan 22:42:16 - [error] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at /config/node-red/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js:807:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022/01/24 22:42:16 [error] 544#544: *1213 upstream prematurely closed connection while reading response header from upstream, client: 10.100.0.179, server: a0d7b954-nodered, request: "GET /hue/resources?bridge=10.0.1.176&key=[myApiKeyWasHere]&type=scene HTTP/1.1", upstream: "http://127.0.0.1:46836/hue/resources?bridge=10.0.1.176&key=[myApiKeyWasHere]&type=scene", host: "10.0.1.205:1880", referrer: "http://10.0.1.205:1880/"
...
```
**Please complete the following information:**
 - Node-RED version: 10.3.4
 - NodeJS version: 16.13.2-r0
 - Device running Node-RED: Home Assistant / hassio
 - Hue Bridge(BSB002): 1.49.1949107040

**Comment by MBombeck** [comment]
I have not changed anything but since yesterday works.

**Comment by Foddy** [comment]
I like those kind of issues 😄
