### ISSUE TITLE
No nodes after installing

### ISSUE THREAD

**Issue by lucwuyts** [Foddy/node-red-contrib-huemagic#3]
Hi, i've installed huemagic, but nothing shows in the flow designer.
This is on windows
npm 2.15.9
node 4.6.1

After restarting node-red, i see this in the logfile

9 Sep 03:40:29 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
19 Sep 03:40:29 - [warn] [tail] Not currently supported on Windows.
19 Sep 03:40:29 - [warn] [hue-bridge] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-light] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-group] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-scene] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-motion] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-temperature] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
19 Sep 03:40:29 - [warn] [hue-brightness] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by Foddy** [comment]
Sorry for the inconveniences… I just released v1.1.1 of HueMagic which should fix this kind of errors/warns on your Node.js environment. For now I will close this issue. If you still have problems after the update please open a new issue thread. Thanks!
