### ISSUE TITLE
Can't control full group if one light in group is on.  

### ISSUE THREAD

**Issue by andy99288** [Foddy/node-red-contrib-huemagic#303]
Could someone please confirm for me this is expected behavior?  I've been having trouble getting my lights to work in 4 like they previously did in 3.   I'm thinking the new Philips API just doesn't work the same.  

Say I have 4 floor lamps in a group.  I turn one of them on.  The group reports as on.   Now once that one light in the group is on, I have no way to control the group.  Sending an on command to the group does nothing, possibly because it already considers itself on.  Brightness, color, and colortemp controls to the group only affect that one light that is already on.  The only way I can find to turn on all 4 floor lamps via group control is to first turn off the one I turned on.  

I'm hoping I'm an idiot and have missed something, because I'm having trouble finding a work around for this in my automations / dashboards.  Good new is, I think this is my last hurdle in upgrading to 4. 

Thank you!

**Comment by Foddy** [comment]
I am sorry, this is unfortunately a new limitation from the new Philips API (at least at the moment). You could use the toggle command to first turn the one light off and then turn them all on again with another toggle command or a custom function to determine if the group (or one light inside) is on to then automatically fire the off command and the on command right after.
