### ISSUE TITLE
Inputs and outputs reversed on palette

### ISSUE THREAD

**Issue by Plloi** [Foddy/node-red-contrib-huemagic#32]
![image](https://user-images.githubusercontent.com/2743514/35413372-36fbf108-01ed-11e8-863b-89e7ab46d233.png)

**Comment by Foddy** [comment]
I think that is quite a matter of opinion. In NodeRED input nodes are nodes that expect a particular command. By contrast, output nodes primarily provide information. Therefore this subdivision.

But I can understand that this may be a bit confusing.
