### ISSUE TITLE
Problems in combination with Dashboard Widgets

### ISSUE THREAD

**Issue by Stinky78** [Foddy/node-red-contrib-huemagic#33]
Hi there,

i am fumbling around with this since days and i assume i am making it too complicated and lost myself somewhere. I wanted to control my HUE lights with via the node-red dashboard ui. Its a a color lamp and i want to use the switch, the slider and the color picker. I have splitted the payload, i have joined the payload and i got it working with switch and slider, but no chance with color somehow. Now my flow is so HUGE that it looks ridiculous. I would be very grateful if you could give me a hint somehow what i am doing wrong and how it can be done much much simpler. I am sure its possible.

Thank you! Much appreciated!

<deleted>

**Comment by lespatots** [comment]
Hi,

Thought I would import your flow but it won’t import for me. Doesn’t even give me the opportunity after I paste it to the clipboard.

Could you check and re-post and I have time to  have a look.

Regards

Richard

**Comment by Stinky78** [comment]
Hi Richard,

sorry for messing it up. Here you go: [https://pastebin.com/VK3tQ866](https://pastebin.com/VK3tQ866)

hope this works better. thanks for your help!!!

bye
S

**Comment by lespatots** [comment]
Hi,

I loaded it and can do what you say works. However, I get a stream of error messages

29/01/2018, 12:19:09node: f45df4a9.8dfb8 <http://192.168.1.113:1880/#>
msg : error
"Error: Pool is closed.”

and the colour picker isn’t doing anything and there is no report out of the debug node.

Is that what you get?

Richard

**Comment by Stinky78** [comment]
i dont get the "Error: Pool is closed.” error message, but that the color picker isn't working is exactly the problem what this is all about.

**Comment by lespatots** [comment]
Hi,

I restarted and that error has gone.

Here us a debug of setting a colour

29/01/2018, 17:41:48node: from join <http://192.168.1.113:1880/#>
on : msg : Object
object
payload: object
topic: "on"
socketid: "ZkgwHevDaz2J2Sh-AAAC"
_msgid: "c4a13c15.a62d4"
29/01/2018, 17:41:55node: from join <http://192.168.1.113:1880/#>
on : msg : Object
object
payload: object
topic: "on"
socketid: "ZkgwHevDaz2J2Sh-AAAC"
_msgid: "748e831b.78e47c"
29/01/2018, 17:42:13node: from picker <http://192.168.1.113:1880/#>
hex : msg.payload : string[6]
"000000"
29/01/2018, 17:42:13node: from join <http://192.168.1.113:1880/#>
hex : msg : Object
object
payload: object
hex: "000000"
on: false
brightness: 100
topic: "hex"
socketid: "VwWbgHjY8Z8yjRZcAAAD"
_msgid: “aaa9bf05.55ee6"

The light is Blue at present (it seems to default to that) and the colour wheel setting is often centered on Black which likely is  0000000. The debug from ‘picker’ should be a command to the light but just zero’s can’t work? My best guess is that the hex colour isn’t being extracted correctly when the light updates its status and that Hex 000000 has no impact on the existing colour setting?

Does that help. Unfortunately I don’t set my lights individually and I use preset scenes that I store in a database (I have three hubs and some other devices in a scene)

I have often got “input error” from the light setting and that comes from the third such error check in the JS, just before SEND LIGHT STATUS.

Sorry can’t help any more. Let me know if you get it solved

R

**Comment by Stinky78** [comment]
That were exactly my findings. I am sure i am doing something wrong, but i thought that dashboard ui and hue were so "common". that there is someone who has a working flow for what i am trying. I googled like crazy but couldn't find anything close ... too bad. I assume i will use scenes as well.
