### ISSUE TITLE
New firmware 14/3/22 1950111030 gives an HTTP 500 error

### ISSUE THREAD

**Issue by Travelbacon** [Foddy/node-red-contrib-huemagic#335]
**Describe the bug**
Since the update to 1950111030 for the HueBridge, the nodes to activate a scene give a HTTP 500 error and the node remains in status "Executing command forever". I noticed this on my current Raspberry Pi running Node Red. I installed a fresh version NodeRed and HueMagic on a different Pi. I Connected the Bridge to Huemagic and made a simple flow with an injection and a scene. This had the same result.

All the other nodes are working fine. And Apple Home Kit for instance is running fine with scenes.

**Flow to Reproduce**
Any setup with a scene in it. 

**Expected behavior**
To activate the requested scene.

**Screenshots**
![image](https://user-images.githubusercontent.com/36138140/158463100-99a9d030-ff26-4d3c-b5af-bd22c0b4e420.png)

**Log report**
15 Mar 20:10:21 - [info] [hue-bridge:Philips hue] Connected to bridge
15 Mar 20:10:22 - [info] [hue-bridge:Philips hue] Processing bridge resources…
15 Mar 20:10:23 - [info] [hue-bridge:Philips hue] Initial emit of resource states…
15 Mar 20:10:26 - [info] [hue-bridge:Philips hue] Keeping nodes up-to-date…
15 Mar 20:10:26 - [info] [hue-bridge:Philips hue] Subscribing to bridge events…
15 Mar 20:10:34 - [error] [hue-scene:Helder] Error: Request failed with status code 500

**Please complete the following information:**
 - Node-RED version: 2.2.2
 - NodeJS version:  14.19.0
 - Device running Node-RED: 2 Raspberry Pis with Raspbian

And of course I've rebooted the Hue Bridge. ;)

**Comment by MrTeal** [comment]
Same for me indeed. Scenes give a 500
<img width="293" alt="image" src="https://user-images.githubusercontent.com/26469005/158538578-6ffb23f3-0fd0-4649-a267-fe3a43a1972d.png">

**Comment by Kedarebwyn** [comment]
This issue is indeed related to the latest firmware, which seems to have activated a new version of the API used on the Philips Hue Bridge.

A temporary workaround, until @Foddy can fix the issue permanently is to locally change the file 'hue-scene.js'. Specifically the line:
https://github.com/Foddy/node-red-contrib-huemagic/blob/7a0d17d7d0f9924e1ef3b92b81393722c68edfec/huemagic/hue-scene.js#L90

Replacing the keyword 'status' with 'action'.

**Comment by Travelbacon** [comment]
I can confirm this patch.
Thank you for this quick solution!

**Comment by AndreTzerra** [comment]
Indeed, after changing the line it's working again!
Thanks for sharing.

**Comment by MrMiracles** [comment]
> This issue is indeed related to the latest firmware, which seems to have activated a new version of the API used on the Philips Hue Bridge.
> 
> A temporary workaround, until @Foddy can fix the issue permanently is to locally change the file 'hue-scene.js'. Specifically the line:
> 
> https://github.com/Foddy/node-red-contrib-huemagic/blob/7a0d17d7d0f9924e1ef3b92b81393722c68edfec/huemagic/hue-scene.js#L90
> 
> to this: `patchObject["recall"] = { action: "active" };`

Thanks, that works for me too!

**Comment by xtazy** [comment]
Another issue is for the 'group' node, which is not outputing a status anymore

**Comment by moeb98** [comment]
+1… and this is very annoying since a lot of my flows are relying on that. Any idea about a root cause and resolutions here?

**Comment by dongennl** [comment]
same, 3 bathrooms are in the dark most of the time now or the lights stay on indefinitely. Does anyone have a pull request ready? This seems very urgent.

**Comment by dongennl** [comment]
it works, I'll try and do a pull

**Comment by dafi87** [comment]
Are you sure your PR doesn't break it for people with the old firmware?
Also, it doesn't fix the issue with group nodes not sending out events anymore.

**Comment by dongennl** [comment]
hi, no, I have no way to test on older firmware; just trying to help those who's rooms are dark.
If anyone else is able to test backward compatibility or make the code conditional on firmware version that would be very welcome, I do not know how to do those things.

**Comment by TurboKanne** [comment]
> This issue is indeed related to the latest firmware, which seems to have activated a new version of the API used on the Philips Hue Bridge.
> 
> A temporary workaround, until @Foddy can fix the issue permanently is to locally change the file 'hue-scene.js'. Specifically the line:
> 
> https://github.com/Foddy/node-red-contrib-huemagic/blob/7a0d17d7d0f9924e1ef3b92b81393722c68edfec/huemagic/hue-scene.js#L90
> 
> to this: `patchObject["recall"] = { action: "active" };`

Nice, after deleting a lot of flows, deleting rooms and scenes in the bridge i stumpled upon this ... and this seems to help as a workaround. Thanks. Starting to re-built the settings in Hue App, Bridge and Home Assistant Node-Red :-( and  :-)

**Comment by andesse** [comment]
I already issued this a month ago
And found the problem... 

https://github.com/Foddy/node-red-contrib-huemagic/issues/316
