### ISSUE TITLE
Universal mode for Hue Scenes

### ISSUE THREAD

**Issue by beanian** [Foddy/node-red-contrib-huemagic#34]
Is there a way i can dynamically set the scene to be triggered as I can with lights & groups using msg.topic? I don't see anything in the docs

**Comment by Foddy** [comment]
Hi @beanian 

Currently, every scene is still linked to a node. But that's a good idea, which I would like to include in the next version. Unfortunately, this is not possible in this form until then.

I'll comment to this issue when this feature is included.
