### ISSUE TITLE
Motion Sensor node is missing in 4.2.0

### ISSUE THREAD

**Issue by Travelbacon** [Foddy/node-red-contrib-huemagic#340]
**Describe the bug**
Motion Sensor is missing in the update of 4.2.0

**Additional context**
After installing the newest update 4.2.0, the node for the motion sensor is missing.

**Comment by MrMiracles** [comment]
Node red tells me; 
SyntaxError: Unexpected token ')' (line:165)

**Comment by MrMiracles** [comment]
Fixed it by added in } on line 165
I did a pull request on it.

For now change line 165 from:
`.then(function() { if(done) { callback(null, true); })`
to
`.then(function() { if(done) { callback(null, true); }})`

**Comment by Swiftnesses** [comment]
Same issue here @Foddy can we have a hotfix pretty please?

**Comment by Foddy** [comment]
Thank you for your fast hint!
