### ISSUE TITLE
Connection failed to hue bridge / lamps

### ISSUE THREAD

**Issue by effen28** [Foddy/node-red-contrib-huemagic#375]
Hallo together,

since a few days ago (maybe since the update), I can not longer choose a lamp in the drop down.
=> it says, there went something wrong, try again

![Unbenannt](https://user-images.githubusercontent.com/102071484/173245548-3d9f8f7f-714d-48c9-936b-d7dc2fcf2d6d.JPG)

also the Hue Bridge-Node says always connecting, but without success

![image](https://user-images.githubusercontent.com/102071484/173245728-8214d1b6-e4e1-425a-80b6-eff3eb013e42.png)

Hope someone can support/help me

Thank you

**Comment by andesse** [comment]
This is a known behavior. Check all the recent bug reports.

**Comment by andesse** [comment]
Here my repository for https HUE API V2. It's just a flow with everything you need. https://github.com/andesse/node-red-hue-api.v2-flows

**Comment by Travelbacon** [comment]
Duplicate  #374

**Comment by xyzo** [comment]
@effen28 I do have the exact same issue and haven't found a solution so far. My Hue-Lights don't work anymore from their huemagic-nodes in Node Red :-(

**Comment by andesse** [comment]
@xyzo here. Very easy. You will be happy. 
https://github.com/andesse/hue-clip-api.node-red-flows

**Comment by xyzo** [comment]
@andesse I discovered that 30 mins ago. I already AM happy now :-D 
Thanks for your work!!

**Comment by andesse** [comment]
@xyzo cool, it won’t take long to set it up and you have zero issue for a long time, cause the api is brand new

**Comment by xyzo** [comment]
@andesse It works. Honestly I'd appreciate if there would be features like selecting rooms/lights/zones from within the nodes menus instead of copy and pasting UIDs everywhere. 

To make sure: it works perfectly if you have digged yourself through everything what might be a bit difficult for people who are "only users". It's just a matter of being user friendly/intuitive...

**Comment by xyzo** [comment]
@andesse 
BTW: the comment node "lights - DOUBLE CLICK FOR INFO" is empty... no info on double-click :-)

**Comment by andesse** [comment]
@xyzo this is not a contrib. This is a flow that you change for your needs. I want that the users get contrib free and independent. So they have no struggle in the future when contribs don’t get updated. 

Light Doubleclick. Can happen. I already have it in the readme at the end, that there could be mistakes. 
Lights are almost the same setup like rooms. 

Follow my recommendation. Trigger scenes, not lights separate if possible. It’s important to read the full readme.

**Comment by xyzo** [comment]
@andesse I got you and I didn't want to upset you.
Just saying that someone who doesn't have a clue about what is going on "inside" and just used huemagic before is now looking for something which works the same like huemagic. Some persons might be looking for similar solutions only.

You did great work with your tidy flow - really!
It's just not a simple out-of-the-box-solution like before and still I see the advantages.

**Comment by andesse** [comment]
> @andesse It works. Honestly I'd appreciate if there would be features like selecting rooms/lights/zones from within the nodes menus instead of copy and pasting UIDs everywhere.
> 
> To make sure: it works perfectly if you have digged yourself through everything what might be a bit difficult for people who are "only users". It's just a matter of being user friendly/intuitive...

I will never add this kind of features. These are parsed nodes again, that will not work some day if they are not maintained. If you want that, wait for HueMagic update.

**Comment by xyzo** [comment]
@andesse I won't wait :-)
What I got now with your work is for MY needs perfect. More perfect then huemagic was before :-)

**Comment by andesse** [comment]
Haha, yeah I got that. No worries. For me this solution has so many flows and examples now, that even only user people can do it when figured out. 
most work is Label link in nodes. 

Thanks for your second comment. :)
I am happy for everybody who can end struggling.

**Comment by lukystreik** [comment]
nodered-local-node-red-1  | 16 Oct 07:47:03 - [info] [hue-bridge:vxhue2] Initializing the bridge (192.168.1.122)…
nodered-local-node-red-1  | 16 Oct 07:47:03 - [info] [hue-bridge:vxhue2] Connected to bridge
nodered-local-node-red-1  | 16 Oct 07:47:04 - [info] [hue-bridge:vxhue2] Processing bridge resources…
nodered-local-node-red-1  | 16 Oct 07:47:04 - [info] [hue-bridge:vxhue2] TypeError: Cannot read properties of undefined (reading 'owner')

Same here, since upgrading to the latest verion of nodered and huemagic, the connection to the brigde is broken. 
The Node status is "connecting".

**Comment by lukystreik** [comment]
I´ve found the issue.
If you add debug logs in the function this.fullResource in utils/api.js it is easier to determine the problem.
You should add something like that below on log stage debug:
`
//load the util function at the beginning of the api.js:
const util = require('util');

...
around line 185:
        // GET FULL/ROOT RESOURCE
        this.fullResource = function(resource, allResources = {})
        {
                const scope = this;
                var fullResource = Object.assign({}, resource);

                console.log("before Owner: " + util.inspect(resource,false, null, true /* enable colors */));

                if(resource["owner"])
                {
                        console.log("in Owner: " + util.inspect(resource["owner"],false, null, true /* enable colors */));
                        fullResource = scope.fullResource(allResources[fullResource["owner"]["rid"]], allResources);
                }

`
<img width="926" alt="Bildschirmfoto 2022-10-16 um 13 50 06" src="https://user-images.githubusercontent.com/66489673/196034113-2cfcbe3b-0abf-4a1a-a317-316bed473c2a.png">



Now we can see, witch is the case:
Here in the group a private owner is defined, witch can not processed by the huemagic api:

`
nodered-local-node-red-1  | vor Owner: {
nodered-local-node-red-1  |   id: 'beda2532-950b-4f9e-b8e1-653e1fcd5bbd',
nodered-local-node-red-1  |   id_v1: '/groups/6',
nodered-local-node-red-1  |   owner: {
nodered-local-node-red-1  |     rid: '867613e6-172e-4ae8-80e4-e8a8dc18cee1',
nodered-local-node-red-1  |     rtype: 'private_group'
nodered-local-node-red-1  |   },
nodered-local-node-red-1  |   on: { on: false },
nodered-local-node-red-1  |   alert: { action_values: [ 'breathe' ] },
nodered-local-node-red-1  |   signaling: {},
nodered-local-node-red-1  |   dynamics: {},
nodered-local-node-red-1  |   type: 'grouped_light'
nodered-local-node-red-1  | }
nodered-local-node-red-1  | im Owner: { rid: '867613e6-172e-4ae8-80e4-e8a8dc18cee1', rtype: 'private_group' }
nodered-local-node-red-1  | vor Owner: undefined
nodered-local-node-red-1  | 16 Oct 13:46:03 - [info] [hue-bridge:vxhue2] TypeError: Cannot read properties of undefined (reading 'owner')
nodered-local-node-red-1  | 16 Oct 13:46:03 - [red] Uncaught Exception:
nodered-local-node-red-1  | 16 Oct 13:46:03 - [error] TypeError: Cannot read properties of undefined (reading 'owner')
nodered-local-node-red-1  |     at API.fullResource (/data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:187:14)
nodered-local-node-red-1  |     at API.fullResource (/data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:190:25)
nodered-local-node-red-1  |     at /data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:247:30
nodered-local-node-red-1  |     at Array.forEach (<anonymous>)
nodered-local-node-red-1  |     at /data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:244:14
nodered-local-node-red-1  |     at new Promise (<anonymous>)
nodered-local-node-red-1  |     at API.processResources (/data/node_modules/node-red-contrib-huemagic/huemagic/utils/api.js:224:10)
nodered-local-node-red-1  |     at /data/node_modules/node-red-contrib-huemagic/huemagic/hue-bridge-config.js:92:47
nodered-local-node-red-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nodered-local-node-red-1 exited with code 1
`

**Comment by lukystreik** [comment]
Quick fix: Ignor private_groups in api.js:

<img width="986" alt="Bildschirmfoto 2022-10-16 um 16 40 51" src="https://user-images.githubusercontent.com/66489673/196041757-14a871ce-9dff-47df-9364-7c17c4716fdd.png">

line 176ff. in utils/api.js
                if (resource === undefined ) {
                  console.log("huemagic: ignore undefined resources");
                  return allResources;
                }

**Comment by zelloxy** [comment]
I'd love for a fix for this, just begun setting up my flow and getting th "Connected to bridge" then the owner error.

**Comment by andesse** [comment]
@zelloxy 

https://github.com/andesse/HUE-CLIP-API.Node-RED-Flows

Try this
