### ISSUE TITLE
Performance Issues with colornamer

### ISSUE THREAD

**Issue by beanian** [Foddy/node-red-contrib-huemagic#39]
After updating to v1.4 I have noticed a 10x performance degradation in the sendGroupStatus function in hue-group.js. Based on my own timings it was taking on average 600ms to execute this function. Once I remove the colornamer call it is reduced to 60ms on average.
This has a noticeable impact on my toggle lightswitches as my flow checks if the light is on or off before determining if it need to switch the group off or on.

**Comment by Foddy** [comment]
Thank you for this small benchmark test!
I will therefore add the possibility to disable the function when needed in the next version.

**Comment by Foddy** [comment]
Option added in v1.5.0
