### ISSUE TITLE
Hue Tap: won't allow multiple presses on the same button

### ISSUE THREAD

**Issue by natcl** [Foddy/node-red-contrib-huemagic#40]
It seems like it's not possible to get a message if you press more than 1 time on the button of a tap, you need to press one of the other buttons to have the original button retriggered.  It would be useful to allow this as we could program toggle switches.
Thanks !

**Comment by natcl** [comment]
Checking the code this could be achieved by checking `sensor.state.lastUpdated`

**Comment by natcl** [comment]
Sent PR #41 to fix this

**Comment by Foddy** [comment]
Thank you! I've merged this pull request to the master branch
