### ISSUE TITLE
Can I read the status of lights based on trigger

### ISSUE THREAD

**Issue by arvdsar** [Foddy/node-red-contrib-huemagic#43]
Hi,

Is it possible to read the status of a light based on an input trigger? (Every x-minutes or when a flow is started). Currently I use ttb-node-hue which works fine, but it I like to use the other Huemagic functionality and therefore I need to switch over.

i.e. When I get home a flow is started to check each of my hue lights one by one. If any of the lights is on, nothing is changed to not mess with the light settings of my family members. If all lights are off, then some lights are turned on to welcome me home.

Best Regards,
Alexander

**Comment by lespatots** [comment]
The Light Node in Huemagic automatically sends a light status whenever a light is changed. That is no matter how it was changed. To do what you want actually needs a continuously running flow to detect if any light is on and set the status you desire. I think the only way to make a specific enquiry would be to send a light a change. Perhaps a transition time modification might do it, you'd have to try it?

**Comment by Foddy** [comment]
Exactly! I could also think of just using a Hue Group node and assign all the lights of your home inside it.

Then you simply check with the “anyOn” property if any of the lights are on and trigger the commands that you want to do without having to loop through every light separately.

**Comment by arvdsar** [comment]
thanks! I'll try your suggestions!

**Comment by arvdsar** [comment]
it's been a while but I wanted to provide feedback. It indeed works when you just update the transition time. The group node will answer with the "anyOn" property.
Additionally, when lights are changed in this group, the group node is triggered and outputs the information. So you can use the group node to update a variable which you can check. It makes my flows more simple. Thanks!
