### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by oblongx** [Foddy/node-red-contrib-huemagic#44]
Hello,

I am having trouble using this node. I am able to connect to the bridge and can search for my lights on the light node. When I deploy I get this error in the debug window whether or not I have a debug node attached to the light. Any idea what I'm doing wrong?
Latest firmware on my bridge and lights.

4/1/2018, 1:22:27 AMnode: Tall lamp
msg : error
"SyntaxError: Unexpected token ="

**Comment by Foddy** [comment]
Are you using Node.JS 8 or 9?

**Comment by oblongx** [comment]
Nope, I was running 4.2.1. Upgraded to v9.10.1 and all is well. Thanks much.
