### ISSUE TITLE
Motion / Temp / Lux sensor issue

### ISSUE THREAD

**Issue by MrBriz** [Foddy/node-red-contrib-huemagic#47]
Hi Foddy,

First I'd like to say thanks for developing this. It's a fantastic little node-red plugin!

So my issue is as follows...

First, I've wired up an input switch to disable / enable the motion sensors. I have 10 sensors, if I wire the switch directly into the sensors I get the following...

![image](https://user-images.githubusercontent.com/7437498/39302912-1b2d0682-494c-11e8-91c9-c3000a6dd666.png)

Then I read somewhere about an issue with API limits, so I create a bunch of hue bridges all connecting to the same IP address but with different user keys, still the same, so finally I put a bunch of random timers between the switch and the sensors, that seems to work fine (guessing the hue rejects requests if fired at the same time)

![image](https://user-images.githubusercontent.com/7437498/39303056-b1f8beb2-494c-11e8-9e6c-8d0594d20187.png)

So that's one thing. The other is the Lux / Temp sensors.

![image](https://user-images.githubusercontent.com/7437498/39303143-0085a48c-494d-11e8-8729-d2cdbf47b153.png)

As you can see I added in one temp sensor. It worked once, then just failed....

So on my bridge I have the following:

Motion Sensors: 10
Dimmer Switches: 12
Hue Colour Bulbs: 14
Hue White Bulbs: 20 (need to add 5 more)
Light Strip: 1 (need to add another 2)

I'm not sure if it's the size of my setup that has issues. I'm hoping to have little node-red flows for almost all of the elements at some point.

If you need me to run / debug anything we can set something up. I'm a developer, but it's been about 4 years since I've done anything in node, so I might need a little hand-holding, but I've been doing this stuff for 20 years, so shouldn't take me long!

Thanks,

James.

**Comment by lespatots** [comment]
Hi,

Seems you are confirming what I have been seeing. Nice (not) to see the same error messages cropping up as at least I'm not alone.  I got round the issue by setting different 'poll intervals' to spread the enquiries around. I read battery state from switches which is an extra load!

I would say that you have rather a lot of devices that need polling and as you are using Node-Red for some things perhaps you'd be better with an extra bridge and spreading the load. I think 12 is about the limit for switches on one bridge. It is difficult, I know, to spread lights and switches sensibly across more than one bridge especially if you have an 'all lights off' function. But I have started to use Homekit and that allows me to integrate functionality across bridges though it is also possible in Node-Red if you sort out an algorithm to read switch states and act appropriately on them. I have three of the new bridges connected and I have three more of the old ones which I could integrate using Homebridge.

I think things will get worse for a while when Philips have their new partner release switches that may be two or three gang (can't wait). It will also be interesting to see whether the wifi on the bridges is activated when they release outside lamps as a wired ethernet connection to an exterior bridge isn't too clever if you live in an area where there are regular lightning strikes.

**Comment by MrBriz** [comment]
Dammit, I didn't want to go out and get more bridges.... do you know if anyone has created virtual homekit bridges in node-red? I'm guessing I could just put all the switches and sensors on one bridge, then the lights on another, or do the switches only work for lights on that bridge?

**Comment by lespatots** [comment]
Hi,

No I would like one too. There is a Homekit emulator node but it is just that. I am using Homebridge with an MQTT interface that allows for creating Homekit devices that you can interface to Homekit and thence via MQTT to Node-Red. At present I am quite impressed with what Homebridge and its plugins can do. For example I used to have HelloHue in Plex for light dimming but now I can do it with a Homebridge plugin and Homekit. I have so many Hue bridges because they were just about free with offers on Amazon! For example, today I can get three GU10 colour lamps with a bridge for 103 euro here in France. There is also a three lamp E27, dimmer and bridge (used) pack for 123 euro.

**Comment by MrBriz** [comment]
I've seen the lights with the bridges, but I ended up just getting the lights in double packs as it was buy two, get one free (33% off) so that's how I kited out the whole house.

So any tips? I've only just started playing with node-red. Someone was suggesting using home-assistant (hass) for the storage of hue states, then just using node-red for all the logic. Have you tried it?

How does it work with the multiple bridges? I'm assuming homekit just works fine and sees everything as normal? I'm guessing it's the same with node-red, just have to pick the right bridge when adding in light / sensor / switch nodes?

So how did you setup the bridges? One for lights, one for switches one for sensors?

**Comment by MrBriz** [comment]
Hey Richard,

Well I just went all in on Philips hue :) The only thing non-Philips is the Raspberry Pi, which is running a Night Hawk camera and a python script using OpenCV so that it can identify humans in the room.

After some digging I've realised I might be able to use some sort of PIR sensor in the room to do this. The issue I have is the movement sensors are good, but only when there is movement! I want to detect the presence of a person, but also the absence so that I can turn off the lights if there isn't anyone in the room, which is why I am using the Pi and a camera.

I'm planning on getting a bunch of the outdoor lights that Philips announced when they are released in the summer.

I'm also planning on using the lux levels for turning on the lights, which is why the hue sensors are handy!

**Comment by MrBriz** [comment]
OK. So I brought a couple more bridges and have been playing. It seems that it can't really handle any more than 3 sensors before there starts to be connection issues!

![image](https://user-images.githubusercontent.com/7437498/39319879-597a4a20-497a-11e8-8bdc-c94f6dbe25b0.png)

As you can see I have 4 sensors, and on deploy I start to get connection errors :(

**Comment by MrBriz** [comment]
btw it's only those 4 sensors on the bridge....

**Comment by MrBriz** [comment]
Just to confirm it seems to work OK if you only have 3 sensors on depl.... scratch that! one of the temp sensors started erroring!

![image](https://user-images.githubusercontent.com/7437498/39321031-b787e8b8-497d-11e8-8a3d-d7c65b2b6eaa.png)

**Comment by MrBriz** [comment]
Also... can I request a feature (if you read down this far Foddy....)

When adding in a temp or lux sensor with the following info details..

model.manufacturer: Philips
model.name: Hue Motion Sensor

You can take the unique ID, remove everything after the last "-" then find the corresponding motion sensor (the matching on ending -0406), and grab the name from that.

It seems the pattern is ID-(0406 - motion) | (0400 - light) | (0402 - temp)

Examples of IDs
Kitchen sensor
00:17:88:01:02:12:83:f6-02-0406

Hue ambient light sensor 1
00:17:88:01:02:12:83:f6-02-0400

Hue temperature sensor 1
00:17:88:01:02:12:83:f6-02-0402


Office sensor
00:17:88:01:03:28:48:b8-02-0406

Hue ambient light sensor 2
00:17:88:01:03:28:48:b8-02-0400

Hue temperature sensor 2
00:17:88:01:03:28:48:b8-02-0402


Dressing room sensor
00:17:88:01:02:12:75:3a-02-0406

Hue ambient light sensor 3
00:17:88:01:02:12:75:3a-02-0400

Hue temperature sensor 3
00:17:88:01:02:12:75:3a-02-0402

**Comment by lespatots** [comment]
Are you sure that your random node is doing what you want? I see that until the error the times reported are for the same second (clusters of three). Try setting longer and different poll times? Say ten seconds apart?

I've avoided presence detection because it is a very difficult thing to do. The best solution is definitely BLE beacons worn by room occupants. The best ones can triangulate and calculate accurate position. But of course the downside is having them on you. A bit like detecting your phone which really only works on a WIFI network with multiple access points. Even then my phone is logged into the lounge and my wife's to the kitchen even though we are both actually in the lounge. Though of course we are both home.

At present I can detect Plex activity in the Lounge and in the Bedroom if I can get a fix for more than one Plex player instance. I guess I could detect that the TV is on as an alternate. Additionally if you think about it presence and activity are related. So in the bedroom sometimes we're active but mostly asleep BUT the lighting solution is very different/ Lastly we have a dog and cat that are perfectly able to trigger motion detectors! Incidentally we don't have all out Hue dimmer switches stuck on the wall as that can be inconvenient too!

All part of the learning experience.

**Comment by MrBriz** [comment]
It's not when I'm clicking the input button that I get the errors. It's when I deploy / restart node.

This home automation stuff is a pain, but fun!

**Comment by MrBriz** [comment]
OK, so after some testing I think I know what's going on...

Basically to many requests to the hub in the same second!

What I've currently got working is the following (and I don't think I need multi hubs for this, but it helps)

3 api users for one of the hubs. One for Motion, set to poll every second, one for my lux sensors set to poll every 10 seconds, and one for my temp sensors polling every 15 seconds.

I did this to space the requests apart a little so I could confirm the issue.

There is an easy(ish) solution to this. Have a class of sensor where you queue up the requests and only send the next request once the previous one is complete. Basically for sensors that don't need to be instant just make sure the requests are not done parallel.

I will most likely end up polling the sensors with a 5 second gap between them. So maybe I have light sensors polled every 15 seconds, and temp sensors polled every 20 seconrs.

What I really want is as I said above, only poll one sensor at a time!

**Comment by MrBriz** [comment]
Yes I spotted that, but it's not on a sensor by sensor basis, it for each API user on the hub. That's why I have 3 API users. One polling every second, one every 10 seconds and one every 15 seconds

**Comment by MrBriz** [comment]
That shouldn't hopefully stop any clashing in API calls

**Comment by MrBriz** [comment]
OK... So this has it's limits! OK. Well now I know the issue I'm going to start digging in the Hue API. I'm going to end up calling the temp and lux sensors myself in a phython / bash / c / php script (whatever I end up using) and write the values to files that I can pragmatically pick up and use in node-red.

Basically just to many API calls... I'm going to dig around in the Hue API docs... be back later......

**Comment by Foddy** [comment]
Please excuse my late feedback on this... I think that we could solve the problem a bit easier. The Hue API offers something like batch API requests. This would allow you to query the status of all devices of a certain type with only one request at a relatively low poll time and let HueMagic do the rest…

I'll be working on a solution soon, as more and more users seem to be affected by this issue and that is in fact the better solution. Sorry, unfortunately, there is not much concrete to read about API limits, which is why I did not think at the time that this could be the problem sometime… 😶

**Comment by MrBriz** [comment]
I thought the hue API would allow batch requests :)

Is there anything I can help with Foddy? If you're willing to spend a small amount of up-front time getting my head into your code and helping me get back into node again I'm sure I could help.

**Comment by Foddy** [comment]
Thanks, I appreciate that! I guess I need some time to plan the new "algorithm" just to be able to offer a smooth upgrade for every kind of user – but I like to come back to you and then give you a little insight into my chaos 😁 !

**Comment by MrBriz** [comment]
Nice. I'm currently moving house, so this should only really be a side-project, but I will see if I can get a few hours this weekend to read through the code :D

**Comment by MrBriz** [comment]
Just out of interest, where in the hue api docs does it mention the batch requests? I've been digging and I can't find anything.

**Comment by Foddy** [comment]
haha no problem ;)

Directly under [point "5.1 Get all sensors"](https://developers.meethue.com/documentation/sensors-api) for example. With this method it would be theoretically possible to interrogate all sensors and their statuses with just two requests. I just hope that this approach does not "overheat" the bridge in any other way…

**Comment by MrBriz** [comment]
It would still be 1n. The first request just gets a list of sensors, you'd still have to make n requests to get back all of the data, which is how I'm assuming it's currently done (just at a rate that is too quick)

**Comment by MrBriz** [comment]
1n +1 even :D

**Comment by MrBriz** [comment]
Actually I lie... see it now :D

**Comment by MrBriz** [comment]
I did a http request direct to the hue api (http://[hue-ip]/api/[key]/sensors), then did the following in a function node which left me with a global object indexed by the sensor id without the last 0406/0402/4000 and also the 0406 one for quick lookup......

let sensor_data = {};

let data = msg.payload;

let parse_sensor_id = function(sensor_id) {
    let last_underscore = sensor_id.lastIndexOf('-');

    //- Split up the id
    let sensor_chassis = sensor_id.substr(0, last_underscore);
    let sensor_type = sensor_id.substr(last_underscore+1);

    return {"type": sensor_type, "id": sensor_chassis}
}


//- Loop through all the sensors and split into the Movement / Temp / Lux
let keys = Object.keys(data);
for(var key_index = 0; key_index < keys.length; key_index++) {
    let sensor_id = keys[key_index];

    //- We only want to deal with the movement / lux / temp sensors.
    switch(data[sensor_id].type) {
        case 'ZLLPresence':
        case 'ZLLTemperature':
        case 'ZLLLightLevel':
            let sensor_type_data = parse_sensor_id(data[sensor_id].uniqueid);

            //- Check to see if we already have a space for the combined data
            if(!sensor_data.hasOwnProperty(sensor_type_data.id)) {
                sensor_data[sensor_type_data.id] = {
                    'ZLLPresence': null,
                    'ZLLLightLevel': null,
                    'ZLLTemperature': null,
                    'name': null,
                    'id': sensor_type_data.id
                };
            }
            sensor_data[sensor_type_data.id][data[sensor_id].type] = data[sensor_id];

            //- If we are the ZLLPresence sensor then we want to grab the name from there.
            if(data[sensor_id].type == 'ZLLPresence') {
                sensor_data[sensor_type_data.id].name = data[sensor_id].name;

                //- Also make a virtual holder pointing to to complete sensor storage
                sensor_data[data[sensor_id].uniqueid] = sensor_data[sensor_type_data.id];
            }

            break;
    }
}

global.set("sensors", sensor_data);

msg.payload = 'Sensors fetched';
return msg;

**Comment by MrBriz** [comment]
You can do the same with the lights, this is what I did (assuming a previous http request node going to http://[hue-ip]/api/[key]/lights)....

let light_data = {};

let data = msg.payload;

//- Loop through all the sensors and split into the Movement / Temp / Lux
let keys = Object.keys(data);
for(var key_index = 0; key_index < keys.length; key_index++) {
    let light_id = keys[key_index];
    light_data[data[light_id].uniqueid] = data[light_id];
}

global.set("lights", light_data);

msg.payload = 'Lights fetched';
return msg;

**Comment by MrBriz** [comment]
I think with the sensors I'll end up adding in checks for the switches, then add those into another main global for use in the flows...... not slept yet... been working on work stuff and this has been buzzing through my brain!

**Comment by ozdeadmeat** [comment]
I was thinking the http request would be a last resort. I have 3 sensors, 2 dimmer switches and about 20 lights atm but the final setup will contain approximately 60 bulbs and 10 or so sensors. What would be a good feature is the ability to define the different objects poll interval. I don't need group info or sensor info every 500ms, hell 20 minute intervals would be fine for me. Has anyone managed to talk to the guy writing this thing to see if/when its going to be fixed. I am really not keen on purchasing more bridges. This really does seem like an over polling issue for things that dont need to be polled so hard. Also, is there anything that can remove the hue bridge from the equation as I think the bridges performance is also going to be a weak link here.

**Comment by Foddy** [comment]
Should be fixed with v1.7.0
