### ISSUE TITLE
Add the real LUX value as option. (Formula added)

### ISSUE THREAD

**Issue by Travelbacon** [Foddy/node-red-contrib-huemagic#49]
Just to discuss.

Brightness' lightLevel is now the INT16 defined by Philips to make Lux more understandable. Lux is in real life not a linear value. "Light level in 10000 log10 (lux) +1 measured by sensor. Logarithm scale used because the human eye adjusts to light levels and small changes at low lux levels are more noticeable than at high lux levels." HUE-API documentation of Philips.

Is it an option to create an extra output LUX or an extra node?
The formula is Math.pow(10, (INT16 - 1)/10000);
Or
```
lux = lightLevel - 1
lux = lux / 10000
lux = Math.pow(10, lux)

msg.payload = Math.round(lux)
return msg;
```

Before I create one and suggest as a pull, I rather discuss. :)

**Comment by Foddy** [comment]
Thank you for this.
The output object is now extended with the lux property on all Hue Brightness nodes with v1.5.6
