### ISSUE TITLE
Toggle light

### ISSUE THREAD

**Issue by iChUdY** [Foddy/node-red-contrib-huemagic#50]
Hi,

pls add toggle msg to ON/OFF light with one stateless button in node-red.

**Comment by ozdeadmeat** [comment]
Doesn't changing the state of the light turn it on anyway?

**Comment by swissglider** [comment]
Yes please do so

**Comment by PiRune** [comment]
A toggle node that gets the light status and then inverts it would be great. I made a toggle based on automatic light events which is too slow

**Comment by PiRune** [comment]
I also think it would be more user friendly with some sort of toggle-node.

Earlier today I just realised a proper workaround, however: https://github.com/Foddy/node-red-contrib-huemagic/issues/86#issuecomment-519464039

**Comment by Foddy** [comment]
Available from version 2.0 ;)
