### ISSUE TITLE
Single Bridge with overpolling on groups, lights and sensors

### ISSUE THREAD

**Issue by ozdeadmeat** [Foddy/node-red-contrib-huemagic#53]
I am experiencing errors with my bridge when utilizing groups, lux / motion sensors and more than 10 lights in a single flow. I was wondering if there was a way to control the poll intervals dependent on the type of device it is or if this feature can be added. I am not a coder but I am confused as to why the group node needs to be polled every 500ms, but if i nerf my bridge interval rate the lights and motion sensors become sluggish to react.

**Comment by Foddy** [comment]
Thank you for your feedback!

I've improved that a bit in the latest version and I'm already working on a better way to optimize connections to the bridge. I'll let you know as soon as there is something new :)!
