### ISSUE TITLE
Ability to poll and update the status of  the lights? 

### ISSUE THREAD

**Issue by nodecentral** [Foddy/node-red-contrib-huemagic#58]
Hi, I find tha a number of bulbs will show a ‘connection error’ but the status will update if a value/request is sent. Is there a way (a command) that can be sent to update the status value.  Maybe I could set it to poll every x seconds/minutes ?

**Comment by Foddy** [comment]
Connection errors are fixed with v1.7.0.
You just need to set your poll interval in your bridge settings once.
