### ISSUE TITLE
incrementBrightness?

### ISSUE THREAD

**Issue by fillilutten** [Foddy/node-red-contrib-huemagic#59]
I dont get incrementBrightness to work. What am I doing wrong?

Thanks!

[{“id”:“1ffc6b46.8b1c25”,“type”:“inject”,“z”:“71a28332.a9335c”,“name”:"",“topic”:"",“payload”:"{“incrementBrightness”:50}",“payloadType”:“json”,“repeat”:"",“crontab”:"",“once”:false,“onceDelay”:0.1,“x”:110,“y”:271,“wires”:[[“d33f00aa.d3c89”,“d7746f6a.e59a5”]]},{“id”:“d33f00aa.d3c89”,“type”:“hue-light”,“z”:“71a28332.a9335c”,“name”:“Kök tak”,“bridge”:“6005b0be.e4595”,“lightid”:“6”,“colornamer”:true,“x”:409,“y”:261,“wires”:[[“f6e7ac1d.52e8d”]]},{“id”:“d7746f6a.e59a5”,“type”:“debug”,“z”:“71a28332.a9335c”,“name”:"",“active”:true,“tosidebar”:true,“console”:false,“tostatus”:false,“complete”:“true”,“x”:382,“y”:169,“wires”:[]},{“id”:“f6e7ac1d.52e8d”,“type”:“debug”,“z”:“71a28332.a9335c”,“name”:"",“active”:true,“tosidebar”:true,“console”:false,“tostatus”:false,“complete”:“false”,“x”:609,“y”:177,“wires”:[]},{“id”:“6005b0be.e4595”,“type”:“hue-bridge”,“z”:"",“name”:“Philips hue”,“bridge”:“192.168.0.15”,“key”:“9AD9LgeN01xTm4XIdv6NtFBxDT387tV767jA0B8G”,“interval”:“1300”}]

**Comment by ArnieX** [comment]
Hi, I have imported your flow and it works for me. Are you able to control your lights ON/OFF using inject {"toggle":1} for example?

**Comment by fillilutten** [comment]
Oh, I moved on and I don't use HueMagic anymore. Thanks anyway!

**Comment by ArnieX** [comment]
Yeah I saw the date posted after I replied ;).
