### ISSUE TITLE
Motion sensor also has Temperature and Ambient Light sensor

### ISSUE THREAD

**Issue by lucwuyts** [Foddy/node-red-contrib-huemagic#6]
Do you plan to support these ?

After adding my motion sensor, i see 3 extra devices when i call the api:
http://10.0.250.54/api/----user----/sensors

These are the devices:  (didn't include the bridge)

"2":{"state":{"temperature":2021,"lastupdated":"2017-09-20T12:25:16"},"config":{"on":true,"battery":100,"reachable":true,"alert":"none"},"name":"Thermostat 1","type":"ZLLTemperature","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:03:0e:44-02-0402"},

"3":{"state":{"presence":false,"lastupdated":"2017-09-20T12:23:08"},"config":{"on":true,"battery":100,"reachable":true,"alert":"none"},"name":"Hue motion sensor 1","type":"ZLLPresence","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:03:0e:44-02-0406"},

"4":{"state":{"lightlevel":0,"dark":true,"daylight":false,"lastupdated":"2017-09-20T12:28:08"},"config":{"on":true,"battery":100,"reachable":true,"alert":"none","tholddark":16000,"tholdoffset":7000},"name":"Hue ambient light sensor 1","type":"ZLLLightLevel","modelid":"SML001","manufacturername":"Philips","swversion":"6.1.0.18912","uniqueid":"00:17:88:01:02:03:0e:44-02-0400"}

**Comment by Foddy** [comment]
Hi, these devices are already supported by HueMagic? Simply select the Brightness and Temperature node and select your „Motion“ sensor.

Or did I misunderstood you?

**Comment by lucwuyts** [comment]
Ok, I didn't know that.  Thought this was for some seperate device...
Thanks.

**Comment by Foddy** [comment]
No problem. Please check out the README file on this repo to get more information about what you can do else with you motion sensor and HueMagic ;)
