### ISSUE TITLE
Validation error of Group node if no group ID is configured

### ISSUE THREAD

**Issue by altery** [Foddy/node-red-contrib-huemagic#61]
### Problem

The _Hue Group_ node displays a validation error (red triangle), if the _Group_ field is empty in the property window of the node. But the _Group_ field must be empty in order to trigger "universal mode", i.e. passing the group id as topic within the message.

### Expected behavior
The group node does not raise a validation error even if no group id is configured.

### Pointers
The field is implemented like this:
```
groupid: {value:"", required: false, validate: RED.validators.number()},
```

It may be sufficient if the default value is changed to type numeric instead of a (empty) string.

**Comment by michaelblight** [comment]
This is a problem for `Hue Light` as well. To use "universal mode" I have to leave the light id empty, but this produces an error on the node. Every deploy thereafter produces the "The workspace contains some nodes that are not properly configured" warning.

**Comment by torandi** [comment]
I have the same problem (with Hue Light in universal mode). It works, but it's annoying to have to discard an error every time I deploy.

**Comment by Foddy** [comment]
Fixed ;)
