### ISSUE TITLE
Dashboard Slider flow for hue bulb 

### ISSUE THREAD

**Issue by nodecentral** [Foddy/node-red-contrib-huemagic#62]
Hi 

Has anyone got a working example of how to control the brightness of a hue bulb via a dashboard slider ?

**Comment by ThibautRuy** [comment]
See below slider to control the brightness of my HueGo, then color picker to change the color. 
You will need to adapt it to your own values.

Example of values to be adapted:

> "bridge":"yourbridgeIP",

> "key":"yourkey",


![capture d ecran 2018-10-07 a 20 41 21](https://user-images.githubusercontent.com/14328511/46585472-7fdb6500-ca71-11e8-93ee-17b60f077679.png)
![capture d ecran 2018-10-07 a 20 40 49](https://user-images.githubusercontent.com/14328511/46585454-53bfe400-ca71-11e8-89fd-13e7b7a47c30.png)


[
   {
      "id":"24e9f9fd.551906",

      "type":"ui_slider",
      "z":"2207afb5.f64e2",
      "name":"brightness",
      "label":"slider",
      "group":"38065ddb.915822",
      "order":0,
      "width":0,
      "height":0,
      "passthru":true,
      "topic":"",
      "min":0,
      "max":"100",
      "step":1,
      "x":210,
      "y":380,
      "wires":[
         [
            "380caf9a.eb7d7"
         ]
      ]
   },
   {
      "id":"7b044ea9.91536",
      "type":"hue-light",
      "z":"2207afb5.f64e2",
      "name":"Hue go 1",
      "bridge":"yourbridge",
      "lightid":"3",
      "colornamer":true,
      "x":620,
      "y":380,
      "wires":[
         [

         ]
      ]
   },
   {
      "id":"380caf9a.eb7d7",
      "type":"template",
      "z":"2207afb5.f64e2",
      "name":"",
      "field":"payload",
      "fieldType":"msg",
      "format":"handlebars",
      "syntax":"mustache",
      "template":"{\n   \"on\":true,\n   \"brightness\":{{{payload}}},\n   \"rgb\":[\n      100,\n      206,\n      232\n   ],\n   \"colorTemp\":500\n}",
      "output":"json",
      "x":420,
      "y":380,
      "wires":[
         [
            "7b044ea9.91536"
         ]
      ]
   },
   {
      "id":"aa37573f.0e0498",
      "type":"ui_colour_picker",
      "z":"2207afb5.f64e2",
      "name":"",
      "label":"",
      "group":"38065ddb.915822",
      "format":"hex",
      "outformat":"string",
      "showSwatch":true,
      "showPicker":true,
      "showValue":true,
      "showHue":true,
      "showAlpha":false,
      "showLightness":true,
      "dynOutput":"false",
      "order":0,
      "width":0,
      "height":0,
      "passthru":true,
      "topic":"",
      "x":210,
      "y":500,
      "wires":[
         [
            "87a98cb5.cbf25",
            "9866492d.c2a598"
         ]
      ]
   },
   {
      "id":"87a98cb5.cbf25",
      "type":"debug",
      "z":"2207afb5.f64e2",
      "name":"",
      "active":true,
      "tosidebar":true,
      "console":false,
      "tostatus":false,
      "complete":"false",
      "x":430,
      "y":460,
      "wires":[

      ]
   },
   {
      "id":"9866492d.c2a598",
      "type":"template",
      "z":"2207afb5.f64e2",
      "name":"",
      "field":"payload",
      "fieldType":"msg",
      "format":"handlebars",
      "syntax":"mustache",
      "template":"{\n   \"on\":true,\n   \"hex\":\"{{{payload}}}\"\n}",
      "output":"json",
      "x":400,
      "y":540,
      "wires":[
         [
            "f0fd53de.277d",
            "abaa8aca.97acf8"
         ]
      ]
   },
   {
      "id":"f0fd53de.277d",
      "type":"hue-light",
      "z":"2207afb5.f64e2",
      "name":"Hue go 1",
      "bridge":"your yourbridge",
      "lightid":"3",
      "colornamer":true,
      "x":600,
      "y":540,
      "wires":[
         [

         ]
      ]
   },
   {
      "id":"abaa8aca.97acf8",
      "type":"debug",
      "z":"2207afb5.f64e2",
      "name":"",
      "active":true,
      "tosidebar":true,
      "console":false,
      "tostatus":false,
      "complete":"false",
      "x":680,
      "y":500,
      "wires":[

      ]
   },
   {
      "id":"38065ddb.915822",
      "type":"ui_group",
      "name":"Group 1",
      "tab":"69743cf.702fdc4",
      "order":1,
      "disp":true,
      "width":6
   },
   {
      "id":"c61fefdf.9566f",
      "type":"hue-bridge",
      "z":"",
      "name":"Philips hue",
      "bridge":"yourbridgeIP",
      "key":"yourkey",
      "interval":"3000"
   },
   {
      "id":"69743cf.702fdc4",
      "type":"ui_tab",
      "z":"",
      "name":"Hue",
      "icon":"dashboard",
      "order":2
   }
]

**Comment by ozett** [comment]
the flow is hard to copy. i got errors in typo.
may you put it in raw, or code-tags? 
thx a lot
