### ISSUE TITLE
Various errors in debug view showing up constantly

### ISSUE THREAD

**Issue by jakobjp** [Foddy/node-red-contrib-huemagic#64]
Hello

I have spent a few days with huemagic for Node-Red now, and created very useful flows. They all work fine. However, while Node-Red is open in the browser, I get various errors in the debug view constantly.

It seems that huemagic somehow triggers many requests to the Hue bridge while the Node-Red web UI is open. - Could this be avoided somehow? (Seems unnecessary to query the bridge so much, as I would only really want requests to the Hue bridge upon editing or executing flows. Not in the background, updating stuff.)

![screen shot 2018-10-10 at 17 39 21](https://user-images.githubusercontent.com/775512/46748440-ddf78a80-ccb3-11e8-902d-ed94c479babc.png)

**Comment by Foddy** [comment]
Fixed with v1.7.0
