### ISSUE TITLE
This module wants lowercase keys but HAP-NodeJS-based modules send uppercase

### ISSUE THREAD

**Issue by hollyhudson** [Foddy/node-red-contrib-huemagic#65]
Thank you for creating this module!  It is super useful for me.  Here's my issue:

I'm trying to connect my Hue lights to my iOS Home app so that I can control them via node-red or Siri, but all the HomeKit node modules I've tried so far send messages with the keys in uppercase (so `"On": true` instead of `"on": true`.  So I have to use another node to transform the homekit node output before sending it to your Hue nodes, every single time.

The root of the issue seems to be the [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) library that all the homekit modules use, which is where the capitalized keys are defined.  And I'm guessing they're not going to change their side because some huge projects like HomeBridge, which is used by Home Assistant, for instance, also rely on the HAP-NodeJS code.  So here I am.

Not sure what to say.  If you change to uppercase I assume it will break all of your integrations, but if folks are trying to use this with iOS devices, they're going to run into problems.

My [LIFX node module](https://flows.nodered.org/node/node-red-contrib-node-lifx) is also having this lowercase problem, so I'll be reporting it to them, as well.

**Comment by Foddy** [comment]
Sorry, this is not that easy to accomplish.
I hope this has been fixed in the meantime.
