### ISSUE TITLE
Color format/changing

### ISSUE THREAD

**Issue by dezral** [Foddy/node-red-contrib-huemagic#66]
Every time i send at hex / rfb color through the hue lightsnode changes the color code slidely.. .. how come is that?  A clean inject node with ffffff to fff7f6.. trying to make a Philips hue colorpick dashboard widget..

All the others i have made with colortemp and brightness works fine..(with the slider)..

**Comment by Foddy** [comment]
Duplicate of #5 and #30 
Please take a look at this for more information
