### ISSUE TITLE
Can't send On value after setting brightness and color

### ISSUE THREAD

**Issue by rawbear** [Foddy/node-red-contrib-huemagic#68]
It seems that if I send a value for brightness and colour, and also a value on on (true or false), the on value is ignored and "true" is assumed.
I added an additional IF in the function to either send brightness-colour pair OR on (true-false)

Is that normal behaviour?

**Comment by dezral** [comment]
I have this too, the msg.payload.on is ignored if i use payload.brightness.

**Comment by Foddy** [comment]
Fixed with the newest versions
