### ISSUE TITLE
extended message for switching off a light or group is not working

### ISSUE THREAD

**Issue by lucwuyts** [Foddy/node-red-contrib-huemagic#7]
As far as i understand the code, this is not implemented?

**Comment by Foddy** [comment]
What do you mean exactly? What is not implemented? Switching off / on lights and groups or giving them additional parameters like color and brightness with HueMagic?

**Comment by lucwuyts** [comment]
When the message is:   {"on": false}   the lamp does nothing
with {"on": true} the lamp switches on.

I tried this with a lamp and a group

**Comment by lucwuyts** [comment]
I changed line 139 of hue-light.js 
from
  else if( msg.payload.on  )
to
  else if( typeof msg.payload.on != 'undefined' )

And this seems to work.  I don't know if above test is correct. (don't have much javascript experience)

The same change is needed in hue-group.js line 132

**Comment by Foddy** [comment]
Thanks for that! I will check this out as soon as possible and update the code to fix this kind of errors on your environment

**Comment by Foddy** [comment]
Fixed with v1.1.3
