### ISSUE TITLE
Fetch / get bulb values for all devices

### ISSUE THREAD

**Issue by psi-4ward** [Foddy/node-red-contrib-huemagic#71]
Hi,
I want some special logic where I need the current `brightness` and/or `on` state so I thought to store these values in the flow context. It's a bit cumbersome to add these logic for each bulb so it would be nice to have a possibility to get/fetch *all* current values from the bridge.

**Comment by foppenm** [comment]
For now you can also do a http request (is a default step in node-red) to:` http://<ip of your hue bridge>/api/<the api key here>/lights` or if you know the light number: `http://<ip of your hue bridge>/api/<the api key here>/lights/7`. The API key can be retrieved by going to your hue bridge node.
You can then create something like this to toggle a hue light bulb:
![afbeelding](https://user-images.githubusercontent.com/18244647/50527776-beba0d80-0aea-11e9-881c-9599aecc47c9.png)

**Comment by Foddy** [comment]
Now also available on the bridge node (2.0+)
