### ISSUE TITLE
Support for a “virtual bulb”

### ISSUE THREAD

**Issue by hazymat** [Foddy/node-red-contrib-huemagic#76]
The dashboard colorpicker node accepts RGB values (or hex etc.) but it doesn’t accept color temperature, which we may prefer to use, to set the light colour in Node-RED (e.g. from a scene).

I understand the Huemagic bulb node will output the RGB value regardless of how you set it, so you could just connect the output of the Hugemagic bulb node to the dashboard colorpicker (through a change node to split the RGB values into separate objects). But there are some disadvantages to doing it this way:

- it is slower than using an internal value from e.g. MQTT. Presumably Hue hub needs to communicate to the bulb, and the bulb needs to return information. If you are setting e.g. 5 lights at the same time, there can be delays. Either way, I have tested reading the JSON value from MQTT, and this feels much more responsive.

- I presume if the bulb is not connected, the value will not come back? I may be wrong...

**Suggestion**
Could you provide the code to convert between colortemp and RGB?
Alternatively could you provide a “virtual” bulb node that you could send a colortemp message to, and receive the RGB value?

**Comment by Foddy** [comment]
You may want to take a look here: https://github.com/Foddy/node-red-contrib-huemagic/blob/master/huemagic/utils/color.js
