### ISSUE TITLE
Integration with Echo Plus

### ISSUE THREAD

**Issue by Zabov79** [Foddy/node-red-contrib-huemagic#77]
I own an Echo plus and some Philips Hue bulbs. I'd like to use this nodes of your to control lights with a node red flow without use a real hue bridge but the Echo plus. Is it possibile? And how?

**Comment by readeral** [comment]
This might be a better option for you @Zabov79, or at least somewhere to start: https://github.com/datech/node-red-contrib-amazon-echo

**Comment by Foddy** [comment]
Sorry, HueMagic requires a Hue Bridge at the moment.
