### ISSUE TITLE
set brightness of hue group with switch all bulbs on

### ISSUE THREAD

**Issue by darkmoon84** [Foddy/node-red-contrib-huemagic#78]
If the brightness of a group is adjusted with an extended message, all bulbs are activated. From my point of view it would be better to have the possibility of setting the brigthness of a group with msg.payload.brightness, where only the actual configuration is updated.
In case all bulbs are off and the brightness is increased all bulbs could be activated

**Comment by Foddy** [comment]
Please take a look at #128
