### ISSUE TITLE
cannot set color with string

### ISSUE THREAD

**Issue by mbillau** [Foddy/node-red-contrib-huemagic#79]
Odd issue here where every time I try to set the color "red" with strings, my lights revert to the color blue.

Here is a flow that injects "color":"red" or "color":"f80d0d".

When I try to set the color with the string version, my light always turns blue. At first I thought it was reverting to the previous hex value, but if I change the light to any other color, with any method (string, hex), injecting "color":"red" always makes it revert to blue! Super strange!  Using huemagic 1.9.0. 

If I enable "colornaming" I can see in the output that hitting the inject with "color":"red" will report:
"hex: "3b3cff"
color: "blue"

I added a bunch of other nodes to inject based on string, like "color":"green", "color":"white", etc and...they all will turn blue!  So basically.... injecting colors by string works only for the color blue.

[{"id":"ad2a5fce.a9d08","type":"hue-light","z":"54122aa2.7eec94","name":"color light","bridge":"6ae38e2e.c19bd","lightid":"5","colornamer":false,"x":472,"y":1232,"wires":[["2fdc9a05.4b57e6"]]},{"id":"e90d87c9.80f948","type":"inject","z":"54122aa2.7eec94","name":"","topic":"","payload":"{\"color\":\"red\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":282.5,"y":1214,"wires":[["ad2a5fce.a9d08"]]},{"id":"722e6a95.828274","type":"inject","z":"54122aa2.7eec94","name":"","topic":"","payload":"{\"hex\":\"f80d0d\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":281.5,"y":1261,"wires":[["ad2a5fce.a9d08"]]},{"id":"2fdc9a05.4b57e6","type":"debug","z":"54122aa2.7eec94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":643,"y":1231,"wires":[]},{"id":"6ae38e2e.c19bd","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.1.15","key":"TTvODGlag9k1rF4ZWey-TjvJmlq0FmyH3pdeeM7O","interval":"3000"}]

**Comment by geekdave** [comment]
Also having this issue.  Anyone find a workaround?  Setting via rgb works but is more tedious. :)

**Comment by geekdave** [comment]
@mbillau I believe I've found a fix: https://github.com/Foddy/node-red-contrib-huemagic/pull/84

**Comment by mbillau** [comment]
Hi @geekdave, thanks for the comment and fix!
