### ISSUE TITLE
node-red-contrib-node-hue conflicts

### ISSUE THREAD

**Issue by jhaury** [Foddy/node-red-contrib-huemagic#8]
Hey there, great node for NR!!

I originally used node-red-contrib-node-hue for my lights, but after I saw this node I gave it a shot. I could not get it running after install. Upon trying to find my hub it would produce a bunch of popup errors in NR.

Found out that your node conflicts with the node-red-contrib-node-hue node. I had to remove the old node from NR completely (disable may work) to get yours to work properly. Not really a big deal as I don't need two hue nodes running at the same time, but it did take me a minute to figure out. I figured I'd let you know (and others) in case they run into this issue also.

Thanks again!

**Comment by Foddy** [comment]
Thanks for that! :)

I will put a hint in the readme for other users to avoid any confusions with existing hue nodes which are using the same backend routes like HueMagic!
