### ISSUE TITLE
Hue switch with dimmer without output (no debug messages.)

### ISSUE THREAD

**Issue by UltiCa** [Foddy/node-red-contrib-huemagic#81]
![bildschirmfoto 2019-02-20 um 20 59 36](https://user-images.githubusercontent.com/37214146/53125487-65a4ae00-355e-11e9-918e-5396c86e1ceb.png)

I have places a hue-switch with debug-node, in the switch the state (changed state) is displayed, but the debug node does not receive any messages. ???

The bridge software and all lamps, switches, sensors are up to date (today).

https://discourse.nodered.org/t/i-have-a-problem-with-the-hue-switch/8235/6

**Comment by Foddy** [comment]
Should be fixed in the latest release
