### ISSUE TITLE
Option to turn off automatic status payload in light/group node

### ISSUE THREAD

**Issue by readeral** [Foddy/node-red-contrib-huemagic#85]
I'm currently using the group node in a subflow to determine if any lights are on in a group, and (with the press of a smart button) to toggle my lights.

(as an aside, the reason I have it in a subflow as it's not a simple 1-1 relationship of all lights in the group to turn on or off, rather, if one light is on, turn it off, but if no lights are on, then turn on all 3. Etc. This logic is required for 3 buttons and 3 lights)

What I'm finding is, I'm using the node's status to find anyOn, if the answer is true, then I'm sending data out of my sub-flow to a node to turn off the lights - which is triggering the group node to send out the newly updated status of false - which is tripping my logic to turn the lights back on again. And round and round we go.

I could write myself a function using global state etc. to mitigate this problem, but a far simpler option would be to have a checkbox which both turns on the ability to report status with a msg.payload.status property, and turns off the auto-sending of status on a state change. That would stop the loop problem without needing to increase the node set.

Thoughts? I'm going to try modifying the package and come up with an approach to submit as a pull request, but would appreciate any input from @Foddy especially.

**Comment by readeral** [comment]
Ah ok, I see what I am proposing is duplicating the function of universal mode - don't mind me then.

Although I do wonder if there's benefit to a use case where someone is choosing their group using the GUI, it's not worth my effort for that possible edge case.

Instead of programming in my proposed changes, instead I'll submit a pull request against the documentation for Universal Mode to make the benefit of deactivating light update events a little more discoverable.

**Comment by blahbla** [comment]
As I understand the documentation I have to write as an example in a function mode: msg.Topic = 2; and send msg into the group node to activate Universal mode. That doesn't work though as it still gives updates every minute or so. Am I reading the docs wrong?

**Comment by Foddy** [comment]
This node‘s functionality has been changed entirely in the latest version. If you want to use a group in universal mode without and skip all the status messages from other groups except the status message of your command, you can do it now.
