### ISSUE TITLE
query scense

### ISSUE THREAD

**Issue by JueWes** [Foddy/node-red-contrib-huemagic#87]
Is there a way to find out which scene is set for a group, e.g. to receive information about manual (via the physical Hue Switch) scene changes?
Currently the scene node sends an event (which does include info about the scene that is currently set) only after receiving a command.
If the HueScene node would offer a way to make it provide the currently set scene, I could use HueSwitch.on.long_released to find out what teh scene has been set to manually.

**Comment by drasier** [comment]
This may not answer your question but I managed to use the "Hue Rule" module to make a scene event handler. Every time a scene is triggered in the Hue System a rule is being launched. It takes a little bit of time and debugging (Hue Bridge) to find out which rule ID match each scene.

![imagen](https://user-images.githubusercontent.com/6588377/77824996-c8279080-7106-11ea-9848-080aa53829fa.png)

So in this example, every time the scene "aurora" is set up the rule ID:37 is triggered.

I used this to keep my Nanoleaf Canvas synced with my hue lights and it works great.

Hope it helps.
