### ISSUE TITLE
Using bridge eventing instead of polling

### ISSUE THREAD

**Issue by brammh** [Foddy/node-red-contrib-huemagic#88]
<deleted org post>

**Comment by oskretc** [comment]
Where did you found the info on how to configure events on the bridge?

**Comment by Foddy** [comment]
I’ve been also searching now for a few hours to find some kind of news or documentation for this without success.... :S

**Comment by oskretc** [comment]
Yes, this is a game-changer for many projects not only for hue magic. Very curious to know where the OP got this info

**Comment by brammh** [comment]
Apologies, this is not yet stable / cannot be used. Not capable of handling mutliple subscribers at this point in time. Will be in some future release is expected. I updated my org question...
