### ISSUE TITLE
Missing Hue-Light and Hue-Group

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#89]
Just updated this and I have now two missing node types as above?

**Comment by Foddy** [comment]
Can you try to update to the latest version (2.0.1)? I found an error in the Hue group node but Hue Light nodes shouldn't be affected from this. For me, it looks like the new dependency `get-image-colors` was not be installed during your update process.

Are you running NodeJS 10+?

**Comment by lespatots** [comment]
10 Aug 17:52:32 - [info] Waiting for missing types to be registered:
10 Aug 17:52:32 - [info]  - hue-light
10 Aug 17:52:32 - [info]  - hue-group

node-red-contrib-huemagic
2.0.1
[object Object]
[object Object]
 11 nodes <http://192.168.1.113:1880/#>in use <http://192.168.1.113:1880/#>
Foddy,

Above are some of the reports I get, the first is from the ’start’ script and the second the Manage display.

Still complains about both nodes as missing!

**Comment by Foddy** [comment]
Sorry I can't reproduce this error. I removed HueMagic completely and installed it from the Node-RED web interface again without any problems.

If you already checked if you are running a supported NodeJS (10+) and Node-RED version, please try removing huemagic and reinstalling. Your flows / configuration will not be deleted during a fresh install.

**Comment by lespatots** [comment]
My bad,

Seems my Nodjs is hopelessly out of date. My attempt to upgrade has thrown new errors and I guess a new build from scratch might be the best way forward.

Thanks
