### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by diversit** [Foddy/node-red-contrib-huemagic#91]
**Describe the bug**
I updated my installation to latest Node-Red 0.20.7 and updated this plugin to 2.0.2.
Now I see this error appearing in the log:
```
12 Aug 17:43:43 - [debug] [hue-bridge:Philips hue beta] TypeError: Cannot read property 'length' of undefined
     at HueBridge.getUpdates (/data/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:94:24)
     at scope.client.rules.getAll.then.then.results (/data/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:61:29)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Flow to Reproduce**
I cannot share my flow, but this should appear in any flow defining a Hue Bridge node.

**Expected behavior**
Code should execute without errors.

**Please complete the following information:**
 - NodeRED version: 0.20.7 (docker image arm64)
 - NodeJS version: 8.1.3
 - Device running NodeRED: Pine64

**Comment by Foddy** [comment]
Okay. I guess it's your NodeJS version. Please consider updating to v10+ and try again if possible.

**Comment by diversit** [comment]
I'm using the Docker image of Node-red and therefore using the Node version using in that image.
So I guess they think Node-red is not ready to move to NodeJS v10+ yet.

**Comment by Foddy** [comment]
This is a bit weird regarding the docker version. As you can see in this article https://nodered.org/docs/faq/node-versions Node-RED also recommends using the v10+.

HueMagic on the other hand uses some new functions and syntax that are obviously not supported by the < v10 versions of NodeJS. If you install Node-RED by using their install script on a Debian based system, Node-RED also installs the v10 Version by default. For now it seems like the only way to get the latest version running is to upgrade the node version. Sorry..

**Comment by diversit** [comment]
Just looked at the docker tag for the image.
There seem to be v8 and v10 builds indeed.
Strangely there seem to be only v8 builds for the Raspberry Pi which is why
I have a NodeJS v8 instead of v10.
I'll add an ticket in that project to also create a v10 build for RPi.
Thanks for your responses.

**Comment by diversit** [comment]
There is now a PR (4 days old) to create Node v10 images for Arm
architectures: https://github.com/node-red/node-red-docker/pull/124
So I just have to wait for it to be released I guess.

**Comment by altery** [comment]
What "new functions and syntax" do you mean, @Foddy ? I think it's just a bug in HueJay regarding Promise handling: https://github.com/Foddy/node-red-contrib-huemagic/issues/96

**Comment by DamianosS** [comment]
Hi,

I'm running into the same (or at least a similar) issue:
```
Oct 24 16:26:54 ccu3-webui daemon.debug node-red[1014]: [hue-bridge:Philips hue] TypeError: Cannot read property 'length' of undefined
Oct 24 16:26:54 ccu3-webui daemon.debug node-red[1014]: [hue-bridge:Philips hue]     at HueBridge.getUpdates (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:94:25)
Oct 24 16:26:54 ccu3-webui daemon.debug node-red[1014]: [hue-bridge:Philips hue]     at scope.client.rules.getAll.then.then.results (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:61:29)
Oct 24 16:26:54 ccu3-webui daemon.debug node-red[1014]: [hue-bridge:Philips hue]     at process._tickCallback (internal/process/next_tick.js:68:7)

```
I'm running Node Red 1.0 ([Redmatic](https://github.com/rdmtc/RedMatic) 5.2.0) on a Homematic, which is basically a Pi. HueMagic version is 2.0.4

Thanks!
Any idea?

**Comment by arvdsar** [comment]
Hi, 
Me too on Node-red 1.0.2 with Hue magic 2.0.4 running on Node-Red docker image with NodeJS 10.16.3

26 Oct 17:50:53 - [debug] [hue-bridge:Philips hue] TypeError: Cannot read property 'id' of 
undefined                                                                                           
    at EventEmitter.<anonymous> (/usr/src/node-red/node_modules/node-red-contrib-huemagic/red/hue-li
ght.js:81:41)                                                                                       
    at EventEmitter.emit (events.js:198:13)                                                         
    at HueBridge.emitUpdates (/usr/src/node-red/node_modules/node-red-contrib-huemagic/red/hue-bridg
e-config.js:189:18)                                                                                 
    at scope.client.rules.getAll.then.then.then.updates (/usr/src/node-red/node_modules/node-red-con
trib-huemagic/red/hue-bridge-config.js:68:11)                                                       
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by hklages** [comment]
I have a similar/same error: 
`[hue-bridge:Philips hue] TypeError: Cannot read property 'length' of undefined
Dec 16 07:47:55 ccu3-webui daemon.debug node-red[989]: [hue-bridge:Philips hue]     at HueBridge.getUpdates (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:94:25)
Dec 16 07:47:55 ccu3-webui daemon.debug node-red[989]: [hue-bridge:Philips hue]     at scope.client.rules.getAll.then.then.results (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:61:29)
Dec 16 07:47:55 ccu3-webui daemon.debug node-red[989]: [hue-bridge:Philips hue]     at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by ozett** [comment]
i saw it, too

**Comment by Foddy** [comment]
Should no longer occur with the latest version
