### ISSUE TITLE
Fetch all devices and resources

### ISSUE THREAD

**Issue by falke1987** [Foddy/node-red-contrib-huemagic#92]
I want to get the msg.sensors but i have nö ideas how it works. I tried a lots of cases but nothing happend. Would it be possible to add short examples in the documentation?

Thank you very much.

**Comment by lucaberta** [comment]
You have to use a function to create the correct payload to send to the bridge module, and get the required answer.

You would need to use:

`msg.payload={"fetch":"sensors"}
return msg;`

in the function node, and connect it between the trigger and the bridge nodes.

Hope this helps.

**Comment by falke1987** [comment]
Thanks for the feedback.
Under the bride node i can see the message **"fetching sensors..."** but at the output i added a debug-node and the message at this node is **"msg.payload : undefined undefined"**

Do you have any ideas whats wrong?

**Comment by lucaberta** [comment]
@falke1987 here is a clipboard export of a little test which works on my system, import it, try it and let us know how it goes:

[{"id":"2d462d08.1a7222","type":"hue-bridge-node","z":"e22ac9aa.e1b468","name":"","bridge":"ded6eb76.c08c7","autoupdates":true,"x":490,"y":200,"wires":[["e75f2506.581128"]]},{"id":"e75f2506.581128","type":"debug","z":"e22ac9aa.e1b468","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":690,"y":200,"wires":[]},{"id":"f465a725.943dd8","type":"debug","z":"e22ac9aa.e1b468","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":570,"y":120,"wires":[]},{"id":"c9288579.9ec7e8","type":"inject","z":"e22ac9aa.e1b468","name":"","topic":"","payload":"sensors","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":200,"wires":[["f619f796.b37cb8"]]},{"id":"f619f796.b37cb8","type":"function","z":"e22ac9aa.e1b468","name":"","func":"msg.payload={\"fetch\":\"sensors\"}\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":200,"wires":[["2d462d08.1a7222","f465a725.943dd8"]]},{"id":"ded6eb76.c08c7","type":"hue-bridge","z":"","name":"iot-hue","bridge":"192.168.5.116","key":"oO3hjHRj8KS-Ha11JT85dasz06uTRLZgwvnUTahy","interval":"3000"}]

**Comment by falke1987** [comment]
Hello @lucaberta thank you very much for your help i am not able to import the clipboard into node red... Something worng with it?

**Comment by lucaberta** [comment]
@falke1987 I too received an error, try with this version instead:

[
    {
        "id": "2d462d08.1a7222",
        "type": "hue-bridge-node",
        "z": "e22ac9aa.e1b468",
        "name": "",
        "bridge": "ded6eb76.c08c7",
        "autoupdates": true,
        "x": 490,
        "y": 200,
        "wires": [
            [
                "e75f2506.581128"
            ]
        ]
    },
    {
        "id": "e75f2506.581128",
        "type": "debug",
        "z": "e22ac9aa.e1b468",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 690,
        "y": 200,
        "wires": []
    },
    {
        "id": "f465a725.943dd8",
        "type": "debug",
        "z": "e22ac9aa.e1b468",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 570,
        "y": 120,
        "wires": []
    },
    {
        "id": "c9288579.9ec7e8",
        "type": "inject",
        "z": "e22ac9aa.e1b468",
        "name": "",
        "topic": "",
        "payload": "sensors",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 150,
        "y": 200,
        "wires": [
            [
                "f619f796.b37cb8"
            ]
        ]
    },
    {
        "id": "f619f796.b37cb8",
        "type": "function",
        "z": "e22ac9aa.e1b468",
        "name": "",
        "func": "msg.payload={\"fetch\":\"sensors\"}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 300,
        "y": 200,
        "wires": [
            [
                "2d462d08.1a7222",
                "f465a725.943dd8"
            ]
        ]
    },
    {
        "id": "ded6eb76.c08c7",
        "type": "hue-bridge",
        "z": "",
        "name": "iot-hue",
        "bridge": "192.168.5.116",
        "key": "oO3hjHRj8KS-Ha11JT85dasz06uTRLZgwvnUTahy",
        "interval": "3000"
    }
]

**Comment by falke1987** [comment]
now it works thank you very much for your great support.
