### ISSUE TITLE
Bridge IP : Port definition ignored

### ISSUE THREAD

**Issue by lukicsl** [Foddy/node-red-contrib-huemagic#94]
I have my bridge (deconz) exposing 8080.
I defined IP:port.
Querying the API key works, all other stuff fails.
![image](https://user-images.githubusercontent.com/23736716/63633060-0d03ba00-c642-11e9-8997-685d91c3fb43.png)

**Comment by gollenia** [comment]
Same here

**Comment by Foddy** [comment]
Should not happen in the latest release
