### ISSUE TITLE
Toggle not working

### ISSUE THREAD

**Issue by DIYtechie** [Foddy/node-red-contrib-huemagic#97]
**Describe the bug**
Toggle does not seem to be working? I'm probably doing something wrong, but can't figure out what.

**Expected behavior**
Injecting 0 or 1 works, but injecting "toggle" as string or 2 as number does nothing. I expected that this command would toggle the light?

**Screenshots**
![Skærmbillede 2019-09-14 kl  21 07 10](https://user-images.githubusercontent.com/20454469/64912763-0265ad80-d734-11e9-9fc6-3b23ce21e1be.png)
![Skærmbillede 2019-09-14 kl  21 06 43](https://user-images.githubusercontent.com/20454469/64912762-01cd1700-d734-11e9-9e91-dc2481a0571d.png)

**Please complete the following information:**
 - NodeRED version: 0.20.5
 - NodeJS version: ??
 - Device running NodeRED: Raspberry Pi 3 model B
 - huemagic version: 2.0.2

**Comment by Tscherno** [comment]
Same issue.

**Comment by bluenazgul** [comment]
same issue here, tried to config the "smart button", changed everything that msg.payload sends "toggle" but it happens nothing

**Comment by ArnieX** [comment]
Toggle works for me. It isn’t supposed to be string but json. Basically sending msg.payload.toggle = anything. Si using inject choose JSON and enter {"toggle":1}. This should work.
![A139CA1A-1CE6-4698-BA90-59F7B7A387A3](https://user-images.githubusercontent.com/2325116/69492411-d8063e00-0ea2-11ea-9af5-0e3b3019b9fa.png)

**Comment by Tscherno** [comment]
Thank you! That really needs to go to the documentation.

**Comment by ArnieX** [comment]
You are welcome ;). Well it's there but it's probably a little cumbersome to understand as it doesn't require to hold any settings when dispatched. But it is basically the same as any other key/value pair that is required to do something.

**Comment by PiRune** [comment]
Yes. Thank you.
