### ISSUE TITLE
hue sensor name - temperature 

### ISSUE THREAD

**Issue by RogierQ** [Foddy/node-red-contrib-huemagic#99]
**Describe the solution you'd like**
I would love to see my sensor name as set in the hue app on the output of the temperature node

**Comment by ThomasPoett** [comment]
You cannot change the name within HUE App. Use e.g. HUETRO on Windows. there you see the naming for LUX/TEMP and you can change the name. This is therefore not part of the node-red pack

**Comment by RogierQ** [comment]
Ok clear. But when i use the motion node i get the name. Isnt this possible with the temp node?

**Comment by ThomasPoett** [comment]
![image](https://user-images.githubusercontent.com/43953071/66647753-0d740680-ec2a-11e9-9094-4aa3c543536b.png)
![image](https://user-images.githubusercontent.com/43953071/66647786-1f55a980-ec2a-11e9-89a4-4ee8c39c99ce.png)
That's mine and how I change all three names

**Comment by RogierQ** [comment]
Wow looks cool! Also with the sensor info in light grey ;-)

**Comment by ir-fuel** [comment]
Any solution for people who don't have a windows computer?
I have 9 sensors and I see no way of knowing which one is which.

**Comment by ThomasPoett** [comment]
I forgot the name. but on IOS are some more apps available where you can change the names with

**Comment by ir-fuel** [comment]
In the mean time I discovered that the order of the temperature sensors in the "Hue Labs" tab in the iOS official Hue app seems to be the same as the temperature sensor name index.
